gramineproject/gramine

- LibOS/shim/include/arch/x86_64/shim_entry_api.h
- LibOS/shim/include/shim_tcb.h
Just removing some unused code.
We should ping @stefanberger after merging this, he'll probably need analogous change in his port.
~Caveat: We probably shouldn't merge it before the build system rewrite, as it changes a file which is incorrectly dep-tracked and only `git clean -dfx` helps.~
// This is a migration of https://github.com/gramineproject/graphene/pull/2494 to the new repo. Now as we changed the repo, everyone will most likely be building everything from scratch, so we should be able to merge it safely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1)
> [LibOS] Remove unused canary in shim_tcb

- LibOS/shim/src/sys/shim_pipe.c
- LibOS/shim/test/regression/pipe_nonblocking.c
Currently, in Gramine we don't save the `O_NONBLOCK` flag for the write end of the pipe. We set the `O_NONBLOCK` flag for the PAL_HANDLE but this isn't propagated to the SHIM_HANDLE when creating pipe. This commit fixes the corner case.
Also, updated the `pipe_nonblocking` regression test to catch this corner case.
Please run both graphene-direct and graphene-sgx regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/35)
> [LibOS] Fix setting of `O_NONBLOCK` flag at the write end of pipe

- Pal/src/host/Linux-SGX/tools/is-sgx-available/Makefile
- Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp
Clang doesn't like Intel syntax.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/42)
> [Pal/Linux-SGX] tools/is-sgx-available: Change asm to AT&T syntax

- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/test/ltp/ltp.cfg
- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux/db_files.c
This commit fixes the problem in which the user is not allowed to manipulate (unlink, chmod) files without read permissions. Because PAL requires us to open such files, we override the host mode in order to be able to open them.
Fixes https://github.com/gramineproject/graphene/issues/1248.
The tests should pass; I also unskipped the LTP tests that fail due to this problem.
The same failure started appearing for a newly added `rename14` test ([link to Jenkins](https://leeroy.cs.unc.edu/job/graphene-direct-sanitizers/59/testReport/junit/apps/LTP/test_direct___rename14/)) so that should be fixed as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/39)
> [LibOS,Pal] Fix operations on files without permissions

- LibOS/shim/include/shim_handle.h
- LibOS/shim/include/shim_types.h
- LibOS/shim/src/bookkeep/shim_handle.c
- LibOS/shim/src/fs/proc/thread.c
Previously, LibOS used `typedef uint16_t FDTYPE`. This was unnecessary and hard-to-read. Moreover, it led to a bug in `__enlarge_handle_map()`: the new size was of 64-bit type `size_t` but it was assigned to `fd_size` field of 16-bit type `FDTYPE`, which led to silent truncation. This resulted in failing asserts, because active FDs suddenly became greater than the limit in the FD map.
This commit fixes this bug by changing the type from 16-bit to 32-bit, and also removes the opaque and confusing `FDTYPE`.
Fixes https://github.com/gramineproject/gramine/issues/28
Current tests should be sufficient. I don't think we want a regression test that opens 64 thousand FDs.
--- …
> [LibOS] Get rid of `FDTYPE` and replace it with `uint32_t`

- LibOS/shim/src/sys/shim_open.c
- LibOS/shim/test/ltp/runltp_xml.py
- Pal/src/db_streams.c
This fixes various small corner cases in filesystem code. As mentioned in #29, our test runner failed to detect these because the LTP test cases actually returned 0.
The LTP runner is also fixed so that this doesn't happen again.
Fixes #29.
The LTP tests fixed are `pwrite02`, `pwrite03` and `ftruncate03`.
Jenkins should pass, you can also run the above tests manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/33)
> [LibOS] Fix filesystem corner cases 

- .readthedocs.yaml
After merging this to master, docs should be fixed on https://gramine.rtfd.io/.
How to test: https://gramine.readthedocs.io/en/woju-rtfd-yaml/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/45)
> [Docs] Add .readthedocs.yaml

- LibOS/shim/test/ltp/ltp.cfg
We aren't gonna require root and make invasive changes to the test machines to test Graphene, so unfortunately we have to disable these.
Closes gramineproject/graphene#2297, closes gramineproject/graphene#2479.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/61)
> [tests] Skip some flaky and unreliable LTP tests

- .ci/ubuntu18.04.dockerfile
- .readthedocs.yaml
- Documentation/requirements.txt
Currently docs are failing because of this commit: readthedocs/sphinx_rtd_theme@3693d4c, which got into released version 2 days ago: https://github.com/readthedocs/sphinx_rtd_theme/releases/tag/1.0.0
Test: docs job in jenkins and also:
- https://gramine.readthedocs.io/en/woju-sphinx-from-repo/
- https://readthedocs.org/api/v2/build/14721879.txt
Branch name has no bearing on the content, initially I wanted to `apt-get install` things in rtfd container, but [the documented solution](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-system-packages) doesn't work on several important packages like sphinx and sphinx-rtd-theme, which are installed from pip anyway.
--- …
> [Docs] Fix docs compilation

- Pal/src/host/Linux-SGX/db_main.c
The tomlc99 library to parse TOML files uses a lot of memory during `toml_parse()`. Sometimes apps have very large manifest files (>10MB), and parsing these manifest files requires more than 64MB of preallocated memory pool in Linux-SGX PAL.
Since this function is called before PAL can read `loader.pal_internal_mem_size`, there is no way to learn the additional memory size for PAL from the manifest. Thus we use a heuristic to pre-allocate some PAL memory before `toml_parse()`.
I understand that this fix is... dubious, but couldn't come up with something better.
Fixes https://github.com/gramineproject/graphene/issues/2680
Try with huge manifest files. E.g., I did this in our Bash example:
```
diff --git a/Examples/bash/manifest.template b/Examples/bash/manifest.template
+# …
```
> [Pal/Linux-SGX] Pre-allocate more PAL memory on huge manifest files

- CI-Examples/bash/manifest.template
- CI-Examples/blender/blender.manifest.template
- CI-Examples/busybox/busybox.manifest.template
- CI-Examples/lighttpd/lighttpd.manifest.template
- CI-Examples/memcached/memcached.manifest.template
- CI-Examples/nginx/nginx.manifest.template
- CI-Examples/python/python.manifest.template
- CI-Examples/ra-tls-mbedtls/client.manifest.template
- CI-Examples/ra-tls-mbedtls/server.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template
- CI-Examples/redis/redis-server.manifest.template
- CI-Examples/sqlite/manifest.template
All example manifests now use the TOML-array syntax for `sgx.trusted_files`, `sgx.allowed_files`, `sgx.protected_files`.
All examples should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/66)
> [CI-Examples] Update examples to use TOML-array syntax for files

- Pal/src/host/Linux-SGX/enclave_ocalls.c
Fixes #67.
NULL is a valid parameter for these system calls, as long as count is 0 (and otherwise, they will fail with -EFAULT anyway).
This fixes Gramine's own `write`/`pwrite`, which recently have been modified not to specialcase 0, and started failing with -EPERM because of the ocall wrapper.
As mentioned in #67, you can run `pwrite03` and `write02` LTP tests manually under SGX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/69)
> [Pal/Linux-SGX] Accept NULL in `write`/`pwrite` ocalls

- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap_urts.c
Per as https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/193,  some thread related `ocall` were added.  we here mock those APIs for graphene `ra-tls`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/65)
> Mock ocall in sgx_pthread.edl for in-enclave RA verifier

- Pal/src/host/Linux-SGX/db_misc.c
On some systems - the RDTSC and the system clock drifts away from each other significantly, that at higher gaps (above 100ms), rdtsc falls behind, and this gets flagged by LTP. Currently the correction is done every 10 seconds ```#define TSC_REFINE_INIT_TIMEOUT_USECS 10000000``` .  The timeout is now reduced to 50ms. This satisfies LTP drift thresholds, and does not impact performance either(tested with SPECpower and Redis).
Fixes https://github.com/gramineproject/graphene/issues/2666 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/38)
> [LibOS] Correct RDTSC instruction drift with system clock more often

- CI-Examples/ra-tls-mbedtls/.gitignore
- CI-Examples/ra-tls-mbedtls/README.md
- CI-Examples/ra-tls-mbedtls/server.manifest.template
- CI-Examples/ra-tls-secret-prov/.gitignore
- CI-Examples/ra-tls-secret-prov/README.md
- CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template
- Pal/src/host/Linux-SGX/tools/ra-tls/meson.build
This PR adds `libsgx_dcap_quoteverify.so` dependency to DCAP-based libs. This was missed in the `[Pal/Linux-SGX] Compile SGX tools with Meson` commit, even though the dependency was already baked in one of the meson files.
As an aside, the `ra-tls-mbedtls` and `ra-tls-secret-prov` examples got a bit stale, so I updated them as well. Surprisingly, we had the bug with `LD_LIBRARY_PATH` in those manifests for a long time, and noone noticed.
CI is enough for `ra-tls` examples.
Unfortunately, we don't have DCAP-enabled SGX machines in our Jenkins CI, so we can't test DCAP-based libraries (that's why the bug was missed in the previous commits). If you want to test, do it manually on a DCAP-enabled machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [Pal/Linux-SGX] Add `libsgx_dcap_quoteverify.so` dependency to DCAP-based libs

- Pal/src/host/Linux-SGX/db_files.c
A Protected File sometimes needs to be read or written, regardless of the actual open mode that was requested (e.g. to read or write some metadata).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/78)
> [Pal/Linux-SGX] Always open Protected Files in RW mode

- Pal/src/host/Linux-SGX/enclave_framework.c
"allowed_files" is an insecure feature, which cannot be safely used in production environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/81)
> [Pal/Linux-SGX] Warn about "allowed_files" usage

- LibOS/shim/src/bookkeep/shim_process.c
- LibOS/shim/src/sys/shim_file.c
- LibOS/shim/src/sys/shim_open.c
- LibOS/shim/test/ltp/ltp.cfg
This change makes Gramine respect the process umask when creating new files using `open` and `mkdir`. It also initializes it correctly.
Fixes one of the issues in https://github.com/gramineproject/graphene/issues/2543.
LTP test `umask01` (which this PR unskips) checks umask support in `open(O_CREAT)`. As far as I can tell, there's no corresponding LTP test for `mkdir`, but I'm not sure if this is important enough to add one of our own.
Anyway, a manual test (to be run with `python` example) looks like this:
```python
import os
for umask in [0o000, 0o022, 0o077]:
if os.path.exists('dir'):
os.rmdir('dir')
os.umask(umask)
os.mkdir('dir', 0o777)
print(oct(os.stat('dir').st_mode))  # should print 0o40777, 0o40755, 0o40700
```
--- …
> [LibOS] Support umask

- Pal/src/host/Linux/db_main.c
This change causes PAL to report the vDSO range based on `/proc/self/maps`, instead of parsing the ELF mapped there and
processing PT_LOAD commands.
On my system, the former method returns 1 page, even though according to `/proc/self/maps` vDSO occupies 2 pages. As a result, under some circumstances (Docker and ASLR disabled) LibOS tries to map memory over vDSO.
I found this while investigating #89, which actually breaks on my system (and this PR fixes it).
(With ASLR disabled, Linux maps vDSO _below_ the range occupied by PAL, so it is part of the "user address range" passed to LibOS. LibOS gets also notified of "preloaded ranges" including vDSO, but the computed length is wrong, so it ends up believing vDSO only occupies one page instead of two).
I also verified this change manually …
> [Pal/Linux] Fix vDSO range retrieval

- LibOS/shim/src/sys/shim_socket.c
Previously, do_sendmsg iterated through all iovec buffers supplied by the user, regardless of whether the host-level write to the socket (via DkStreamWrite) was able to send the whole buffer or only part of the buffer.
This could lead to data corruptions: Graphene would send only some parts of the buffers (i.e., with gaps) but would report to the user app the total sum of sent bytes (i.e., without gaps).
This PR fixes this by simply bailing out on the first encountered host-level partial write.
Fixes https://github.com/gramineproject/graphene/issues/2664.
Create a communication channel between client and server and send large size data for example 4194299 bytes multiple times.
--- …
> [LibOS] Return a partial write in do_sendmsg if host-level write was partial

- .ci/lib/config-docker.jenkinsfile
- Pal/src/host/Linux/db_main.c
- Scripts/docker_seccomp.json
Gramine fork() emulation does fork()+execve() on the host system which effectively remaps PAL executable to a new address if ASLR is on. The new location could collide with other mappings that are later on sent to the child process via checkpointing mechanism (user mapped regions).
Fixes https://github.com/gramineproject/graphene/issues/2589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/89)
> [Pal/Linux] Disable host-level ASLR in PAL Linux

- subprojects/packagefiles/glibc-2.34/compile.sh
if Gramine is built with the default prefix `/usr/local`, Glibc requires the option `--disable-sanity-checks` otherwise it complains like this:
"On GNU/Linux systems the GNU C Library should not be installed into /usr/local since this might make your system totally unusable. We strongly advise to use a different prefix."
Note that `--disable-sanity-checks` simply silences this warning -- we actually install Glibc under `gramine/runtime/glibc`.
Fixes #97.
Try to build with default prefix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/98)
> [Glibc] Fix the build of Glibc with default prefix `/usr/local`

- Documentation/devel/performance.rst
We forgot to update our documentation when ICX (Icelake Server) machines got available. Our documentation on EPC size periodically confused people (they were surprised that ICX has GBs of EPC memory because our docs indicates otherwise).
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/92)
> [Docs] Mention large EPC size on Icelake servers

- Pal/src/host/Linux-SGX/db_streams.c
Signed-off-by: aneessahib <anees.a.sahib@intel.com>
Fixes a Klocwork sighting. The function could return negative incorrectly even when there are no failures due to uninitialized return variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/93)
> [PAL] Initialize ret variable to avoid incorrect return value

- LibOS/shim/test/ltp/ltp.cfg
- Pal/src/host/Linux/db_sockets.c
Signed-off-by: Sonali Saha <sonali.saha@intel.com>
Fixed the issue of an ephemeral port is not allocated when port number in a socket address is specified as 0 when calling bind.
Fixes gramineproject/graphene#2291
Follow the steps to reproduce mentioned in issue gramineproject/graphene#2291.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/76)
> [Pal/Linux] Assign an ephemeral port if port 0 was specified in `udp_bind`

- Documentation/manifest-syntax.rst
- LibOS/shim/test/regression/.gitignore
- LibOS/shim/test/regression/Makefile
- LibOS/shim/test/regression/env_passthrough.manifest.template
- LibOS/shim/test/regression/test_libos.py
- Pal/src/db_main.c
It is now possible to define some envvars that are passed through from the host inside the Graphene instance (previously the only way to pass envvars was to set `loader.insecure__use_host_env`).
This was originally developed as https://github.com/gramineproject/graphene/pull/2641. Based on an offline discussion with @mkow, I simplified the code as much as possible (it overapproximates some things, but we don't care about a handful of envvars.)
Fixes https://github.com/gramineproject/graphene/issues/2356
A new LibOS regression test is added + old tests should be sufficient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/56)
> Add `loader.env.[ENVIRON] = {passthrough=true}` manifest option

- Pal/src/host/Linux-SGX/enclave_entry.S
Creating a frame with CPU context on signal stack when handling an exception was done without any bound checks. Malicious host could generate any amount of signals and cause these frames to overflow the stack. This commit fixes it by adding bound checks, effectively disallowing more than ~9 nested exceptions (which should be more than enough in normal case).
Try running in Gramine with SGX:
```c
#define _GNU_SOURCE
#include <err.h>
#include <sched.h>
int main(void) {
while (1) {
if (sched_yield() < 0) {
err(1, "sched_yield");
}
}
}
```
and concurrently `timeout 4 bash -c 'while true; do kill -SIGCONT pid_of_above_program; done'`. This will cause weird behavior on the current master (most likely a crash) and with this PR the process will hang in newly added `FAIL_LOOP`
---
This change …
> [Pal/Linux-SGX] Detect signal stack overflow in "enclave_entry.S"

- CONTRIBUTING.rst
- Pal/src/db_main.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/enclave_framework.c
Previously, all insecure-manifest-option messages were scattered. Some insecure manifest options were not warned about at all (e.g. `sgx.debug`). This commit adds a uniform message with all insecure manifest options detected, and only prints this message for the SGX PAL.
Run smth manually. E.g.:
```
$ gramine-sgx ./helloworld
---------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:
- sgx.debug = true                             (this is a debug enclave)
- loader.insecure__use_cmdline_argv = true     (forwarding command-line args to the app)
- sys.insecure__allow_eventfd = true           (host-based eventfd is enabled)
- sgx.allowed_files = [ ... ]                  (some files allowed for …
```
> [Pal/Linux-SGX] Add uniform message on using insecure manifest options

- LibOS/shim/include/shim_thread.h
- LibOS/shim/src/bookkeep/shim_pid.c
- LibOS/shim/src/bookkeep/shim_thread.c
- LibOS/shim/src/ipc/shim_ipc_pid.c
- LibOS/shim/src/shim_init.c
- LibOS/shim/src/sys/shim_clone.c
Previously allocating ID for a new process did not immediately change the ownership of this ID (it happened later in the child process). This could cause a issues when one thread issues a `fork` syscall and another exits, releasing its own thread ID - IPC leader might get notified to release an ID range, which it thinks is a part of a bigger one, since it was not yet notified about the ID ownership change.
This commit causes allocating a new ID to also immediately notify IPC leader about ownership change, atomically w.r.t. other threads in the current process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/109)
> [LibOS] Make `get_new_id` immediately move ID ownership if needed

- LibOS/shim/src/meson.build
This ensures that the LibOS binary (`libsysdb.so`) is not incorrectly marked as requiring executable stack.
As mentioned in the commit, it doesn't actually change anything for Gramine, at least right now. It just makes the `libsysdb.so` library look less suspicious. :)
The only difference is in ELF metadata. You can check that:
* using checksec: `checksec --file=libsysdb.so` (should say "NX enabled")
* using readelf: `readelf -l libsysdb.so` (the `GNU_STACK` section should say `RW`, not `RWX`)
If you're curious about the `.o` files, they should all have the `.note.GNU-stack` section (which you can check using `readelf -S`). `vdso-data.o` did not have that section before.
--- …
> [LibOS] Make sure LibOS doesn't have executable stack flag

- Pal/src/host/Linux-SGX/gsgx.h.in
- Pal/src/host/Linux-SGX/meson.build
- meson.build
When rewriting `gsgx.h` generation to Meson, we started adding the SGX driver include path to `-I`. This breaks the build process when the path points to kernel headers.
Instead, we should include only the SGX header file (by absolute path), like we did before.
Gramine should compile with the in-kernel driver correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/117)
> [Pal/Linux-SGX] Fix SGX driver path

- .ci/lib/config-asan.jenkinsfile
- LibOS/shim/test/ltp/Makefile
- LibOS/shim/test/ltp/runltp_xml.py
Gramine compiled with ASan builds is 2x slower, and some tests like
`sendfile09` often fail because of that.
Jenkins will, hopefully, pass :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/118)
> [LTP] Increase timeouts when running with ASan

- python/graminelibos/manifest.py
"sgx.trusted_files.key = value" syntax is deprecated, but still supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/119)
> [python] Restore old trusted files syntax support

- Documentation/manifest-syntax.rst
- LibOS/shim/test/regression/.gitignore
- LibOS/shim/test/regression/Makefile
- LibOS/shim/test/regression/attestation.c
- LibOS/shim/test/regression/file_size.c
- LibOS/shim/test/regression/manifest.template
- LibOS/shim/test/regression/rw_file.c
- LibOS/shim/test/regression/rw_file.h
- LibOS/shim/test/regression/sealed_file.c
- LibOS/shim/test/regression/test_libos.py
- Pal/src/host/Linux-SGX/enclave_framework.c
- Pal/src/host/Linux-SGX/enclave_pf.c
- Pal/src/host/Linux-SGX/enclave_pf.h
- Pal/src/host/Linux-SGX/pal_linux.h
- Pal/src/host/Linux-SGX/protected-files/protected_files.h
- Pal/src/host/Linux-SGX/sgx_arch.h
Previously, only `sgx.protected_files` were available in the manifest. This kind of protected files needs a provisioned master (wrap) key. But sometimes it is enough to seal files on the same platform for later usage by the same enclave or by enclaves of the same signer: this is the SGX sealing feature.
This commit adds two more options to support SGX sealing: `sgx.protected_mrenclave_files` and `sgx.protected_mrsigner_files`.
Similarly to `sgx.protected_files`, these new options specify lists of files that are encrypted by the SGX key generated via SGX instruction `EGETKEY(SEAL_KEY)`, bound to the MRENCLAVE/MRSIGNER enclave measurement (so that only instances of the same enclave/only enclaves with the same signer may decrypt protected files).
References:
- …
> [Pal/Linux-SGX] Add `sgx.protected_mr{enclave,signer}_files` manifest options

- LibOS/shim/src/fs/chroot/fs.c
- Pal/src/host/Linux-SGX/db_devices.c
- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux/db_devices.c
- Pal/src/host/Linux/db_files.c
Signed-off-by: Sonali Saha <sonali.saha@intel.com>
Graphene created the file with default permissions (0755), but it reported different permissions 0700 as it includes only user permissions to the returned permissions. This fix includes group and other permissions to the file permissions returned.
Fixes gramineproject/graphene#2543
Create a file with mode set as 0777 the permissions of this newly generated file will be 0755. Use stat to report back the file permissions it should report 0755 instead of 0700.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/10)
> [LibOS] Report back the default permissions of a file consistently

- Documentation/building.rst
- Documentation/quickstart.rst
- meson.build
This change improves support for building on systems other than Ubuntu:
- Use `asm/sgx.h` (not `uapi/asm/sgx.h`). Previously, `uapi` was always appended to the provided include path, so it wasn't possible to configure Gramine when the userspace kernel headers were installed without `uapi` prefix.
- Try out the `/usr/include` path. Ubuntu doesn't install kernel headers there, but many other distributions (e.g. Fedora, CentOS) do.
- Clarify in the quick start guide that it is for Ubuntu, and add a hint in case of configuration problems.
Closes #120.
Try building on a system with 5.11+ kernel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/121)
> [Pal/Linux-SGX] Improve SGX driver header configuration

- CI-Examples/nginx/nginx.manifest.template
On some systems (namely CentOS/RHEL), the previous enclave size of 256MB was barely enough for Nginx worker processes. Intermittently, these worker processes failed with `Out-of-memory in library OS` error. Increasing the size to 512MB fixes this error.
Nginx CI test should still work. Also, CentOS and RHEL tests should now work all the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/125)
> [CI-Examples] Increase enclave size to 512MB for Nginx

- Documentation/attestation.rst
- Documentation/manifest-syntax.rst
- LibOS/shim/test/fs/manifest.template
- LibOS/shim/test/regression/manifest.template
- Pal/src/host/Linux-SGX/enclave_pf.c
It's clearly described as insecure and debug feature, but the name missed the usual prefix we give such options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/123)
> [Pal/Linux-SGX] Add "insecure__" prefix to "protected_files_key"

- Pal/src/host/Linux/db_main.c
Previously, if mapping ASAN shadow memory failed, process would just enter an infinite loop. This commit makes it exit the whole process instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/124)
> [Pal/Linux] Exit process in case of errors in `setup_asan`

- Documentation/manifest-syntax.rst
- LibOS/shim/src/bookkeep/shim_thread.c
- LibOS/shim/test/regression/.gitignore
- LibOS/shim/test/regression/Makefile
- LibOS/shim/test/regression/test_libos.py
- LibOS/shim/test/regression/uid_gid.c
- LibOS/shim/test/regression/uid_gid.manifest.template
This implementation enables Gramine to run an executable with another user than root.
This becomes very handy in case of executables, which shouldn't run with the root user.
The implementation of this feature sets also the effective uid/gid to the value,
which is defined in the manifest for the directive loader.uid/gid
This topic has been discussed in the issue [2632](https://github.com/gramineproject/graphene/issues/2632)
Signed-off-by: Denis Zygann <denis@zygann.de>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/37)
> [LibOS] Add UID and GID to manifest

- LibOS/shim/test/regression/file_check_policy_allow_all_but_log.manifest.template
- LibOS/shim/test/regression/file_check_policy_strict.manifest.template
- Pal/src/host/Linux-SGX/db_files.c
In some workloads (especially Python workloads that try to access .pyc files), there are tons of  "Disallowing access ..." and "Allowing access ..." messages. Previously, they were printed even at the "error" level. To decrease verbosity of the output, this commit forces these messages to be printed starting from the "warning" level.
Two LibOS tests now have `loader.log_level = "warning"` to verify this.
Also, manually check GSC's example of Python helloworld example: https://gramine-gsc.readthedocs.io/en/latest/#example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/144)
> [Pal/Linux-SGX] Change log level of "unknown files" message to "warning"

- Pal/src/host/Linux/db_exception.c
- Pal/src/host/Linux/db_main.c
- Pal/src/host/Linux/pal_linux.h
In some cases vDSO stubs may fallback to raw syscalls, which we now allow in our seccomp filter.
Fixes #176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/178)
> [Pal/Linux] Add vDSO as allowed range in seccomp policy

- Pal/include/pal_internal.h
- Pal/regression/Memory.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux/db_main.c
- Pal/src/slab.c
This change reduces the initial 64MB buffer to a much smaller size, and allocates 64MB of memory after PAL startup instead (by making that the default value for `loader.pal_internal_mem_size`).
While the memory still has to be explicitely zeroed, this makes calculating the enclave measurement much faster (`gramine-sgx-sign` on test binaries takes 50% less time, because we can omit hashing 64MB worth of zeroes.
CI should be enough, but keep in mind this is a breaking change if existing manifests define `loader.pal_internal_mem_size`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/192)
> [Pal] Reduce the 64MB static buffer

- .ci/linux-sgx-sanitizers.jenkinsfile
- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-secret-prov/Makefile
- LibOS/shim/src/shim_rtld.c
This adds `CI-Examples` to the SGX sanitizers configuration. ASan and UBSan found no bugs, but the remote attestation examples did not work when compiled with Clang (because it doesn't default to PIE).
Also, I fixed a stupid bug that causes Gramine to continue after failing to map such executables (instead of exiting with a helpful message, which we already have!)
CI should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/197)
> [CI] Test apps in the SGX sanitizers configuration

- LibOS/shim/test/regression/test_libos.py
`self.has_debug` -> `self.has_debug()`
This bug caused the ASan test to fail when running in release mode.
This is one of the issues described in #208.
* Build with ASan and release mode: `CC=clang CXX=clang++ AS=clang meson --buildtype=release -Ddirect=enabled -Dtests=enabled -Dasan=enabled`.
* Run the ASan test in `LibOS/shim/tests/regression`:
```
make run_test run_test.manifest
ASAN=1 ../../../../Scripts/run-pytest -k test_021_asan
```
It should fail on `master` and pass on this branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/212)
> [tests] Fix `has_debug()` invocation

- .ci/lib/stage-clean-check.jenkinsfile
- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- CI-Examples/helloworld/.gitignore
- CI-Examples/helloworld/Makefile
- CI-Examples/helloworld/README.md
- CI-Examples/helloworld/helloworld.c
- CI-Examples/helloworld/helloworld.manifest.template
- Documentation/cloud-deployment.rst
- Documentation/devel/debugging.rst
- Documentation/quickstart.rst
Gramine's "quick start" guides recommended running the `helloworld` regression test, but this now requires an extra flag for Meson (`-Dtests=enabled`) that we do not want to recommend to first-time users. Instead, there's a standalone `helloworld` example.
Discussed in #187.
Fixes #205.
Compile and run the example yourself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/188)
> [CI-Examples,Docs] Add `helloworld` example

- Pal/src/db_streams.c
- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/enclave_pages.c
- Pal/src/host/Linux-SGX/enclave_pages.h
Fixes the intermittent crashes after fork, introduced in #192. See commit message for more details.
Unfortunately LibOS allocation code still looks pretty brittle (we rely on the fact that in child process does roughly the same allocations as in parent, or at least less of them). But the crash should be gone now.
Fixes #215.
The problem can be seen on the `fork_and_exec` example. Normally it appears rarely, but you can adjust the memory parameters to force it:
1. `cd LibOS/shim/test/regression; make fork_and_exec.manifest`
2. Edit `fork_and_exec.manifest`: set `sgx.enclave_size = "128M"` and `loader.pal_internal_mem_size = "40M"`.
3. Rebuild: `SGX=1 make fork_and_exec.token` (you'll need to repeat this step after rebuilding Gramine)
4. Run in a loop, e.g.: `while gramine-sgx …
> [Pal/Linux-SGX] Fix user address range calculation

- Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c
- Pal/src/host/Linux-SGX/sgx_profile.c
Still emits a warning under 11.2.0, but I'm not sure how to fix it (looks like false positive?) and it's probably not urgent:
```
../Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c:584:20: error: ‘userdata’ may be used uninitialized [-Werror=maybe-uninitialized]
584 |             return *(long*)((void*)&userdata + (off_t)addr);
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/220)
> Fixes for problems found by GCC 11.2.0

- LibOS/shim/test/fs/test_pf.py
- Pal/regression/Memory.c
- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux-SGX/db_memory.c
- Pal/src/host/Linux-SGX/enclave_pages.c
- Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.h
- Pal/src/host/Linux-SGX/sgx_main.c
- common/include/asan.h
- common/src/asan.c
A few changes related to ASan. The "Fix shadow memory size" commit fixes one of the problems described in #208.
* This fixes `gramine-direct` hanging on some new Linux systems (I reproduced this on Linux 5.11, over at #208 people also reproduced it on 5.13) which like to map vvar/vdso above 0x800000000000 (I'm not sure why that happens, though).
* Accessing "invalid" enclave memory should now trigger ASan (which is why I had to disable it for some PAL tests).
* Overflowing the LibOS stack (you can try adding a big array in `shim_emulate_syscall`) also triggers ASan, because we hit the stack guard page.
However, the user experience is not very good, as ASan then gets triggered recursively when trying to format the report, and the actual report we see is for memory *below* the stack guard …
> ASan improvements

- CI-Examples/ra-tls-mbedtls/README.md
When compiling for running DCAP client in SGX, should make with options
as: make app dcap, previously one is not correct.
When running DCAP client in SGX, should add the arguments in cmd.
N/A: No functional change to the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/225)
> Fix argument for SGX client

- CONTRIBUTING.rst
- python/gramine-test
This updates the documentation, and also makes sure `gramine-test pytest -v` is more usable.
Fixes #226.
Check if the examples in `CONTRIBUTING.rst` work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/227)
> `gramine-test` fixes

- LibOS/shim/src/sys/shim_file.c
- Pal/src/host/Linux/db_events.c
- Pal/src/host/Linux/pal_host.h
I looked into why the `sendfile` LTP test is so slow, and found two things:
* the buffer size is pretty small,
* `DkEventSet` in Linux PAL is pretty inefficient and always calls `futex` (Linux-SGX PAL has a waiters count, so it should be OK)
As a result, there is a lot of small `pread64` and `pwrite64` calls, each accompanied by several `futex` calls (releasing locks).
Here's a benchmark for `sendfile09` LTP test (which uses `sendfile` to copy 1 GB ranges), with `gramine-direct`, compiled in debug mode (but release numbers are pretty similar):
| version | time |
|---|---|
| Linux (no Gramine) | 1.07 s |
| master |  2.61 s |
| `DkEventSet` optimized | 1.86 s |
| 64KB buffer | 1.31 s |
| **`DkEventSet` optimized + 64KB buffer** | **1.25 s** |
(Benchmarks performed using …
> Optimize `sendfile`

- LibOS/shim/src/sys/shim_dup.c
Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>
As per the man [page](https://man7.org/linux/man-pages/man2/dup.2.html), `dup2` must return `newfd` if `oldfd` and `newfd` have the same values.
Fixes #180 
LTP tests haven't been upgraded yet. Please follow the steps listed in #180.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/249)
> [LibOS] Fix dup2 and dup3 as per the spec

- LibOS/shim/test/regression/attestation.c
- Pal/src/host/Linux-SGX/sgx_attest.h
- Pal/src/host/Linux-SGX/sgx_platform.c
- Pal/src/host/Linux-SGX/tools/common/attestation.c
- Pal/src/host/Linux-SGX/tools/common/attestation.h
- Pal/src/host/Linux-SGX/tools/ias-request/ias_request.c
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls.h
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c
- Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c
SGX quote returned by IAS does not contain signature and signature length fields. This might result in a buffer overflow if we accidentally end up using these fields as part of the quote. To avoid such an issue, this commit splits sgx_quote structure into sgx_quote_body and signature.
Also, modified `attestation` LibOS regression to incorporate the new sgx_quote structural change.
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
Fixes #113 
Please run LibOS regression tests. One can also run the `ra-tls-mbedtls` test as part of our CI-Examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/219)
> [Pal/Linux-SGX] Restructure sgx_quote_t to split signature from body

- python/gramine-sgx-sign
This fixes the "dependency cycle" error that appears when building test manifests on Ubuntu 18.04 (Ninja 1.8.2).
Fixes #257.
See #257 for how to reproduce the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/260)
> [python] gramine-sgx-sign: fix incompatibility with old Ninja

- LibOS/shim/src/shim_rtld.c
- Pal/include/pal_rtld.h
- Pal/src/db_rtld.c
Previously, `l_addr`/`l_base` field names were used to denote the "difference between virtual addresses in ELF file and actual virtual addresses in memory". This commit renames them to `l_base_diff` which reflects the actual meaning better.
Link to ELF spec, see page 73: https://refspecs.linuxfoundation.org/elf/elf.pdf.
All tests must pass, no functional change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/255)
> [Pal,LibOS] rtld: Rename `l_addr`/`l_base` to `l_base_diff`

- Documentation/devel/coding-style.rst
- LibOS/shim/include/arch/x86_64/gramine_entry_api.h
- LibOS/shim/include/arch/x86_64/shim_internal-arch.h
- LibOS/shim/include/arch/x86_64/shim_syscalls.h
Apply clang-format rules to a few files, which should be uncontroversial.  This is mostly to "denoise" output while working on issues where we don't like what clang-format does, although I may have misjudged something (i.e., the review may still be useful to catch format changes that are unappealing).
Unless people object, I'll probably do a slow trickle of these sorts of PRs, or updates to this one.
I did manually disable formatting around some inline assembly, which I assume will be uncommon to need.
N/A: No functional change to the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/223)
> [Format] Apply clang-format to a few files

- LibOS/shim/include/shim_handle.h
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/shim_fs_pseudo.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/sys/shim_open.c
Instead of handle-specific "position" fields, use a common field for all filesystems. This allows removing some filesystem-specific parts of `shim_handle`, and can enable global (instead of filesystem-specific) handling of file position in the future.
(I'm hoping to convert read/write callbacks to stateless pread/pwrite, but even without that, it's a useful cleanup).
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/268)
> [LibOS] Introduce `shim_handle.pos`

- LibOS/shim/test/regression/host_root_fs.manifest.template
`host_root_fs` regression test mounts whole host root directory inside Gramine. Dynamic loaders ("ld.so") tend to cache locations of dynamic libraries and hold such caches in "/etc" directory, which could brake this test.
Fixes #271 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/271)
> [LibOS/regression] Disable mounting host "/etc" in `host_root_fs` test

- LibOS/shim/src/sys/shim_futex.c
- LibOS/shim/test/regression/futex_wake_op.c
Current code implements `ANDN` op as NAND operation but this op according to man pages should do a complement of `oparg` and then `bitwise and` with the value of `uaddr2`. This commit fixes the issue.
This commit also updates the `futex_wake_op` regression test for `FUTEX_OP_ANDN` and other operations as well.
Please run `futex_wake_op` LibOS regression test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/265)
> [LibOS] Fix FUTEX_WAKE_OP's implementation of `ANDN` operation

- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/tmpfs/fs.c
`st_dev` was calculated differently in `stat` (path stat) and `fstat` (fd stat).
Fixes #246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/273)
> [LibOS] Uniformly calculate `st_dev` in chroot stat functions

- Documentation/attestation.rst
- Documentation/manifest-syntax.rst
Two commits:
- [Docs] Improve explanation for `sgx.enclave_size` manifest option
From the previous explanation, it looked like it is enough to enable  EDMM feature only in hardware, and the behavior of Gramine would change automatically. In fact, the EDMM feature must be enabled in all components of the hardware/software stack (including Gramine).
Also, it was confusing to readers to jump straight to RAM, without a mention of SGX-specific EPC. This looked like EPC was some memory separate from RAM.
- [Docs] Fix broken links for Marblerun attestation
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/256)
> [Docs] Fix broken Marblerun links; improve `sgx.enclave_size` explanation

- LibOS/shim/test/regression/file_check_policy_allow_all_but_log.manifest.template
- Pal/src/db_rtld.c
In the [recent RTLD refactoring](https://github.com/gramineproject/gramine/pull/152), the LibOS binary was initially mapped into memory via `_DkStreamMap(..., /*prot=*/0, ...)`. This led to a corner case in the Linux-SGX PAL: if `sgx.file_check_policy = "allow_all_but_log"` was set in the manifest (or the LibOS binary was marked in `sgx.allowed_files`), the LibOS binary was considered an allowed file. And because protections were `0` (aka MAP_SHARED), Linux-SGX's `file_map()` callback decided to map the file in untrusted memory, which was incorrect and led to failures later.
This commit fixes this bug by specifying `PAL_PROT_WRITECOPY` -- this guarantees that the file will be mapped inside enclave memory.
Kudos to @aneessahib who reported this issue.
I modified one of the LibOS regression …
> [Pal] Always map LibOS binary inside enclave memory

- Pal/src/host/Linux-SGX/sgx_platform.c
When generating quotes in Gramine, a warning message "Malformed request received" will appear in AESM log.
This is because in retrieve_quote(), a new connection to AESM service is created but never used or closed. Removing this connection prevents AESM from printing the warning message.
Subsequent request_aesm_service() uses its own connection, therefore remains untouched.
Fixes gramineproject/graphene#2448
After applying this patch, generating quotes in Gramine will no longer generate warning messages in AESM log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/280)
> [Pal/Linux-SGX] Fix AESM warning 'Malformed request received'

- LibOS/shim/src/arch/x86_64/shim.lds
- LibOS/shim/test/regression/meson.build
- Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c
- common/include/asan.h
- meson.build
This fixes compilation and linker warnings for GCC, and incompatibility with newest Clang/LLVM. See the commits.
* Compile with GCC 11 / ld 2.37
* Compile with Clang 13 and `-Dasan=enabled` (note that for Clang you also need `-Dmusl=disabled`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/284)
> Ubuntu 21.10 fixes

- subprojects/glibc-2.34-1.wrap
- subprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5.wrap
- subprojects/uthash-2.1.0.wrap
Some package URLs still used the old `packages.grapheneproject.io`, which became unaccessible recently.
There are two packages not yet in `packages.grapheneproject.io`:
- TOML (version: commit `208203af46bdbdb29ba199660ed78d09c220b6c5`)
- Glibc (version: 2.34)
@woju or someone who has access to the web-site, please add these two packages.
Closes #290.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/293)
> [Meson] Fix package URLs to `packages.gramineproject.io`

- CI-Examples/bash/manifest.template
- CI-Examples/blender/blender.manifest.template
- CI-Examples/busybox/busybox.manifest.template
- CI-Examples/helloworld/helloworld.manifest.template
- CI-Examples/lighttpd/lighttpd.manifest.template
- CI-Examples/memcached/memcached.manifest.template
- CI-Examples/nginx/nginx.manifest.template
- CI-Examples/python/python.manifest.template
- CI-Examples/ra-tls-mbedtls/client.manifest.template
- CI-Examples/ra-tls-mbedtls/server.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template
- CI-Examples/redis/redis-server.manifest.template
- CI-Examples/sqlite/manifest.template
This is for backwards compatibility with Gramine v1.0. We currently have Gramine v1.0 installation package, and our QuickStart doc installs this version but runs the latest `CI-Examples/helloworld` sample app.
Commit "Update examples to use `loader.entrypoint` instead of `loader.preload`" removed the `loader.preload` manifest option from all examples' manifests. However, Gramine v1.0 doesn't recognize the new `loader.entrypoint` option and thus fails. This commit fixes that.
See #237 for context.
CI must succeed. No functional change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/287)
> [CI-Examples] Update examples to also use `loader.preload`

- LibOS/shim/src/vdso/arch/x86_64/meson.build
- Pal/gdb_integration/debug_map_gdb.py
This change stops GDB from trying to load vDSO as regular files, and instead loads them from process memory. As a result, GDB backtrace is fixed for stacks involving vDSO (e.g. `shim_do_gettimeofday`).
The GDB warnings (`file not found: .../[vdso_libos]`) should be gone.
There should be a proper backtrace for `shim_do_gettimeofday`:
```
LibOS/shim/test/regression $ GDB=1 gramine-direct gettimeofday
(gdb) break shim_do_gettimeofday
(gdb) run
...
(gdb) bt
#0  shim_do_gettimeofday (tv=0x7ffff3f692b8 <read_exact>, tz=0x0) at ../LibOS/shim/src/sys/shim_time.c:17
#1  0x00007ffff3f691b8 in shim_emulate_syscall (context=0x7ffff3efef38) at ../LibOS/shim/src/shim_syscalls.c:41
#2  0x00007ffff3f8a3ff in syscalldb () at ../LibOS/shim/src/arch/x86_64/syscallas.S:173
#3  0x00007ffff3f8a402 in …
```
> [LibOS] Improve GDB treatment of vDSO

- Documentation/manifest-syntax.rst
- LibOS/shim/test/regression/attestation.manifest.template
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/enclave_framework.c
- Pal/src/host/Linux-SGX/enclave_tf.h
This PR adds three new manifest options:
- `sgx.seal_key.flags_mask` for KEYREQUEST.ATTRIBUTESMASK.FLAGS
- `sgx.seal_key.xfrm_mask` for KEYREQUEST.ATTRIBUTESMASK.XFRM
- `sgx.seal_key.misc_mask` for KEYREQUEST.MISCMASK
These new manifest options allow the user to control how the SGX sealing key is generated. This flexibility is especially important for cases where files are sealed with one version of Gramine and unsealed with another version of Gramine (differing in default attribute masks).
For a very detailed explanation of this subtle issue, please check https://github.com/gramineproject/gramine/issues/274.
Fixes #274.
See #274. But here is a snippet that proves this PR works:
```
$ echo 'sgx.seal_key.xfrm_mask = "ffffffffffffff1b"' >> manifest.template
$ SGX=1 gramine-test build
$ …
```
> [Pal/Linux-SGX] Allow different masks for SGX sealing key derivation

- LibOS/shim/include/shim_fs.h
- LibOS/shim/src/bookkeep/shim_handle.c
- LibOS/shim/src/bookkeep/shim_process.c
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/pipe/fs.c
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/fs/shim_fs_lock.c
- LibOS/shim/src/fs/shim_fs_pseudo.c
- LibOS/shim/src/fs/shim_namei.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/shim_rtld.c
- LibOS/shim/src/sys/shim_access.c
- LibOS/shim/src/sys/shim_file.c
- LibOS/shim/src/sys/shim_getcwd.c
- LibOS/shim/src/sys/shim_open.c
- LibOS/shim/src/sys/shim_pipe.c
- LibOS/shim/src/sys/shim_socket.c
- LibOS/shim/src/sys/shim_stat.c
- Pal/src/host/Linux-SGX/db_devices.c
- Pal/src/host/Linux/db_devices.c
This commit makes holding `g_dcache_lock` mandatory when calling `path_lookupat`, `dentry_open` and dentry callbacks (`shim_d_ops`). The callbacks are now also better documented.
This is in preparation for removing the per-object dentry lock (`shim_dentry.lock`), and later, switching to inodes. It should also make the filesystem functions less prone to race conditions.
Context: #279 (inodes migration). Should also help with https://github.com/gramineproject/graphene/issues/944 (but since I touch only some of the filesystem code, I won't claim it's fixed yet).
I spent some time making sure the callbacks are called according to documentation; I would be grateful for a double-check.
--- …
> Take `g_dcache_lock` in dentry-related functions

- LibOS/shim/include/shim_fs.h
- LibOS/shim/src/fs/shim_fs_lock.c
Instead of using `shim_dentry.lock` for data stores in individual dentries, we use a global local (`g_fs_lock_lock`) for all fs_lock
related operations. This is in preparation for removing `shim_dentry.lock`.
Context: #279.
I realize that using a lock for guarding a field on another object (`shim_dentry`) doesn't look nice. However, I tried the alternative (taking the global lock for dentries, `g_dcache_lock`) and it breaks because of the spaghetti in filesystem code[1]. While I could probably work around this specific issue, I think it's better to keep this module separate (i.e. using its own lock) so that it's easier to reason about.
[1] If you want to know the gory details, it was `shim_pipe`: because it uses extra file descriptor, the callback for `open` actually "closes" one of these …
> [LibOS] fs_lock: Use a separate lock for all operations

- Pal/src/host/Linux-SGX/enclave_entry.S
This PR adds more explanatory comments and mends them to be more uniform across the file. All lines are re-wrapped to 100 char limit. All labels have better names; in particular, labels start with prefix `cssa0_` or `cssa1_` to indicate whether asm code is executed in SSA[0] (regular and stage-2 exception handler flows) or in SSA[1] (stage-1 exception handler flows). Finally, `ignore_exception` label was redundant and therefore removed.
N/A. No changes in the code itself, only comments and label names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/291)
> [Pal/Linux-SGX] Improve readability of enclave_entry.S

- Pal/regression/Socket.c
- Pal/regression/test_pal.py
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux/db_sockets.c
PAL's DkStreamGetName operation incorrectly serialized IPv6 addresses, flipping the bytes on little-endian architectures. This caused MySQL to reject incoming connections (because e.g. a connection from 127.0.0.1 was reported by Gramine as coming from 0.127.1.0).
Fixes #246.
* MySQL 5.7 should work, as described in #246. Unfortunately we don't have an example project for MySQL, and MySQL version 8 (available in Ubuntu repositories) does not work yet (it crashes on an assertion, I haven't investigated deeply).
* I modified the `Socket` PAL regression test to reproduce the scenario happening in MySQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/299)
> [Pal/{Linux,Linux-SGX}] Fix IPv6 address serialization

- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux-SGX/enclave_framework.c
See #302 for details.
Fixes #302.
All tests must succeed. Try manually to create `trusted_testfile` with some random text and run the LibOS regression test:
```
gramine/LibOS/shim/test/regression$ gramine-sgx file_check_policy_strict read trusted_testfile
warning: Hash of trusted file 'trusted_testfile' does not match with the reference hash in manifest
fopen failed: Permission denied
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/304)
> [Pal/Linux-SGX] Better warning message when loading trusted file fails

- LibOS/shim/src/sys/shim_file.c
Fixes a bug introduced in #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/307)
> [LibOS] Add missing unlock on error return path in `shim_do_rmdir`

- LibOS/shim/src/bookkeep/shim_signal.c
It is possible that an async signal occurs during LibOS thread initialization and is forwarded by PAL to `quit_upcall()` / `interrupted_upcall()`. At this point, `get_cur_thread() == NULL` and `is_internal()` helper function segfaults on `thread->tid`. This commit fixes this bug.
Note that we don't implement a similar change for *synchronous signals* because it is assumed that sync signals can never happen during LibOS code.
This bug was found while I was experimenting with something different on Gramine. That workload increased the frequency of async signals; some of these signals got delivered while in LibOS thread initialization. This manifested itself as a MEMFAULT in Gramine PAL terminology, and led to an infinite loop of such MEMFAULTs.
On my extreme workload, this bug happened …
> [LibOS] Fix segfault during async-signal upcalls

- Documentation/pal/host-abi.rst
- LibOS/shim/src/fs/proc/info.c
- LibOS/shim/src/sys/shim_getrlimit.c
- Pal/include/pal/pal.h
- Pal/regression/Memory.c
- Pal/src/db_main.c
Split out from #314 (removing superfluous `PAL_MEM_INFO` struct).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/318)
> [Pal] Remove superfluous PAL_MEM_INFO struct

- LibOS/shim/src/sys/shim_mmap.c
- LibOS/shim/src/sys/shim_sleep.c
- LibOS/shim/src/sys/shim_time.c
See #327 for details.
Fixes #327.
This doesn't merit its own test, but one can locally test like I did. Change `CI-Examples/helloworld` like this:
```diff
diff --git a/CI-Examples/helloworld/helloworld.c b/CI-Examples/helloworld/helloworld.c
@@ -1,6 +1,15 @@
#include <stdio.h>
+#include <time.h>
int main(void) {
+    struct timespec tp;
+    fprintf(stderr, "1\n");
+    clock_gettime(CLOCK_REALTIME, &tp);
+    fprintf(stderr, "2\n");
+    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &tp);
+    fprintf(stderr, "3\n");
+    clock_gettime(CLOCK_THREAD_CPUTIME_ID, &tp);
+    fprintf(stderr, "4\n");
printf("Hello, world\n");
return 0;
}
```
Then build with `make DEBUG=1` and run with `gramine-direct helloworld`:
```
1
2
[P1:T1:helloworld] warning: Per-process and per-thread CPU-time clocks are not …
```
> [LibOS] Add warnings for unsupported `CLOCK_{PROCESS,THREAD}_CPUTIME_ID`

- Pal/src/host/Linux-SGX/db_devices.c
- Pal/src/host/Linux/db_devices.c
- Pal/src/host/Skeleton/db_devices.c
Write to `/proc/self/fd/2` (which is symlink to /dev/tty) fails with `O_TRUNC` flag which translates to `DkStreamSetLength` as `setlength` function is not implemented for dev:tty devices.
This PR adds dummy function `setlength` to support O_TRUNC flag.
Fixes #303 
Should be able to execute below commands successfully:
```
gramine-direct busybox sh -c 'echo foo>/proc/self/fd/2'
gramine-sgx busybox sh -c 'echo foo>/proc/self/fd/2'
```
as described in link  https://github.com/gramineproject/gramine/issues/303#issuecomment-1002591818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/332)
> [Pal] Support opening TTY devices with O_TRUNC flag

- Pal/src/host/Linux-SGX/protected-files/protected_files.c
- Pal/src/host/Linux-SGX/tools/common/pf_util.c
Previously the debug log looked like this:
```
debug: load_protected_file: sealed_file_mrenclave.dat, fd 16, size 0, mode 2, create 1, pf 0xf402a30
debug: load_protected_file: sealed_file_mrenclave.dat, fd 16: opening new PF 0xf402a30
debug: ipf_open: handle: 16, path: 'sealed_file_mrenclave.dat', real size: 0, mode: 0x2
debug: ipf_open: OK (data size 0)
CREATION OK
```
Now the redundant newlines are removed.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/347)
> [Pal/Linux-SGX] Remove redundant newlines in messages in PFs

- LibOS/shim/test/regression/meson.build
- LibOS/shim/test/regression/mmap_file_backed.c
- LibOS/shim/test/regression/test_libos.py
- LibOS/shim/test/regression/tests.toml
- LibOS/shim/test/regression/tests_musl.toml
- Pal/src/host/Linux-SGX/db_files.c
There was a bug in Gramine-SGX implementation of trusted files: invocation of `mmap(..., <trusted-file-fd>, <offset-past-file-end>)` crashed Gramine process. Such an invocation can happen during checkpoint restore in the child process. This PR fixes this bug by initializing (zeroing) the memory region on such mmap and simply returning success.
For my previous failed attempt to fix this bug, see #328 and #336 and #338.
This bug was found on Python's qiskit package (it led to a segfault on SGX PAL).
This PR adds new LibOS regression test to catch this bug. The test also checks protected-files logic: it was not affected by this bug but we still add such check for future-proofing.
Also see descriptions in #328.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [Pal/Linux-SGX] Init memory region on mmap past trusted-file end

- Documentation/attestation.rst
- LibOS/shim/src/fs/dev/attestation.c
Previously, our documentation on attestation only mentioned two attestation-related pseudo-files: `user_report_data` and `quote` (these are the only files needed to implement SGX remote attestation).
This PR adds descriptions of the rest files: `target_info`, `my_target_info` and `report` (these files are used in SGX local attestation). Also, some incorrect statements are fixed.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/333)
> [Docs] Describe all `/dev/attestation/` pseudo-files

- LibOS/shim/src/bookkeep/shim_vma.c
- LibOS/shim/test/ltp/ltp.cfg
Previously, Gramine sent the contents a tainted shared file-backed memory region in a checkpoint blob (in a `shim_mem_entry` object). This resulted in this memory region being allocated as anonymous via `DkVirtualMemoryAlloc()` in the child process, so the updates on this memory region were not reflected in parent/child.
Fixing this bug allows to remove the workaround for BROK LTP tests. This is because LTP reports results of the child via the file `/dev/shm` mapped as `MAP_SHARED`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/349)
> [LibOS] Re-map tainted shared file-backed memory regions on fork

- LibOS/shim/include/shim_internal.h
- LibOS/shim/include/shim_signal.h
- LibOS/shim/include/shim_table.h
- LibOS/shim/include/shim_thread.h
- LibOS/shim/src/bookkeep/shim_signal.c
- LibOS/shim/src/bookkeep/shim_thread.c
- LibOS/shim/src/shim_syscalls.c
- LibOS/shim/src/sys/shim_poll.c
- LibOS/shim/src/sys/shim_sigaction.c
This is used by e.g. `sigsuspend`, `pselect` and `ppoll`. Note that `epoll_pwait` is not changed, since it will be reworked in a follow up PR.
Fixes https://github.com/gramineproject/graphene/issues/789
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/354)
> [LibOS] Add support for temporary changing of signal mask by syscalls

- Pal/src/host/Linux-SGX/db_files.c
Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>
Disallowing renaming operation on protected files to avoid issues like #345
Fixes #345 (temporarily)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/352)
> [Pal/Linux-SGX] Disallow rename operation on protected files

- LibOS/shim/src/fs/sys/fs.c
- LibOS/shim/test/regression/test_libos.py
- Pal/include/pal_internal.h
- Pal/src/db_main.c
- Pal/src/host/Linux-SGX/db_misc.c
- Pal/src/host/Linux/arch/x86_64/db_arch_misc.c
- Pal/src/host/Linux/db_main.c
- Pal/src/host/Skeleton/db_main.c
This PR cleans up a few of the TODOs as part of refactoring sysfs.
Please run `sysfs_common` and `proc_common` regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/360)
> Refactor sysfs to improve sanitization - Part 3

- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/src/fs/proc/fs.c
- LibOS/shim/src/fs/proc/info.c
- LibOS/shim/test/regression/meson.build
- LibOS/shim/test/regression/proc_stat.c
- LibOS/shim/test/regression/test_libos.py
- LibOS/shim/test/regression/tests.toml
- LibOS/shim/test/regression/tests_musl.toml
We implement a minimal set of dummy values in these two procfs pseudo-files to satisfy workloads like Python's psutil library.
~~This PR is based on #328 (because I was testing the `qiskit` package in Python).~~ UPDATE: I rebased to remove that commit.
Fixes #329.
A new LibOS regression test is added to test `/proc/stat`.
Also see #328 description of Python `qiskit` package for manual testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/330)
> [LibOS] Add dummy entries in `/proc/stat` and `/proc/meminfo`

- LibOS/shim/src/sys/shim_stat.c
- LibOS/shim/test/ltp/ltp.cfg
LTP fstat03 tests `shim_do_fstat` sys call and reports `internal memory fault` for the second test where `stat_buf` is NULL which should return `EFAULT` but test fails as `memset` tries to set NULL buffer. `shim_do_fstat` call does not sanitize the `stat_buf` before using it.
Code changes in this PR sanitizes the inputs to `shim_do_fstat` syscall before using them.
Fixes #356 
execute LTP test `fstat03` with command: `gramine-direct fstat03`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/362)
> [LibOS] Verify buffer argument of the `fstat` syscall

- LibOS/shim/src/bookkeep/shim_thread.c
- LibOS/shim/src/ipc/shim_ipc_worker.c
- Pal/src/host/Linux-SGX/db_pipes.c
- Pal/src/host/Linux-SGX/pal_host.h
Linux-SGX PAL performs a TLS handshake when creating a PAL pipe. For this, the PAL creates a helper thread but its resources were never cleared previously. This lead to memory leaks each time a PAL pipe was created (e.g., for IPC communication and pollable events).
Fixes #365. Fixes https://github.com/gramineproject/graphene/issues/2467.
All tests must pass. You can manually test it by adding log messages and running e.g. `pipe` LibOS regression test (that's what I did to verify this patch).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/366)
> [Pal/Linux-SGX] Garbage collect helper pipe-handshake threads

- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/src/fs/proc/info.c
- LibOS/shim/src/fs/sys/cache_info.c
- LibOS/shim/src/fs/sys/cpu_info.c
- LibOS/shim/src/fs/sys/fs.c
- LibOS/shim/src/fs/sys/node_info.c
- LibOS/shim/src/sys/shim_sched.c
- Pal/include/arch/x86_64/pal_topology.h
- Pal/include/host/Linux-common/topo_info.h
- Pal/regression/Bootstrap.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/enclave_ocalls.c
- Pal/src/host/Linux-common/topo_info.c
- common/include/api.h
This PR refactors sysfs to improve sanitization. It fixes issues 1, 2 listed as part of gramineproject/graphene#2105.
This supersedes PR #106 and I have closed the PR.
Please run `sysfs_common` and `proc_common` regression tests. Also, `openvino` benchmark using the TBB library can be used to validate the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/355)
> Refactor sysfs to improve sanitization

- Pal/src/host/Linux/db_exception.c
On x64 Linux VDSO is randomized even if ASLR is disabled, but this bug manifests only on systems with 5-level paging. This commit adds a workaround for that bug.
Fixes #369
Manually run Gramine with Linux PAL on system with 5-level paging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/368)
> [Pal/Linux] Add a workaround for a kernel bug randomizing VDSO

- LibOS/shim/src/shim_malloc.c
- Pal/include/pal_internal.h
- Pal/src/slab.c
- subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
Two related things:
- Fixes a bug in PAL's calloc() (missing overflow check, most likely a security issue).
- Changes LibOS's calloc() to use overflow builtins for better performance (no division needed; we use GCC/clang builtins everywhere anyways).
Read the code carefully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/370)
> [Pal/LibOS] Fix overflow checks in calloc()

- meson.build
Have "UNRELEASED" in meson.build's version so that anyone who builds from tarballs from a version between releases won't have an apparently released version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/379)
> Bump version in meson.build post 1.1

- CI-Examples/ra-tls-mbedtls/server.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template
- common/src/string/toml_utils.c
It was already long-deprecated, time to remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/375)
> Drop support for using 0/1 for bools in manifests

- CI-Examples/README.md
- CI-Examples/ra-tls-mbedtls/Makefile
- Documentation/manifest-syntax.rst
- Documentation/manpages/gramine-manifest.rst
- Documentation/tutorials/pytorch/index.rst
- LibOS/shim/test/regression/env_from_file.manifest.template
- Pal/src/host/Linux-SGX/enclave_framework.c
- Pal/src/host/Linux-SGX/tools/pf_crypt/pf_crypt.c
- python/graminelibos/manifest.py
We've been printing a warning about this for half a year and two releases (1.0 and 1.1) now, time to get rid of it.
And also we can finally fix the checksum vs hash confusion in our codebase.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/374)
> Drop support for dictionary syntax for files in manifest

- Documentation/quickstart.rst
Command for Prepare signing key in Quick Start Guide assumes we already have a gramine directory inside `"$HOME"/.config/` without which it throws a `No such file or directory` error. This commit adds the command to create that `gramine` dir.
Link to Quick Start Guide: https://gramine.readthedocs.io/en/latest/quickstart.html#prepare-a-signing-key
Fixes: #377 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/378)
> [Docs] Fix an error in "Prepare a signing key section" in Quick Start Guide

- .github/ISSUE_TEMPLATE.md
Although we had a note in the comment, nobody really gave the hash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/380)
> Update Github issues template to require Gramine commit hash

- LibOS/shim/include/shim_fs.h
- LibOS/shim/include/shim_handle.h
- LibOS/shim/src/bookkeep/shim_handle.c
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/shim_dcache.c
- LibOS/shim/src/fs/shim_fs_util.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/sys/shim_clone.c
- LibOS/shim/test/regression/test_libos.py
Next step in inodes conversion (#279). Based on open PR #282.
- Use `g_dcache_lock` for the dentry inode field
- Take `g_dcache_lock` for the whole checkpointing process
- Convert `tmpfs` to use inodes (fixes unlinking, renaming, and corner cases when migrating handles)
- Support `inode->data` (with deallocation and migration)
- Factor out some generic callbacks (seek, stat, hstat, poll)
CI should be enough. Some tests are now enabled for tmpfs (`send_handle`, `rename_unlink`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/297)
> Convert `tmpfs` to use inodes

- LibOS/shim/src/ipc/shim_ipc.c
- LibOS/shim/src/ipc/shim_ipc_worker.c
- LibOS/shim/src/shim_pollable_event.c
- LibOS/shim/src/sys/shim_pipe.c
It also missed PAL to UNIX errno translations.
Fixes #376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/381)
> [LibOS] Add interrupt handling around `DkStreamWaitForClient`

- subprojects/packagefiles/mbedtls/compile-gramine.sh
- subprojects/packagefiles/mbedtls/gramine.patch
- subprojects/packagefiles/mbedtls/include/mbedtls/config-gramine.h
- subprojects/packagefiles/mbedtls/meson.build
This ensures that userspace programs using the mbedtls library (e.g. `gramine-sgx-pf-crypt`) use the same configuration flags as the the mbedtls library itself.
The problem was that the Meson build applied a patch to a copy of `mbedtls/config.h`, but the programs included the unpatched version. As a result, the both sides disagreed about size of some data structures, causing `gramine-sgx-pf-crypt` to crash (when compiled with Clang in release mode).
This is one of the issues reported in #208 (https://github.com/gramineproject/gramine/issues/208#issuecomment-1032270427). If you compile Gramine with Clang in release or debugoptimized mode, the FS tests will fail:
```
$ SGX=1 gramine-test pytest test_pf.py
...
E   subprocess.CalledProcessError: Command '['gramine-sgx-pf-crypt', 'decrypt', …
```
> [common] Fix mbedtls configuration mismatch

- .dir-locals.el
- LibOS/shim/src/vdso/vdso-data.S
- LibOS/shim/src/vdso/vdso-note.S
- Pal/regression/crt_init/arch/x86_64/user_start.S
- Pal/src/host/Linux-SGX/enclave_entry.S
- Pal/src/host/Linux-SGX/sgx_entry.S
Older assembly files in Gramine were written using tabs, and [our Emacs config reflects this](https://github.com/gramineproject/graphene/commit/713863b5214512ec0daf4e3b53fe6b5ff32f3c41), but we prefer spaces now. Right now, there are 5 assembly files indented with spaces and 5 files indented with tabs. There are also already two cases of mixing tabs and spaces (in `enclave_entry.S` and `sgx_entry.S`).
I want to convert all "legacy" files to spaces so that they're easier to work with. I used Emacs' `untabify` function to automate the conversion.
This PR also updates the default config.
`git grep $'\t' '*.S'` should be empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gr …
> Convert assembly files to spaces

- LibOS/shim/include/shim_fs.h
- LibOS/shim/include/shim_handle.h
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/shim_dcache.c
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/fs/shim_fs_synthetic.c
- LibOS/shim/src/fs/shim_fs_util.c
- LibOS/shim/src/fs/shim_namei.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/meson.build
- LibOS/shim/src/sys/shim_file.c
- LibOS/shim/test/regression/meson.build
- LibOS/shim/test/regression/synthetic.c
- LibOS/shim/test/regression/tests.toml
- LibOS/shim/test/regression/tests_musl.toml
Previously, synthetic files were created as special dentries with DENTRY_SYNTHETIC flag set. These dentries were marked as belonging to a filesystem (typically "chroot") but weren't really initialized by it. As a result, they could break assumptions made by that filesystem (e.g. about `dent->inode` existing).
This change treats synthetic files same as other special files (named pipes and sockets). We set `dent->fs` to mark them as belonging to a separate filesystem, and all operations for the file are forwarded to that filesystem.
In addition, for simplicity we only create synthetic directories. If the user mounts something else than a directory, the synthetic mountpoint can still be a directory: it will be shadowed by the mounted file anyway.
There's a new regression test, `synthetic`, …
> [LibOS] Replace DENTRY_SYNTHETIC with a separate filesystem

- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/src/fs/shim_fs_pseudo.c
In addition, `pseudo_node` objects are now tracked by number and checkpointed.
This should have a pretty good coverage on Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/402)
> [LibOS] Convert `pseudo` filesystem to use inodes

- LibOS/shim/src/shim_call.c
Previously, `clang -O3` optimized the `asan_stack` and `asan_global` tests to a no-op.
This is reported in #208 (hopefully the last failure from that issue).
Compile Gramine with `--buildtype=debugoptimized` or `--buildtype=release` and ASan enabled.
The following tests do not trigger ASan on master, and should do so now:
```
regression $ gramine-test run run_test asan_stack
regression $ gramine-test run run_test asan_global
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/410)
> [LibOS] Make sure ASan tests work in optimized builds

- .ci/lib/config.jenkinsfile
- .ci/lib/stage-build-nosgx.jenkinsfile
- .ci/lib/stage-build-sgx.jenkinsfile
- CONTRIBUTING.rst
- Documentation/devel/building.rst
- Documentation/devel/debugging.rst
- meson.build
Compiler warnings are not stable and sometimes based on heuristics, so we shouldn't fail the build on warnings by default (this can easily cause Gramine to be unbuildable on new compilers/distros due to trivial or non-issues, see e.g. https://github.com/gramineproject/gramine/pull/220).
Build with and without passing `--werror` to `meson setup`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/409)
> [Meson] Build without werror by default

- LibOS/shim/src/sys/shim_socket.c
When returning from accept() or accept4(), the address should come from the accepted socket, not the listening socket.
Fixes #344 
The argument addr should now be filled with the peer address on return.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/412)
> [LibOS] Properly return peer address for accept() and accept4()

- Documentation/manifest-syntax.rst
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/test/regression/manifest.template
This converts the `fs.mount` manifest key to an array instead of table. Similar to `sgx.{trusted,allowed,protected}_files`, an array can be parsed more efficiently. It's also more natural, because order matters when specifying mount points.
The old (table) syntax is still accepted, but triggers a deprecation warning.
This commit converts the main manifest for regression tests. Other manifests will be converted later.
In addition, Gramine now allows omitting the `type` key (with "chroot" as default) and the `uri` key (so that it's easier to use the `tmpfs` filesystem).
Issue: #23 (although we might want to close it after the deprecated syntax is gone).
Prerequisite for #371: new syntax for trusted/protected files.
The `manifest.template` in LibOS regression tests should exercise the new …
> [LibOS] Convert `fs.mount` to an array

- LibOS/shim/include/shim_fs.h
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/pipe/fs.c
- LibOS/shim/src/fs/shim_dcache.c
- LibOS/shim/src/fs/shim_namei.c
- LibOS/shim/src/fs/socket/fs.c
- LibOS/shim/src/sys/shim_pipe.c
- LibOS/shim/src/sys/shim_socket.c
This PR converts the remaining filesystems to inodes. I finally got rid of the ugly stash-FDs-in-pointer hack. In fact, we're already able to remove `data` and `lock` fields from dentry.
The next step will be to drastically simplify the dentry object, and replace most uses with inode.
Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/414)
> Convert `fifo` and `socket` filesystems to use inodes 

- LibOS/shim/src/sys/shim_socket.c
- LibOS/shim/test/regression/tcp_ipv6_v6only.c
- Pal/include/pal/pal.h
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux-SGX/linux_types.h
- Pal/src/host/Linux-SGX/pal_host.h
- Pal/src/host/Linux/db_sockets.c
- Pal/src/host/Linux/pal_host.h
`setsockopt` syscall fails with socket options `SO_RCVTIMEO` and `SO_SNDTIMEO`. Argument for socket options `SO_RCVTIMEO` and `SO_SNDTIMEO` is a `struct timeval` but `int` type was used which causes the `setsockopt` syscall failure.
Changing the argument type to `struct timeval` from `int` with these socket options fixes the issue.
Fixes #341
Added regression test in `gramine/LibOS/shim/test/regression/tcp_ipv6_v6only.c`
execute the test `tcp_ipv6_v6only` to verify the fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/415)
> [LibOS/Pal] pass timeout value with correct type `struct timeval` to `setsockopt` syscall

- CI-Examples/bash/manifest.template
- CI-Examples/blender/blender.manifest.template
- CI-Examples/busybox/busybox.manifest.template
- CI-Examples/helloworld/helloworld.manifest.template
- CI-Examples/lighttpd/lighttpd.manifest.template
- CI-Examples/memcached/memcached.manifest.template
- CI-Examples/nginx/nginx.manifest.template
- CI-Examples/python/python.manifest.template
- CI-Examples/ra-tls-mbedtls/client.manifest.template
- CI-Examples/ra-tls-mbedtls/server.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template
- CI-Examples/redis/redis-server.manifest.template
- CI-Examples/sqlite/manifest.template
- Documentation/manifest-syntax.rst
- LibOS/shim/src/bookkeep/shim_handle.c
- Pal/src/db_main.c
- python/graminelibos/manifest.py
Both were long deprecated, time to get rid of them for the next release.
Corresponding examples PR: https://github.com/gramineproject/examples/pull/16.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/404)
> Drop support for `loader.preload` and URIs in `libos.entrypoint` in manifests

- Pal/src/host/Linux-SGX/db_exception.c
Using raw syscall instructions is very slow on SGX PAL, so warn users about it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/434)
> [Pal/Linux-SGX] Warn about raw syscall usage

- Documentation/devel/howto-doc.rst
- LibOS/shim/include/shim_checkpoint.h
- LibOS/shim/include/shim_fs.h
- Pal/src/host/Linux-SGX/enclave_ocalls.c
- common/include/api.h
- common/include/spinlock.h
- common/include/toml_utils.h
- common/src/printf.c
Please check if it looks good, if so then I'll update the rest of the docs (probably in parts).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/420)
> [Docs] Improve and unify Doxygen comments, part 1

- LibOS/shim/include/shim_fs.h
- LibOS/shim/src/bookkeep/shim_handle.c
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/pipe/fs.c
- LibOS/shim/src/fs/shim_dcache.c
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/fs/shim_fs_pseudo.c
- LibOS/shim/src/fs/shim_fs_synthetic.c
- LibOS/shim/src/fs/shim_fs_util.c
- LibOS/shim/src/fs/shim_namei.c
- LibOS/shim/src/fs/socket/fs.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/sys/shim_file.c
- LibOS/shim/src/sys/shim_getcwd.c
- LibOS/shim/src/sys/shim_open.c
- LibOS/shim/src/sys/shim_pipe.c
- LibOS/shim/src/sys/shim_socket.c
- LibOS/shim/src/sys/shim_stat.c
This change removes the `state` dentry field, and uses the `inode` field directly: a dentry is either positive (with inode) or negative (without inode). Dentry fields describing the file (`type`, `perm`) are also gone.
As a consequence, negative lookups are no longer cached: a negative dentry only means that a file is not known to exist.
Jenkins should be enough.
Cleanup: using inode as a parameter should simplify the implementation of individual filesystems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/428)
> [LibOS] Move fully to inodes

- Pal/src/host/Linux-SGX/sgx_main.c
Signed-off-by: Ying Liu <ying2.liu@intel.com>
parse_loader_config and add_pages_to_enclave might take some time during enclave initialization, so warn users about it.
Add messages to warn users that parse_loader_config and add_pages_to_enclave  might be slow.
Fixes #46 
Any test case in gramine source tree could be used to test this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/435)
> [Pal/Linux-SGX] Warn users that parse_loader_config and add_pages_to_enclave might be slow.

- Pal/src/host/Linux-SGX/enclave_framework.c
- common/include/api.h
There are no security bugs related to this right now, but looks like something which may end up used for untrusted size calculations someday.
https://godbolt.org/z/e96rW16G4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/440)
> [common] Make `DIV_ROUND_UP()` overflow-safe

- LibOS/shim/test/regression/exec_invalid_args.c
Previously, this test used the Glibc wrapper `execve()`, which led to the error "execve reading 8 bytes from a region of size 0" in newer GCC.
This was detected on a machine with Ubuntu 21.10 and 5.16.10 kernel and Glibc 2.34 (and some new GCC version). Meson was configured with `--werror`. The errors were like this:
```
../LibOS/shim/test/regression/exec_invalid_args.c:21:9: error: ‘execve’ reading 8 bytes from a region of size 0 [-Werror=stringop-overread]
21 |     r = execve(argv[0], badptr_argv, good_envp);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../LibOS/shim/test/regression/exec_invalid_args.c:21:9: note: referencing argument 2 of type ‘char * const*’
In file included from ../LibOS/shim/test/regression/exec_invalid_args.c:4:
/usr/include/unistd.h:572:12: note: in a call to …
```
> [LibOS/regression] Use `syscall()` in `exec_invalid_args` test

- LibOS/shim/include/shim_fs.h
- LibOS/shim/include/shim_handle.h
- LibOS/shim/src/bookkeep/shim_handle.c
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/eventfd/fs.c
- LibOS/shim/src/fs/pipe/fs.c
- LibOS/shim/src/fs/shim_fs_pseudo.c
- LibOS/shim/src/fs/shim_fs_util.c
- LibOS/shim/src/fs/socket/fs.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/shim_rtld.c
- LibOS/shim/src/sys/shim_file.c
- LibOS/shim/src/sys/shim_open.c
- LibOS/shim/src/sys/shim_wrappers.c
- LibOS/shim/test/ltp/ltp.cfg
Instead of using the handle position, `read` and `write` receive file position as a parameter (and might choose to update it). This is a similar design to Linux internals.
As a result, there's no need to emulate operations like `pread` using `seek`, and filesystem callbacks can be simpler.
This is in preparation for adding another filesystem (for protected files).
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/449)
> [LibOS] Pass file offset to `read` and `write` callbacks

- Documentation/manpages/gramine-sgx-ias-request.rst
- Pal/src/host/Linux-SGX/tools/common/attestation.c
- Pal/src/host/Linux-SGX/tools/common/ias.c
- Pal/src/host/Linux-SGX/tools/common/ias.h
- Pal/src/host/Linux-SGX/tools/ias-request/ias_request.c
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c
Previously, Gramine tools (including RA-TLS) used IAS API v3. This version is deprecated and will be EOLed on 16. August 2022. This commit updates Gramine to IAS API v4; the only difference is that Advisory URL & IDs are returned in HTTP response body (in v3, they are returned in HTTP response headers).
Closes https://github.com/gramineproject/graphene/pull/2268.
I tested manually on my machine.
1. Test with `ra-tls-mbedtls`:
```
~/gramineproject/gramine/CI-Examples/ra-tls-mbedtls$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 \
RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 RA_TLS_EPID_API_KEY=<my-key> ./client epid
. Seeding the random number generator... ok
. Connecting to tcp/localhost/4433... ok
. Setting up the SSL/TLS structure... ok
. Loading the CA root certificate ... ok
. Installing RA-TLS …
```
> [Pal/Linux-SGX] Update tools to use IAS API v4

- LibOS/shim/src/sys/shim_open.c
- LibOS/shim/test/ltp/ltp-sgx.cfg
- LibOS/shim/test/ltp/ltp.cfg
- LibOS/shim/test/regression/synthetic.c
- LibOS/shim/test/regression/test_libos.py
This PR also changes these syscalls to return `EINVAL` error code on special files (same as what Linux returns), as well as enables the LTP test `fsync03` that expects this error code.
This PR also adds previously "forgotten" `synthetic` LibOS regression test to Pytest, and augments this test with `fsync()` check.
LTP and LibOS regression tests are added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/464)
> [LibOS] Make `fsync()` and `fdatasync()` a no-op on dirs

- Pal/src/host/Linux-SGX/sgx_internal.h
- Pal/src/host/Linux-SGX/sgx_main.c
Signed-off-by: Zhang Lili <lili.z.zhang@intel.com>
Seems the two file descriptors (enclave->token and enclave->sigfile) will not be used after the call initialize_enclave().   Close the fds for resource recycling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/479)
> [Pal] Add missing syscall to close fds

- Documentation/devel/coding-style.rst
- LibOS/shim/test/fs/test_fs.py
- LibOS/shim/test/fs/test_pf.py
- LibOS/shim/test/fs/test_tmpfs.py
- LibOS/shim/test/ltp/test_ltp.py
- LibOS/shim/test/regression/test_libos.py
- Pal/gdb_integration/debug_map_gdb.py
- Pal/regression/test_pal.py
- Pal/src/host/Linux/gdb_integration/gramine_linux_gdb.py
- python/gramine-gen-depend
- python/gramine-manifest
- python/gramine-sgx-gen-private-key
- python/gramine-sgx-get-token
- python/gramine-sgx-sign
- python/gramine-test
- python/graminelibos/sgx_get_token.py
- python/graminelibos/sgx_sign.py
- python/graminelibos/sigstruct.py
- python/graminelibos/util_tests.py
Gramine Python utilities should use the system-wide Python interpreter instead of the local version of Python (which may not have system-wide-installed Python packages). This was detected in GSC when running the default Python Ubuntu Docker image.
Corresponding GSC PR: https://github.com/gramineproject/gsc/pull/49
Test GSC with our Python example: https://gramine.readthedocs.io/projects/gsc/en/latest/#example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/429)
> [Python] Change Python scripts' shebang to `/usr/bin/python3`

- Documentation/_templates/layout.html
- Documentation/conf.py
- Documentation/quickstart.rst
There were a few reports from people who used `/en/latest` documentation against v1.1 packaged version and got confused, because things got changed (last one was #477).
Let's add a warning to `/en/latest`.
Also, fix build issues caused by too new jinja.
https://gramine.readthedocs.io/en/woju-docs-warning/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/481)
> [Docs] Add admonition about master branch

- Pal/include/pal/pal.h
- Pal/src/host/Linux-SGX/db_eventfd.c
- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux-SGX/db_pipes.c
- Pal/src/host/Linux-SGX/db_process.c
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux/db_eventfd.c
- Pal/src/host/Linux/db_files.c
- Pal/src/host/Linux/db_pipes.c
- Pal/src/host/Linux/db_process.c
- Pal/src/host/Linux/db_sockets.c
Not used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/505)
> [Pal] Remove unused `disconnected` field from PAL_STREAM_ATTR structure

- LibOS/shim/src/sys/shim_socket.c
This is a temporary fix - rewrite of the whole subsystem is WIP. Hopefully we don't break anything with this...
Fixes #469, fixes #489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/499)
> [LibOS] Initialize socket handles to be readable and writable

- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/include/shim_handle.h
- LibOS/shim/src/fs/shim_fs_pseudo.c
This changes semantics of `/dev/attestation` writable files so that `write` (not flush/close) triggers an action. See #502 for discussion why this is adequate. 
Fixes #502.
See #502 for a manual test. The next PR (#504) also contains automated test for the error case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/508)
> [LibOS] Propagate errors when writing to pseudo-files

- python/graminelibos/util_tests.py
This translates to `uname -m` instead of `uname -p`. The latter is non-POSIX and does not work in some Linux distributions:
https://unix.stackexchange.com/a/307960
Bug found by @omeg.
Without this PR, on Debian, `gramine-test build` inside LibOS regression tests does not build manifests for `x86_64` tests (e.g. `cpuid`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/509)
> [python] Use `platform.machine()`, not `platform.processor()`

- CI-Examples/nginx/.gitignore
- CI-Examples/nginx/Makefile
- CI-Examples/nginx/README.md
- CI-Examples/nginx/nginx.manifest.template
- Documentation/conf.py
- Documentation/index.rst
- Documentation/manifest-syntax.rst
- Documentation/manpages/gramine-argv-serializer.rst
This PR extends `nginx` CI-Example to showcase the usage of passing command-line arguments securely to the application running inside the enclave. It also adds documentation on the usage of `gramine-argv-serializer` tool.
Please run the `nginx` example as part of `CI-Examples`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/460)
> [CI-Examples] Extend nginx example to use secure cmdline args

- LibOS/shim/include/shim_fs_encrypted.h
- LibOS/shim/src/fs/chroot/encrypted.c
- LibOS/shim/src/fs/shim_fs_encrypted.c
- LibOS/shim/test/regression/test_libos.py
- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
This adds rename support for encrypted files. The lowest layer is much like the old implementation in #31, but thanks to encrypted files being in LibOS, the issues mentioned there do not appear:
* it's possible to rename a file that is currently open
* it's not possible to rename a file "into" or "out of" encrypted files (since rename works only within a mounted filesystem)
* this shouldn't introduce problems with reference counting
Part of protected files redesign (#371).
Note that this does *not* affect `sgx.protected_files`, which still uses the old subsystem (we'll switch once the new one has all the same features).
The `rename_unlink` test is enabled for encrypted files. It tests various scenarios for deleting and renaming a file, possibly overwriting another file, keeping an open …
> [LibOS] Support renaming encrypted files

- LibOS/shim/src/arch/x86_64/shim_context.c
- LibOS/shim/test/regression/bootstrap_cpp.cpp
- Pal/src/host/Linux-SGX/sgx_syscall.c
Otherwise on GCC the snippets landed in whatever section we currently were.
Add `static const int asdf = 1;` to `pal_topology.h` and run `gramine-sgx`. The old code will segfault trying to execute `do_syscall_intr` from `.rodata`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/523)
> Add missing section declarations to toplevel inline assembly

- Pal/src/host/Linux-SGX/sgx_framework.c
- Pal/src/host/Linux-SGX/sgx_main.c
The "TOML parsing" message is always printed on enclave startup (because we cannot rely on the `log_level` specified in the manifest at startup). Previously, it was annoyingly printed for every child enclave.
An example of R, that calls `rm` and <some other utility> upon termination:
- before this PR:
```
~/gramineproject/examples/r$ gramine-sgx ./R --slave --vanilla -f scripts/sample.r
Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:
- loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
- sgx.allowed_files = [ ... ]                (some files are passed …
```
> [Pal/Linux-SGX] Skip "TOML parsing" message in child enclaves

- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/src/fs/shim_fs_pseudo.c
- LibOS/shim/src/fs/sys/cpu_info.c
- LibOS/shim/src/fs/sys/fs.c
This is a slight improvement of the pseudo-filesystem. As discussed with @mkow, it should be useful for the sysfs rewrite.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/527)
> [LibOS] shim_fs_pseudo: Make it easier to specify optional files

- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/src/fs/sys/fs.c
@mkow had difficulty understanding the `sys_resource` function, and for good reason: it has two very distinct use cases (parse number from name, list names).
The refactored version is slightly longer, but IMO more readable.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/528)
> [LibOS] fs/sys: Refactor `sys_resource`

- LibOS/shim/include/shim_fs.h
- LibOS/shim/include/shim_handle.h
- LibOS/shim/include/shim_types.h
- LibOS/shim/src/shim_parser.c
- Pal/src/host/Linux-common/file_utils.c
- Pal/src/host/Linux/pal_linux.h
- common/include/crypto.h
They are not needed and wrong (we are mostly no-std env).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/533)
> [LibOS,Pal] Weed out unnecessary `unistd.h` includes

- LibOS/shim/include/shim_fs.h
- LibOS/shim/include/shim_fs_encrypted.h
- LibOS/shim/src/fs/chroot/encrypted.c
- LibOS/shim/src/fs/dev/attestation.c
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/fs/shim_fs_encrypted.c
- LibOS/shim/src/fs/shim_fs_pseudo.c
- LibOS/shim/src/sys/shim_clone.c
- LibOS/shim/test/regression/keys.c
- LibOS/shim/test/regression/manifest.template
- LibOS/shim/test/regression/meson.build
- LibOS/shim/test/regression/test_libos.py
- LibOS/shim/test/regression/tests.toml
- LibOS/shim/test/regression/tests_musl.toml
This allows mounting encrypted files with `key = "..."` parameter. In addition, the keys can be now updated by application, by writing to `/dev/attestation/keys/<name>`.
The LibOS regression tests explicitly use `key = "custom"` now. There is also a test that checks if we can set a key, if errors are handled, and if the update persists after a fork.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/504)
> Support multiple keys in encrypted files

- LibOS/shim/src/fs/chroot/encrypted.c
- LibOS/shim/src/fs/shim_fs_encrypted.c
- LibOS/shim/test/regression/.gitignore
- LibOS/shim/test/regression/Makefile
- LibOS/shim/test/regression/manifest.template
- LibOS/shim/test/regression/test_libos.py
- Pal/include/host/Linux-common/pal_flags_conv.h
- Pal/include/pal/pal.h
- Pal/src/host/Linux-SGX/db_files.c
The new mount syntax supersedes `sgx.{allowed,trusted,protected}_files`, and the `encrypted` filesystem should always create "passthrough" PAL handles. This is ensured by introducing a special option to `DkStreamOpen`.
(I think that this option is temporary - if we manage to move all of trusted/protected files to LibOS, then all PAL handles will be "passthrough").
The LibOS regression tests worked only because we mounted `tmp/enc`, and we happened to include `tmp/` in the list of allowed files. Instead, the tests for encrypted files use a separate host directory (`tmp_enc/`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/534)
> [LibOS] Don't use PAL trusted/protected files in `encrypted` fs

- LibOS/shim/src/fs/chroot/encrypted.c
- LibOS/shim/src/fs/shim_fs_encrypted.c
- LibOS/shim/test/regression/manifest.template
- LibOS/shim/test/regression/test_libos.py
- Pal/include/pal/pal.h
- Pal/include/pal_internal.h
- Pal/src/db_misc.c
- Pal/src/host/Linux-SGX/db_misc.c
- Pal/src/host/Linux/db_misc.c
- Pal/src/host/Skeleton/db_misc.c
- Pal/src/pal-symbols
Key names beginning with `_` are considered special, and PAL is queried for these keys. This is used for SGX MRENCLAVE and MRSIGNER keys.
If a key is not supported by the current PAL, mounting will still succeed (but files will not be readable). This way, manifests using these PAL-host-specific keys can still be loaded when using other PAL hosts.
(This design is as discussed in #371).
The existing tests for MRENCLAVE and MRSIGNER keys now also check the new implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/539)
> [LibOS] Support special keys (MRENCLAVE, MRSIGNER) in `encrypted` fs

- python/gramine-test
Previously in Gramine, the `-C` option (change dir) and `-n` option (configure file name) were incompatible.
The gramine-test first confirms the file's existence and later changes the current working directory.
The verification is done by option library predefined type `click.Path`. The verification is done before the gramine-test
changes the directory, so it always checks the file's existence in the current working directory.
The workaround for this problem is to use a callback.
When the `-C` option is passed, change the directory as fast as possible and not wait until the command function is called.
Additionally, the argument `is_eager` will cause the library to parse the change dir option before anything else.
[Callbacks and Eager …
> [tests] Respect the change dir option

- .ci/lib/stage-clean-check.jenkinsfile
- .ci/lib/stage-test.jenkinsfile
- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- Documentation/cloud-deployment.rst
- Documentation/devel/building.rst
- LibOS/shim/test/abi/meson.build
- LibOS/shim/test/abi/x86_64/.gitignore
- LibOS/shim/test/abi/x86_64/atexit_func.asm
- LibOS/shim/test/abi/x86_64/common.c
- LibOS/shim/test/abi/x86_64/exit.asm
- LibOS/shim/test/abi/x86_64/fpu_control_word.asm
- LibOS/shim/test/abi/x86_64/manifest.template
- LibOS/shim/test/abi/x86_64/meson.build
- LibOS/shim/test/abi/x86_64/mxcsr.asm
- LibOS/shim/test/abi/x86_64/rflags.asm
- LibOS/shim/test/abi/x86_64/stack.asm
- LibOS/shim/test/abi/x86_64/stack_arg.asm
- LibOS/shim/test/abi/x86_64/test_entrypoint.py
- LibOS/shim/test/abi/x86_64/tests.toml
- LibOS/shim/test/meson.build
- meson.build
Add NASM compiler to the project - I believe we will want to move from GCC assembly to NASM in the future, so this is the first step.
The second change adds tests for the entry point. These tests verify the process initialization state as described n section 3.4 of System V Application Binary Interface. I also plan to add another ABI test regarding syscalls ABI. The new tests will also appear in the `abi_x86_64` directory. In the feature, if somebody else is interested, he can add analogous tests for other architectures using the similar naming pattern.
* [System V Application Binary Interface - AMD64 Architecture Processor Supplement](https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf)
```
gramine-test pytest
gramine-test --sgx pytest
```
--- …
> [tests] Introduce entrypoint tests

- python/graminelibos/manifest.py
Previously, the `manifest.py` tool read the whole trusted file in memory and only then calculated the hash over it. In case of some huge file, the tool could fail with `MemoryError`. Now we read the file in chunks.
A related StackOverflow question and replies: https://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python
This was detected on some workload with huge files and small amount of RAM. The error was like this:
```
gramine-sgx-sign \
--key enclave-key.pem \
--manifest python.manifest \
--output python.manifest.sgx
Traceback (most recent call last):
File "/usr/bin/gramine-sgx-sign", line 70, in <module>
main() # pylint: disable=no-value-for-parameter
...
File "/usr/bin/gramine-sgx-sign", line 30, in main
expanded = manifest.expand_all_trusted_files()
File …
```
> [python] Calculate SHA256 hash of trusted files in chunks

- LibOS/shim/include/shim_fs.h
- LibOS/shim/include/shim_vma.h
- LibOS/shim/src/bookkeep/shim_vma.c
- LibOS/shim/src/fs/chroot/encrypted.c
- LibOS/shim/src/fs/chroot/fs.c
- LibOS/shim/src/fs/shim_fs_mem.c
- LibOS/shim/src/fs/shim_fs_util.c
- LibOS/shim/src/fs/tmpfs/fs.c
- LibOS/shim/src/shim_rtld.c
- LibOS/shim/src/sys/shim_mmap.c
- LibOS/shim/test/fs/test_tmpfs.py
- LibOS/shim/test/regression/meson.build
- LibOS/shim/test/regression/mmap_file_emulated.c
- LibOS/shim/test/regression/test_libos.py
- LibOS/shim/test/regression/tests.toml
- LibOS/shim/test/regression/tests_musl.toml
This adds support for "emulated" memory mappings in LibOS. Memory is written back to the file using a new `msync` callback.
This (and #539) bring us to feature parity with SGX protected files, so the next step will be to replace the old implementation (see issue: #371).
There is a new LibOS regression test, `mmap_file_emulated`, that checks reading and writing an emulated file. In addition, some tmpfs tests are now unskipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/550)
> [LibOS] Implement `mmap` for encrypted and tmpfs files 

- Documentation/manifest-syntax.rst
- LibOS/shim/include/shim_fs_pseudo.h
- LibOS/shim/src/fs/proc/info.c
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/fs/sys/cache_info.c
- LibOS/shim/src/fs/sys/cpu_info.c
- LibOS/shim/src/fs/sys/fs.c
- LibOS/shim/src/fs/sys/node_info.c
- LibOS/shim/src/sys/shim_sched.c
- LibOS/shim/test/ltp/manifest.template
- LibOS/shim/test/regression/sysfs_common.manifest.template
- Pal/include/arch/x86_64/pal_topology.h
- Pal/include/pal/pal.h
- Pal/regression/Bootstrap.c
- Pal/src/db_main.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/enclave_framework.c
- Pal/src/host/Linux-SGX/enclave_ocalls.c
- Pal/src/host/Linux-SGX/sgx_api.h
- Pal/src/host/Linux-common/topo_info.c
This PR completely rewrites all three parts of sysfs topology handling:
- parsing sysfs files on the host (`topo_info.c`),
- passing them to LibOS, possibly across a security boundary (`Linux-SGX/db_main.c`),
- generating sysfs files inside LibOS based on the topology information (`fs/sys/*`).
The overall idea of the rewrite is to simplify and normalize the data structures passing through the untrusted interface, to ensure they are properly handled and sanitized. Effectively, this PR shifts as much complexity as possible to either untrusted side or to the part working on already sanitized, in-enclave data.
The reason for this change is the number of security issues found in the old code and review difficulty of sanitization in the old approach (despite multiple review passes I kept …
> Rewrite sysfs topology support

- LibOS/shim/src/fs/chroot/encrypted.c
The `hdrop` callback incorrectly assumed a that handle pointed to a regular file.
This commit also removes this assumption from other callbacks: while in most cases they should not be called for a directory handle, this is not yet a part of a documented contract.
Bug reported in https://github.com/gramineproject/gramine/issues/371#issuecomment-1116161688.
* Modify the manifest for `busybox` as specified in https://github.com/gramineproject/gramine/issues/371#issuecomment-1116161688
* Create `/tmp/testdir` on host
* Run `gramine-direct busybox ls /tmp/testdir`
This crashes on master, and is fixed in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/564)
> [LibOS] fs/encrypted: Fix crash on dropping a directory handle

- LibOS/shim/test/abi/x86_64/call_auxiliary.asm
- LibOS/shim/test/abi/x86_64/meson.build
- LibOS/shim/test/abi/x86_64/stack_auxiliary.c
- LibOS/shim/test/abi/x86_64/stack_env.asm
- LibOS/shim/test/abi/x86_64/stack_env.manifest.template
- LibOS/shim/test/abi/x86_64/test_entrypoint.py
- LibOS/shim/test/abi/x86_64/tests.toml
This change adds tests for verifying the environment variables and auxiliary vector.
Those additional tests were requested during the review of PR https://github.com/gramineproject/gramine/pull/541.
The environment variables test is straightforward. The only difference is a custom manifest file, which
sets up the environment variables. Please notice that we care about the order in this test, which isn't required by the ABI documentation. Removing this requirement would be over complication without any additional value.
In the case of the auxiliary vector, the ABI document doesn't specify which types are required.
I decided that the best approach would be to strictly verify the types that Gramine is setting up at this time.
- Lack of any auxiliary entry will cause the test to fail.
- …
> [tests] Add test for environment variables and auxiliary vector

- .ci/lib/stage-test-sgx.jenkinsfile
- CI-Examples/python/Makefile
- CI-Examples/python/README.md
- CI-Examples/python/python.manifest.template
- CI-Examples/python/run-tests.sh
- CI-Examples/python/scripts/sgx-quote.py
This script shows how to generate an SGX quote in Python.
Kudos to @lejunzhu for providing the initial Python script.
The test is added to the CI (via `run-tests.sh`).
When I run manually, the output looks like this:
```
~/gramineproject/gramine/CI-Examples/python$ gramine-sgx python scripts/sgx-quote.py
...
Extracted SGX quote with size = 4578 and the following fields:
ATTRIBUTES.FLAGS: 0700000000000000  [ Debug bit: True ]
ATTRIBUTES.XFRM:  0700000000000000
MRENCLAVE:        ac0415220cee87830641234cafc26139814c5fc4a3ba75fc1bd63acefa5548f8
MRSIGNER:         0dedbe47afb6955e5f6109637c1fbd9cc4b4e073e1396da8ce2091075e5b0a3b
ISVPRODID:        0000
ISVSVN:           0000
REPORTDATA:       0000000000000000000000000000000000000000000000000000000000000000 …
```
> [CI-Examples] python: Add `sgx-quote.py` script

- LibOS/shim/src/sys/shim_exit.c
- LibOS/shim/src/sys/shim_mmap.c
- LibOS/shim/src/sys/shim_sleep.c
- LibOS/shim/src/sys/shim_time.c
- Pal/src/host/Linux-SGX/db_exception.c
- Pal/src/host/Linux/db_exception.c
- common/include/api.h
In #525, @boryspoplawski suggested that a macro like this would be too complicated to be worthwhile. Having actually drafted an implementation, I don't think it looks too bad. In fact, I believe this turns the preferred approach of doing something once per enclave into something you have a chance of remembering.
You may run a program that triggers once of the warnings that make use of `DO_ONCE`, and verify that the warning, indeed, happens once. For example:
```c
#include <stdint.h>
#include <sys/mman.h>
int main(void) {
unsigned char output[16];
uintptr_t addr = (uintptr_t) main;
addr &= ~0xfff;
mincore((void*)addr, 4096, output);
mincore((void*)addr, 4096, output);
mincore((void*)addr, 4096, output);
return 0;
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [common] Create `FIRST_TIME()` macro

- LibOS/shim/test/ltp/test_ltp.py
Sets in Python do not have `+` operator, `union` method must be used instead.
Add a bug to Gramine which will fail some LTP test that has `must-pass` in config and try running it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/581)
> [LTP] Fix an incorrect usage of sets in "test_ltp.py"

- Pal/src/host/Linux-SGX/db_exception.c
The user may use this hint to disassemble the app binaries and find the offending instruction.
I didn't add a new test because I don't think it deserves it. Here is my manual testing:
- Add `ud2` in Helloworld:
```diff
diff --git a/LibOS/shim/test/regression/helloworld.c b/LibOS/shim/test/regression/helloworld.c
int main(int argc, char** argv) {
printf("Hello world!\n");
+    __asm__ volatile("ud2\n");
return 0;
}
```
- Run this test with at least `loader.log_level = "warning"`, you'll see:
```
warning: Unknown or illegal instruction executed (at 0x4004fb)
```
- Look at the Helloworld executable:
```bash
gramine/built-debug/lib/x86_64-linux-gnu/gramine/tests/libos/regression$
objdump -D helloworld | grep 4004fb
4004fb:       0f 0b                   ud2
```
--- …
> [Pal/Linux-SGX] On SIGILL, specify where in app code it happened

- LibOS/shim/include/arch/x86_64/shim_internal-arch.h
- LibOS/shim/include/shim_internal.h
- LibOS/shim/src/arch/x86_64/meson.build
- LibOS/shim/src/arch/x86_64/shim_elf_entry.nasm
- LibOS/shim/src/shim_rtld.c
As mentioned in https://github.com/gramineproject/gramine/pull/541, we would like to convert an AT&T assembly to Intel one. As I was working mainly with the entrypoint, I think this is an excellent start to experiment with it. Gramine already has all entrypoint tests, so it is easier to verify that this change doesn't break anything.
We don't set a register to any particular addresses, as the ABI document doesn't require that. After this change, the value of registers hasn't been changed.
```
gramine-test -C LibOS/shim/test/abi/x86_64/ pytest
gramine-test --sgx -C LibOS/shim/test/abi/x86_64/ pytest
gramine-test -C LibOS/shim/test/fs pytest
gramine-test --sgx -C LibOS/shim/test/fs pytest
gramine-test -C LibOS/shim/test/regression pytest
gramine-test --sgx -C LibOS/shim/test/regression …
```
> [LibOS] Reimplement call to elf entrypoint

- LibOS/shim/include/shim_internal.h
- LibOS/shim/src/fs/sys/fs.c
- LibOS/shim/src/shim_init.c
- LibOS/shim/src/sys/shim_clone.c
- Pal/include/pal/pal.h
- Pal/src/db_main.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/sgx_main.c
- Pal/src/host/Linux/db_main.c
This PR adds checkpoint-and-restore support for sysfs. It addresses issue 3 listed as part of https://github.com/gramineproject/graphene/issues/2105
Please run PAL/LibOS regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/583)
> [Pal,LibOS] Add checkpoint-and-restore support for sysfs

- Documentation/cloud-deployment.rst
- Documentation/quickstart.rst
Two commits in this PR:
- [Docs] Improve "Run sample application" section of Quick Start
- [Docs] Rewrite "Cloud Deployment" to use Gramine install. The previous version of this document described how to build Gramine from the GitHub repo, which is not user-friendly. Now this document is similar to the Quick Start Guide.
N/A.
I rented a couple MS Azure CC VMs (one with Ubuntu 18.04, another with Ubuntu 20.04) and installed Gramine in a bare minimum of steps. This documentation follows my experiments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/594)
> [Docs] Improve "Quick Start" and "Cloud Deployment" pages

- Documentation/attestation.rst
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c
Silently ignoring missing environment variables could turn a simple typo into a security-critical misconfiguration. Provide a more explicit way of ignoring a particular part of the SGX measurement and warn when an environment variable is simply missing.
Also detect and warn when neither MRSIGNER nor MRENCLAVE are specified.
Run the `ra-tls-mbedtls` example with some of the environment variables missing or set to `any` and observe the output.
Run `ra-tls-secret-prov` and note that the warnings are not printed, as a custom verification callback is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/586)
> [Pal/Linux-SGX] Provide RA_TLS_*=any, warn when the variable is unset

- CI-Examples/busybox/Makefile
A typo slipped through review
Try building busybox example with and without this PR, both in normal and SGX version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/602)
> [CI-Examples] Fix a typo in busybox Makefile

- meson.build
- subprojects/mbedtls-mbedtls-2.26.0-2.wrap
- subprojects/packagefiles/mbedtls/compile.sh
- subprojects/packagefiles/mbedtls/fcntl.patch
Due to symbol incompatibility on different glibc versions (`fcntl` vs `fcntl64`), `ra-tls-mbedtls` examble could not be built on Ubuntu18.04 if Gramine was build on any newer distro.
Try building Gramine on Ubuntu20.04 and installing + running `ra-tls-mbedtls` example on Ubuntu18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/611)
> [mbedtls] Patch sources to use `fcntl` syscall directly

- Pal/src/db_misc.c
- subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
This PR provides 2 patches that restrict a #define and a function to only be used and built when building for x86_64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/601)
> [common & PAL] Restrict a #define and a function to x86_64

- CI-Examples/ra-tls-secret-prov/secret_prov_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_min_client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template
This example sometimes runs out of memory when trying to map a large shared library. Encountered on #612 where the app sometimes failed to map `libm.so`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/617)
> [CI-Examples] Increase enclave size in "ra-tls-secret-prov"

- LibOS/shim/src/bookkeep/shim_vma.c
Whenever I used this function I always make this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/616)
> [LibOS] Make `debug_print_vma` print regardless of the log level

- CI-Examples/lighttpd/.gitignore
- LibOS/shim/test/regression/.gitignore
Git reported that we have commited files that should be ignored.
This PR fixes `.gitignores` to not exclude files that we actually have in our git repository.
* [gitignore doucmentation](https://git-scm.com/docs/gitignore)
```
git ls-files -ci --exclude-standard
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/606)
> [git] Fix ignore list

- LibOS/shim/src/bookkeep/shim_signal.c
- LibOS/shim/src/sys/shim_sigaction.c
Only pass the restorer to prepare_sigframe() if the SA_RESTORER flag is
set, otherwise pass NULL. Not all architectures support the restorer,
such as ppc64, and will never have that flag set.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/597)
> [LibOS] Pass the restorer if SA_RESTORER flag is set

- Documentation/cloud-deployment.rst
- Documentation/conf.py
- Documentation/quickstart.rst
By mistake, our Quick start guide and Cloud deployment pages contained:
```
git clone https://github.com/gramineproject/gramine.git <branch>
```
This is supposed to clone a single commit of Gramine (for CI-Examples testing). But this command clones the master branch of Gramine into a directory named `<branch>`. The correct form should be:
```
git clone https://github.com/gramineproject/gramine.git --branch <branch>
```
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/624)
> [Docs] Fix `git clone <branch>` shallow copy

- CI-Examples/bash/manifest.template
Enclave size of 256M is insufficient for Bash on CentOS.
This started to manifest itself with the new Glibc 2.35.
Signed-off-by: Aniket Borkar <aniketx.borkar@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/630)
> [CI-Examples] Increase Bash enclave size to 512M

- CI-Examples/rust/.cargo/config.toml
- CI-Examples/rust/Makefile
As it turns out, running `cargo` only to have it decide that no files have changed and no work needs to be done is, at least on some of our CI machines, not as fast as we'd expect. Thus it's actually worth it to make use of the `.d` files generated by Cargo to only run it when the source code has actually changed.
Closes #627.
Run `make` twice and note that only the first run executes cargo. Modify the source code and verify that it does trigger a rebuild.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/628)
> [CI-Examples/rust] Only run cargo when necessary

- .ci/lib/stage-test-direct.jenkinsfile
- LibOS/shim/test/ltp/test_ltp.py
- python/graminelibos/regression.py
To diagnose the LTP tests that sometimes time out, modify the test script such that CI timestamps each subtest getting executed. This will tell us if it's a hang, or if the machine is just slightly too slow for the current timeout values.
CI should suffice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/632)
> [LTP] Run timeout-prone tests with unbufferred output

- LibOS/shim/src/fs/shim_fs_encrypted.c
- LibOS/shim/src/shim_init.c
- LibOS/shim/src/sys/shim_socket.c
- Pal/regression/Hex.c
- Pal/src/host/Linux-SGX/db_misc.c
- Pal/src/host/Linux-SGX/enclave_framework.c
- Pal/src/host/Linux-SGX/sgx_framework.c
- common/include/hex.h
This commit removes macros `BYTES2HEXSTR` and `ALLOCA_BYTES2HEXSTR`, as well as introduces the `hex2bytes()` function instead of ad-hoc code snippets in LibOS and PAL codebase.
I promised this during the review of https://github.com/gramineproject/gramine/pull/638.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/644)
> [LibOS,PAL] Clean up hex parsing

- Documentation/attestation.rst
Commit "[Pal/Linux-SGX] Adapt for the new encrypted files API" deprecated the `SECRET_PROVISION_SET_PF_KEY` envvar and introduced the new `SECRET_PROVISION_SET_KEY` envvar instead. However, that commit forgot to update the Attestation documentation page.
The mentioned commit:
- https://github.com/gramineproject/gramine/commit/fbfd07c522a0b190c0a97158ea406e35c82fa0e0
- https://github.com/gramineproject/gramine/pull/587
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/643)
> [Docs] Describe new `SECRET_PROVISION_SET_KEY` envvar in attestation

- LibOS/src/fs/shim_fs_encrypted.c
Without this check, the called `encrypted_file_flush(enc)` assumes that the Encrypted File is opened and fails on an assert / with a segfault because it tries to access `enc->pf`.
Kudos to Anees Sahib <anees.a.sahib@intel.com> for root causing the bug.
A manual check looks something like this: add an `"encrypted"` FS mount pointing to some specific encrypted file in the manifest file, then create/use an app that first opens and then closes this encrypted file and then spawns a child process. You'll hit this bug.
We hit it on the PyTorch PPML tutorial. @aneessahib is working on an update to this tutorial, so he found and root caused the bug.
--- …
> [LibOS] Do not flush unopened Encrypted File during checkpoint

- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- CI-Examples/common_tools/benchmark-http.sh
- CI-Examples/lighttpd/README.md
- CI-Examples/nginx/README.md
The `benchmark-http.sh` script uses the Apache Benchmark (ab) under the hood. At least the default version of ab shipped with Ubuntu 18.04 (v2.3) does not work correctly with Nginx and HTTPS (it fails on KeepAlive HTTPS requests). So updated the script to use `wrk2`. Secondly, the median calculation in the script is broken and this PR addresses the issue. This PR also adds APIs to parse and convert throughput and latency metrics with SI units to plain numbers.  (Note: `wrk2` shows the results with SI units.)
Please run `nginx` or `ligttpd` as part of our `CI-Examples`
The results file should display median throughput and latency correctly.
When `LOOP = 1` which is the default case, we see only zeros.
```
cat result-220321-091419 …
```
> [CI-Examples] Update benchmark-http.sh script to use wrk2 benchmark

- libos/src/net/ip.c
This socket option allows for later retrieval of detailed error descriptions that happened on the socket. We do not support such retrieval, so allowing to set this option basically defers the moment the app notices that it's not supported from the call to `setsockopt`, to the moment the error condition actually happens (which might be never).
Fixes #673
Try running repro code from https://github.com/gramineproject/gramine/issues/673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/678)
> [LibOS] Handle `IP_RECVERR` socket option as a no-op

- libos/include/shim_fs.h
- libos/include/shim_handle.h
- libos/src/fs/pipe/fs.c
- libos/src/fs/socket/fs.c
- libos/src/net/unix.c
- libos/src/sys/shim_fcntl.c
- libos/src/sys/shim_pipe.c
And some code clean ups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/677)
> [LibOS] Allow setting `O_NONBLOCK` on not connected UNIX sockets

- Documentation/devel/onboarding.rst
- libos/src/shim_parser.c
- libos/src/sys/shim_exit.c
- libos/test/regression/test_libos.py
Syscall name should be enough to have in the trace log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/682)
> [LibOS] Remove `shim_` prefix from syscalls trace log

- libos/test/regression/cpuid.c
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux-sgx/pal_misc.c
Previously, `_DkCpuIdRetrieve()` was too restrictive on the leaf 0x7 (Structured Extended Feature Flags) -- it only allowed sub-leaves 0 and 1. In reality, Intel SDM states the following:
If ECX contains an invalid sub-leaf index, EAX/EBX/ECX/EDX return 0.
Sub-leaf index n is invalid if n exceeds the value that sub-leaf 0
returns in EAX.
This could lead to Gramine erroneously failing with `Unrecognized leaf/subleaf in CPUID`.
Fixes #668.
Added a test case in the `cpuid` LibOS test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/670)
> [Pal/Linux-SGX] Allow `CPUID(EAX=0x7, ECX=<any value>)`

- pal/src/host/linux/pal_files.c
- pal/src/host/linux/pal_host.h
`handle.file.map_start` initially introduced for fork emulation in https://github.com/gramineproject/graphene/commit/b8031c4224021f3943a87093f40c91ce4e431f34 was removed by https://github.com/gramineproject/gramine/commit/a95c063436053b218904d9da7e3e4dcaf4177397. It's not used any more so that we can remove it.
Fixes https://github.com/gramineproject/gramine/issues/694
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/695)
> [Pal/Linux] Remove unused `file.map_start` from `PAL_HANDLE`

- pal/src/host/linux-sgx/enclave_ocalls.c
This cause `ECONNRESET` to be translated to `EPERM` and confused the app. For example `lighttpd` printed error messaged, but continued to work.
Try running `lighttpd` example as we do in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/709)
> [PAL/Linux-SGX] Add `ECONNRESET` to errors allowed from `ocall_recv`

- .ci/lib/stage-test-direct.jenkinsfile
- libos/test/ltp/test_ltp.py
- python/graminelibos/regression.py
In #632, I attempted to add log timestamps to the intermittently-failing tests (`fcntl14` and `fdatasync01`, for example). As we've later discovered (see discussion on #642), the approach of live-piping the output and having CI timestamp it is not viable, as `pytest-xdist` doesn't support running tests with stdout capture disabled.
Therefore I change the strategy to logging timestamps within Python while the output is being pumped around. Then the output gets printed, with the timestamps, when a test fails. This has the additional benefit of not having to list the problematic tests anywhere.
Closes #642.
Try running a test with `-s` (e.g. `python3 -m pytest -v -k fcntl14 -s`, cf. [the docs on running LTP tests](https://gramine.readthedocs.io/en/latest/devel/contributing.html#ltp)), …
> [tests] Log timestamps within Python

- CI-Examples/common_tools/download
The default number is `20` which combined with 10s per try timeout could result in a pipeline timeout in our CI, if the host (from which we download) was down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/710)
> [CI-Examples] Change the default retries number in `downloads` script

- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- CI-Examples/lighttpd/lighttpd-generic.conf
Additionally, this commit also increases max-connections value for `lighttpd` workload in CI-Examples. This was done to remove the following log messages:
```
server.c.980) [note] sockets disabled, connection limit reached
server.c.973) [note] sockets enabled again
```
Please run `lighttpd` workload as part of the `CI-Examples`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/693)
> [CI] Add bash bc tool to CI systems

- .ci/lib/stage-lint.jenkinsfile
- scripts/gitignore-check-files
After the https://github.com/gramineproject/gramine/pull/606, we don't have any files listed as ignored (in `.gitignore` files) and which are in the repo. This PR introduces a Jenkins check that verifies that this assumption hasn't been violated.
```
$ ./scripts/gitignore-check-files
.gitignore rules aren't violated
$ echo $?
0
$ touch libos/test/fs/build.ninja
$ git add -f libos/test/fs/build.ninja
$ ./scripts/gitignore-check-files
================================================================================
ERROR: Files ignored by git exists in the repository:             
--------------------------------------------------------------------------------
libos/test/fs/build.ninja
================================================================================
$ echo $?
1
```
---
This …
> [CI] Verify that .gitignore rules aren't violated

- CI-Examples/ra-tls-secret-prov/Makefile
Signed-off-by: Veena Saini <veena.saini@intel.com>
Sometimes, we have a requirement of creating the dcap server binary along with ssl certificates on a non-sgx system. This change helps user to get the dcap server binary along with certificates using `make dcap` command only. 
Step 1: `make app dcap ` should work as before 
Step 2: `make distclean`
Step 3: `make dcap` should generate `secret_prov_server_dcap` binary with ssl ceritificates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/727)
> [CI-Examples] Add SSL cert creation for `make dcap` target

- common/include/api.h
- common/src/path.c
- libos/src/fs/libos_fs.c
- pal/include/host/linux-common/linux_utils.h
- pal/src/host/linux-common/file_info.c
- pal/src/host/linux-common/meson.build
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux/pal_files.c
`file_stat_type`, `file_attrcopy` and `is_dot_or_dotdot` are shared between
pal/linux and pal/linux-sgx, hence can be moved to Linux-common header.
Fixes https://github.com/gramineproject/gramine/issues/696
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/697)
> [Pal] Move shared functions to Linux-common header

- libos/src/libos_init.c
At the start, Gramine often outputs allocating stack at 0
Now the log work correctly!
```
debug: Gramine was built from commit: 1.2post-UNRELEASED
debug: Host: Linux
debug: LibOS xsave_enabled 1, xsave_size 0x440(1088), xsave_features 0x1f
debug: Initial VMA region 0x7ffff3efd000-0x7ffff3fd1000 (LibOS) bookkeeped
debug: Initial VMA region 0x7ffff3fd2000-0x7ffff7fd2000 (pal_init_pool) bookkeeped
debug: Initial VMA region 0x7ffff7fd6000-0x7ffff7fd8000 (vdso) bookkeeped
debug: Initial VMA region 0x7ffff7fd2000-0x7ffff7fd6000 (vvar) bookkeeped
debug: Initial VMA region 0x7ffff3fd1000-0x7ffff3fd2000 (pal_internal_me) bookkeeped
debug: ASLR top address adjusted to 0x42ef1b19e000
debug: Shim loaded at 0x7ffff3efd000, ready to initialize
debug: mounting "file:." (chroot) under /
debug: mounting …
```
> [LibOS] Move "Allocated stack" log message to after `allocate_stack()`

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files_internal.h
The `offset` field supposed to represent the current file position (user's view). This isn't true. The actual offset of the file is kept in the LibOS, not in the protected files. We can observe this when `lseek(2)` is used. Also there isn't any API that allows us to get a current offset from protected file structure. The offset is changed when the LibOS wants to read/write the data.
This field is ambiguous, so it's better to remove it and pass the requested offset to each function.
```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/719)
> [common] Drop offset from the protected file structure

- common/include/api.h
- common/src/arch/meson.build
- common/src/arch/x86_64/ct_memequal.nasm
- common/src/arch/x86_64/meson.build
- common/src/meson.build
- pal/src/host/linux-sgx/enclave_framework.c
The MAC check in `sgx_verify_report()` should be done in a constant-time manner
to avoid side-channel leaks via timing attacks which could potentially allow an
attacker to guess a valid value and thereby bypass security controls. Similar
hardening is also applied in SGX SDK.
Signed-off-by: Kailun Qin <kailun.qin@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/704)
> [common,PAL] Introduce constant-time memcmp and use it for MAC check

- libos/test/fs/meson.build
- libos/test/fs/seek_tell_truncate.c
- libos/test/fs/test_fs.py
- libos/test/fs/tests.toml
The goal of this test is to verify that Gramine doesn't change file offset after truncation.
This is a test.
```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/718)
> [LibOS] Add seek/tell/truncate test

- pal/src/host/linux-sgx/pal_pipes.c
Linux SGX PAL pipes are encrypted using TLS. This requires performing a handshake when they are created. If the pipe is to be nonblocking, we make it so only after the handshake, not to waste time on send/recv ocalls returning `EAGAIN` (no data on nonblocking fd).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/715)
> [PAL/Linux-SGX] Set pipe handle as nonblocking only after TLS handshake

- libos/include/libos_fs_pseudo.h
- libos/include/libos_vma.h
- libos/src/bookkeep/libos_vma.c
- libos/src/fs/proc/fs.c
- libos/src/fs/proc/info.c
- libos/src/fs/proc/thread.c
- libos/test/regression/test_libos.py
Resolves https://github.com/gramineproject/gramine/issues/614. Use the VMA subsystem instead of adding a PAL API.
An application may want to adjust itself based on the peak memory usage in some scenarios. This patch adds VmPeak stats into the pseudo-file `/proc/<pid>/status` to support the usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/742)
> [LibOS] Add peak memory usage support in procfs

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files_internal.h
- libos/test/fs/seek_tell.c
- libos/test/fs/test_fs.py
The file should grow only during write and truncation. The protected file was extended when the application opened it for reading and writing and read from an offset larger than the current size. Previous logic, in the `ipf_update_after_seek` function, assumed that if the file is writable, the file should be extended. This function was called in the read and write routine of protected files.
New tests verify that the file is not extended after seek/tell routine, and they are not extended after the read syscall.
```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/738)
> [common] Don't extend files while reading data from protected files

- python/graminelibos/regression.py
Apparently we didn't test the case when the tests are actually timing out. This fixes a subtle bug in the handling of that.
Artificially reduce the timeout of a test in `ltp.cfg` and observe the test suite behaving correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/732)
> [tests] Fix detecting LTP timeouts

- libos/src/libos_rtld.c
- libos/test/regression/exec_script.c
According to POSIX, if the pathname argument of `execve()` specifies
an interpreter script, then interpreter will be invoked with the following
arguments:
interpreter [optional-arg] pathname arg...
where `pathname` is the pathname of the file specified as the first argument of
`execve()`, and `arg...` is the series of words pointed to by the `argv` argument
of `execve()`, starting at `argv[1]`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/754)
> Override `argv[0]` with file pathname for interpreter scripts

- CI-Examples/ra-tls-mbedtls/README.md
- CI-Examples/ra-tls-mbedtls/src/client.c
- CI-Examples/ra-tls-mbedtls/src/server.c
- tools/sgx/ra-tls/ra_tls.h
Previously, RA-TLS exposed two mbedTLS-specific APIs:
- `ra_tls_verify_callback(..,  mbedtls_x509_crt*, ..)`
- `ra_tls_create_key_and_crt(mbedtls_pk_context*, mbedtls_x509_crt*)`
Any app that wanted to use these APIs of RA-TLS should have been linked against `mbedtls_gramine` version of mbedTLS. Otherwise the internal formats of `mbedtls_x509_crt` and `mbedtls_pk_context` objects could diverge, leading to hard-to-diagnose bugs.
Apps should not rely on Gramine-internal mbedTLS version. So this PR removes these two mbedTLS-specific funcs from RA-TLS API. **This is a breaking change**, but better do it now, while RA-TLS is not widely used.
Consequently, this PR modifies the `ra-tls-mbedtls` example to use DER-format versions of these functions.
For the context, see also discussion in …
> [tools] Remove mbedTLS-specific funcs from RA-TLS API

- libos/src/libos_rtld.c
Print debug message on `-ENOEXEC` error (failure to read the shebang line) instead of the error message. The error code is already propagated to the app that called `execve()`, and sometimes apps open "wrong" files (e.g., LTP does it), so it is not a Gramine error and must be silenced.
Run LTP `execve` tests. There is at least one test that tries to `execve("dummy-file")` on purpose, and suddenly we saw that `log_error` message. Now the error message gone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/782)
> [LibOS] Print debug message in `load_and_check_shebang()`

- libos/include/arch/x86_64/libos_cpuid.h
- libos/src/arch/x86_64/fs_proc/info.c
- libos/src/arch/x86_64/libos_cpuid.c
- libos/src/arch/x86_64/meson.build
- libos/test/regression/proc_cpuinfo.c
- libos/test/regression/test_libos.py
- pal/include/arch/x86_64/pal_arch.h
- pal/regression/Bootstrap.c
- pal/regression/test_pal.py
- pal/src/arch/x86_64/pal_cpuid.c
Some workloads may require to parse the flags line in the pseudo-file
`/proc/cpuinfo`.
This patch
- removes `cpu_flags` from `pal_cpu_info` to keep the generality of PAL (i.e., to avoid emulating part of Linux-specific stuff in PAL, which should be done in LibOS instead)
- builds the `flags` line via performing `PalCpuIdRetrieve()` call when printing `/proc/cpuinfo`
Partially resolves  https://github.com/gramineproject/gramine/issues/592.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/768)
> [LibOS,PAL,common] Add `flags` line to `/proc/cpuinfo`

- tools/sgx/ra-tls/secret_prov_attest.c
From the man page of `strtok_r()` (https://man7.org/linux/man-pages/man3/strtok.3.html#NOTES): on some implementations, `*saveptr` is required to be NULL on the first call to `strtok_r()` that is being used to parse str.
This patch thus initializes the saveptr of `strtok_r()` to NULL for better portability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/784)
> [tools/sgx] Initialize `strtok_r()`'s saveptr to NULL

- libos/include/libos_internal.h
- libos/include/libos_process.h
- libos/include/libos_table.h
- libos/include/libos_utils.h
- libos/src/bookkeep/libos_process.c
- libos/src/libos_init.c
- libos/src/libos_rtld.c
- libos/src/sys/libos_exec.c
Previously, LibOS codebase used incorrect types:
- `const char** argv`
- `const char** envp`
In reality, the types must be "arrays of constant pointers". So the correct types should be:
- `char* const* argv` (array of constant ptrs to data)
- `const char* const* envp` (array of constant ptrs to constant data)
Notice that argv items point to non-constant data: this is because argv list is modified in LibOS -- both the pointers and the strings. On the other hand, envvars are not modified so they have const qualifiers in both places.
Good references:
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html -- read RATIONALE
- https://github.com/gramineproject/gramine/pull/459 -- for some initial discussions
- https://c-faq.com/ansi/constmismatch.html
- …
> [LibOS] Use proper const qualifiers for `argv` and `envp`

- pal/regression/Directory.c
- pal/regression/test_pal.py
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_files.c
- pal/src/host/linux/pal_host.h
- pal/src/host/linux/pal_streams.c
Previously in `file_open`, `file.realpath` is allocated [together with the handle](https://github.com/gramineproject/gramine/blob/85078de3222367da4d0aaa14793c218648a94659/pal/src/host/linux/pal_files.c#L42). But in `file_rename`, it is allocated to a [separate memory location](https://github.com/gramineproject/gramine/blob/85078de3222367da4d0aaa14793c218648a94659/pal/src/host/linux/pal_files.c#L219). After this change, `file.realpath` is also allocated separately in `file_open`, and there is no need to [check the address of the pointer](https://github.com/gramineproject/gramine/blob/85078de3222367da4d0aaa14793c218648a94659/pal/src/host/linux/pal_files.c#L116) when doing free inside `file_close`. Same for `dir.realpath`.
Remove calling `dir_close()` in …
> [Pal] Always allocate `file.realpath` and `dir.realpath` in separate memory locations

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files_internal.h
As suggested in review https://reviewable.io/reviews/gramineproject/gramine/719 we don't want to have a file header with static definitions used in a single file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/766)
> [common] Remove static function declarations from protected_files_internal.h

- libos/include/libos_handle.h
- libos/include/libos_internal.h
- libos/include/libos_process.h
- libos/src/arch/x86_64/start.S
- libos/src/bookkeep/libos_handle.c
- libos/src/bookkeep/libos_process.c
- libos/src/libos_init.c
- libos/src/sys/libos_exec.c
- libos/test/regression/shebang_test_script.manifest.template
- libos/test/regression/shebang_test_script.sh
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
This will enable users to run scripts in Gramine (as opposed to manually providing a ELF entrypoint - this can be quite an inconvenience to users). This will also minimize the need to create wrapper docker files for entrypoint manipulation while using GSC.
Fixes https://github.com/gramineproject/gramine/issues/320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/722)
> Support running scripts as the entrypoint

- libos/src/arch/x86_64/libos_cpuid.c
- libos/test/regression/test_libos.py
Some workloads may depend on the specific CPU feature flags in the `flags` line of the pseudo-file `/proc/cpuinfo` (e.g.,
intel-extension-for-pytorch looks for the `avx2` flag). However, currently Gramine only supports a subset of them (e.g., `avx2` is not included).
This patch extends support for more CPU feature flags in `proc/cpuinfo` by performing a bunch of `PalCpuIdRetrieve()` calls, finding the currently enabled HW features, and adding the corresponding flag-descriptions.
Resolves https://github.com/gramineproject/gramine/issues/592.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/789)
> [LibOS] Support more CPU feature flags in `/proc/cpuinfo`

- tools/sgx/common/util.c
The current implementation of the `pf_crypt` tool uses `fstat` to find the wrap_key length. But `fstat` implementation in Gramine sgx doesn't support reporting the size field. So, use `lseek` to determine the length of the file when running within the enclave.
Please run LibOS, PAL, fs regression tests. Also, please try encrypting and decrpting using `gramine-sgx-pf-crypt`  tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/787)
> [tools/sgx] Fix `pf_crypt` to run within an enclave

- CI-Examples/ra-tls-mbedtls/README.md
- Documentation/attestation.rst
- Documentation/sgx-intro.rst
`RA_TLS_ISV_SVN` description in document is not aligned with implementation.
https://github.com/gramineproject/gramine/blob/64b004bb59a237ea2486ef791fd970519888c638/tools/sgx/common/quote.c#L191-L194
Also add `Security Version Number (SVN)` in glossary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/793)
> [Doc] Correct `RA_TLS_ISV_SVN` description in attestation

- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- Documentation/devel/building.rst
- meson.build
"meson >= 0.56" is required for properly linking static libraries with custom targets.
See https://github.com/gramineproject/gramine/pull/773#pullrequestreview-1051815308 for details.
Related gsc PR: https://github.com/gramineproject/gsc/pull/82.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/799)
> [meson,CI,Docs] Upgrade Meson to ">= 0.56"

- Documentation/container-integration.rst
- Documentation/gsc.rst
- Documentation/index.rst
We now have not only GSC, but also the Gramine Docker image hosted on DockerHub. Update our documentation to mention both tools and prepare for more tools/workflows in the future. Also, GSC was split from the core repository a long time ago and there is no need to emphasize that, so we rephrase its description.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/749)
> [Docs] Change "GSC" page to "Container integration"

- libos/test/regression/test_libos.py
Bash first resolves the path to be absolute and then passes it as pathname (contrary to dash, which does not do it).
Dash is a default `/bin/sh` on Ubuntu, so the shebang test previously used a relative pathname. But on CentOS/RHEL/Fedora, Bash is the default `/bin/sh`, and thus the shebang test failed. With this PR, we introduce a Regex that works both for relative and absolute pathnames.
Fixes #807.
@anjalirai-intel Could you test it on CentOS?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/809)
> [LibOS/regression] Fix `test_212_shebang_test_script` to run with bash

- libos/src/bookkeep/libos_thread.c
Klocwork detected memory leaks due to non-freeing of memory resources in the event of `PalThreadGetCpuAffinity` failure. This commit fixes the three leaks reported by Klocwork.
Regular CI test suite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/810)
> [LibOS] Fix memory leaks detected by Klocwork

- libos/test/regression/attestation.c
Previously, we inlined the mbedtls relevant definitions due to no access to mbedtls headers (mbedtls is built as a Meson suproject while the attestation test file was compiled using Make at that time).
As this test is built using Meson now, we should use #include mbedtls headers instead of the definitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/818)
> [tests] Use #include mbedtls headers in the attestation test

- CI-Examples/ra-tls-secret-prov/Makefile
- CI-Examples/ra-tls-secret-prov/README.md
- CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c
The `libsecret_prov_attest.so` library provisions a secret upon successful attestation. However, there can be cases when applications would want Gramine to terminate upon an unsuccessful attestation, as opposed to the application directly handling this part. In this PR,  `libsecret_prov_attest.so`  exits when attestation is unsuccessful, also handles a case where there aren't any keys to provision, under which case a `REMOTE_ATTESTATION_SUCCESSFUL` string is set at the host enclave (by the server), that client applications are free to customize and use if they want.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/721)
> [CI-Examples] Modify secret_prov_server to not require a key

- tools/sgx/ra-tls/ra_tls_verify_dcap.c
This patch adds/fixes the following in `ra_tls_verify_callback()` for DCAP:
- checking and warning `collateral_expiration_status` when the collateral is out-of-date
- failing fast when `verification_result` is considered a failure (i.e., not continuing the verification of other information, which is incorrect in such case)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/815)
> [tools/sgx] Enhance RA-TLS DCAP quote verification logic

- libos/include/libos_lock.h
This function is meant to be used only in `assert`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/834)
> [LibOS] Define `locked` function only in debug builds

- libos/include/libos_handle.h
- libos/src/bookkeep/libos_handle.c
- libos/src/sys/libos_exit.c
Fixes https://github.com/gramineproject/gramine/issues/824.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/830)
> [LibOS] Close open fds on thread exit

- libos/src/libos_parser.c
Parse and print `sockaddr` in log of bind syscall. for example:
```
trace: ---- bind(6, {family=INET6,ip=[0:0:0:0:0:0:0:0],port=htons(29501)}, 28) = 0x0
```
Also change `family=INET` to `family=INET6` in log of `bind` and `connect` when it's `AF_INET6`.
Straightforward change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/829)
> [LibOS] Enhance logging of `bind` syscall

- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c
- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.h
- pal/src/host/linux-sgx/host_main.c
Modern Intel CPUs have a large number of cores, and modern workloads (such as PyTorch) allocate a large number of threads (e.g., 4 threads per each CPU core). This exceeds the previous limit on the number of threads (1024) and leads to boostrap errors like this:
error: There are no available TCS pages left for a new thread!
Please try to increase sgx.thread_num in the manifest.
This PR bumps the limit to 4096 and fixes several potential stack-overflow issues along the way.
CI. Plus I tested several large workloads manually (testing with different `sgx.enclave_thread` settings).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/812)
> [PAL/Linux-SGX] Bump the max number of enclave threads to 4096

- CI-Examples/ra-tls-secret-prov/src/secret_prov_client.c
- CI-Examples/ra-tls-secret-prov/src/secret_prov_server.c
- tools/sgx/ra-tls/secret_prov.h
- tools/sgx/ra-tls/secret_prov_attest.c
- tools/sgx/ra-tls/secret_prov_common.c
- tools/sgx/ra-tls/secret_prov_common.h
- tools/sgx/ra-tls/secret_prov_verify.c
This is a breaking change that modifies the API of the Secret Prov lib as follows:
- `secret_provision_start()` allocates a context that should be supplied to all other Secret Prov APIs and must be closed afterwards.
- `secret_provision_get()` requires a context as the first argument, and extracts the secret that is associated with this context. Thus, it allows for several secrets being delivered in parallel from different remote parties (previously, the secret was a global variable).
- `secret_provision_destroy()` is removed. Instead, users should call `secret_provision_close()` that will both close the session and destroy the secret.
With these changes, the context ceases to be global, and the library becomes thread-safe. Also, leaks of mbedTLS resources are prevented.
As a small side …
> [tools/sgx] Improve public API of Secret Prov lib

- libos/src/libos_rtld.c
LibOS codebase doesn't require `handle::uri` to be set. Appending NULL URI directly to GDB link map will lead to an unexpected memory fault occurred inside PAL.
This patch appends `handle::uri` to GDB link map only when it's set.
Fixes #840.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/845)
> [LibOS] Append `handle::uri` to GDB link map only when it's set

- libos/include/libos_handle.h
- libos/src/bookkeep/libos_handle.c
- libos/src/sys/libos_exec.c
- libos/test/regression/fcntl_lock.c
- libos/test/regression/manifest.template
Quickly adapted from a previous PR.
Resolves https://github.com/gramineproject/gramine/issues/836.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/837)
> [LibOS] Release POSIX file locks on fds with `CLOEXEC` flag on `execve`

- libos/src/sys/libos_ioctl.c
- libos/src/sys/libos_socket.c
`ioctl(FIONCLEX/FIONCLEX)` should update flags in `libos_fd_handle` instead of `libos_handle`. `O_CLOEXEC` flag is only handled in `libos_fd_handle`. 
Also add `O_RDWR` to flags of `libos_handle` for socket.
Now `ioctl(FIONCLEX/FIONCLEX)` and `fcntl(F_GETFD/F_SETFD/F_GETFL/F_SETFL)` have expected behavior and return value.
Fixes #819
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/842)
> [LibOS] fix `ioctl(FIONCLEX/FIONCLEX)` syscall

- libos/test/fs/common.c
All these functions use libc:
```
#0  __GI___libc_read (fd=3, buf=0x6c323d475010, nbytes=1048576) at ../sysdeps/unix/sysv/linux/read.c:25
#1  0x00006c323d8b1951 in read_fd (path=0x6c323d8f6ff4 "tmp/a", fd=3, buffer=0x6c323d475010, size=1048576) at ../libos/test/fs/common.c:32
#2  0x00006c323d8b1557 in read_write (file_path=0x6c323d8f6ff4 "tmp/a") at ../libos/test/fs/read_write.c:15
#3  0x00006c323d8b1741 in main (argc=3, argv=0x6c323d8f6ec8) at ../libos/test/fs/read_write.c:45
```
The return value for read(2)/write(2)/sendfile(2) should be -1 and errno should be set
to indicate the type of error.
Beside that:
- sendfile(2) should check if it wasn't interrupted,
- read(2) and write(2) aren't used with non-blocking fds, but because
we are here, let's also verify the EAGAIN error.
``` …
```
> [tests] Fix retval checks

- Documentation/devel/coding-style.rst
- libos/src/libos_checkpoint.c
- pal/src/host/linux-sgx/enclave_ecalls.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/enclave_pages.c
- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c
- pal/src/host/linux-sgx/host_ecalls.c
@dimakuv and @boryspoplawski in https://github.com/gramineproject/gramine/pull/850 proposed to remove a rule about matching .c and .h files.
I went through all files in `pal/src`, `pal/regression`, `libos/src/`, `libos/test/abi`, `libos/test/fs`, `libos/test/regression`, and there subdirectories - it seems like this rule isn't applied often.
Build should be enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/861)
> [Docs] Remove rule about matching .c and .h files

- Documentation/manifest-syntax.rst
- libos/test/regression/argv_from_manifest.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/src/pal_main.c
This PR implements the `loader.argv` described in #761. In this issue @mkow raises the question about `loader.argv0_override` , however this option was recently removed by @dimakuv in f91a2c18370858701a33c00620b0c7954f6779bf.
The whole section was converted to use the table. This was done because currently Gramine version of tomlc99 doesn't support dot notation in `toml_array_in`.
Fixes #761.
New tests was added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/858)
> [PAL] Introduce `loader.argv` manifest option

- Documentation/manifest-syntax.rst
The wording is slightly less verbose and represented as a bullet list now. Reads easier.
One person complained about the previous paragraph with three options (it was confusingly written). Also, the `Note` kinda splits the section into two halves, and people didn't notice the second half.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/880)
> [Docs] Improve wording about commandline arguments

- tools/sgx/ra-tls/ra_tls_verify_dcap.c
As in the title. Found when I tested Michal's changes to `ra-tls-secret-prov`.
- Without this PR:
```
./server_dcap
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -12288
```
- With this PR:
```
./server_dcap
ra_tls_verify_callback: Quote: verification failed with error SW_HARDENING_NEEDED
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -12288
```
(To circumvent this error that says that the platform is outdated, we can simply do `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 ./server_dcap`.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/883)
> [tools/sgx] Add error messages for DCAP quote verification

- common/include/linux_socket.h
- libos/include/libos_flags_conv.h
- libos/src/libos_pollable_event.c
- libos/src/sys/libos_eventfd.c
- libos/test/regression/fdleak.c
- libos/test/regression/test_libos.py
- pal/include/host/linux-common/pal_flags_conv.h
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c
- pal/src/host/linux-sgx/host_log.c
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/host_perf_data.c
- pal/src/host/linux-sgx/host_platform.c
- pal/src/host/linux-sgx/host_process.c
- pal/src/host/linux-sgx/host_profile.c
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux-sgx/pal_eventfd.c
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux-sgx/pal_misc.c
- pal/src/host/linux-sgx/pal_pipes.c
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_devices.c
- pal/src/host/linux/pal_eventfd.c
- pal/src/host/linux/pal_files.c
- pal/src/host/linux/pal_main.c
- pal/src/host/linux/pal_memory.c
- pal/src/host/linux/pal_pipes.c
- pal/src/host/linux/pal_streams.c
- python/graminelibos/regression.py
This flag was used to control `CLOEXEC` flag of host OS fd, and as such, was Linux specific. It was also not really needed - Linux and Linux SGX PALs always set it on host fd anyway.
This commit also adds all missing `CLOEXEC` flag usages in Linux and Linux SGX PALs.
Fixes #864
`fdleak` test augmented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/866)
> [PAL] Remove `PAL_OPTION_CLOEXEC` flag

- common/src/ubsan.c
- libos/src/sys/libos_sched.c
- libos/test/ltp/ltp.cfg
- libos/test/regression/pthread_set_get_affinity.c
This PR was dependent on sysfs rewrite. Now that it is done, reviving this PR.
This commit adds an approx. implementation of `getcpu` syscall that returns a random set bit from cpu affinity mask associated
with calling thread and its corresponding NUMA node.
`pthread_set_get_affinity` regression test is extended to validate this implementation. This commit also enables the
`getcpu01` ltp test for non-SGX case.
Closes https://github.com/gramineproject/graphene/pull/2331
Please run `pthread_set_get_affinity` LibOS regression test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/609)
> [LibOS] Add support for `getcpu` syscall

- CI-Examples/nginx/nginx.manifest.template
- Documentation/manifest-syntax.rst
- Documentation/performance.rst
- libos/test/regression/multi_pthread_exitless.manifest.template
- pal/regression/Thread2_exitless.manifest.template
- pal/src/host/linux-sgx/enclave_api.h
- pal/src/host/linux-sgx/enclave_ecalls.c
- pal/src/host/linux-sgx/enclave_framework.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux-sgx/pal_rpc_queue.h
If malicious host maps APIC registers in some untrusted memory (MMIO) and this memory is subsequently read by the enclave (e.g. when reading some results of an ocall) such read can potentially return some stale, enclave-originated data. Naturally aligned 8-byte reads are not affected by this vulnerability, so as software mitigation, this commit makes all untrusted memory accesses 8-byte wide and naturally aligned.
As a side effect the exitless ocalls feature becomes potentially insecure. It uses untrusted memory in some complex manner, which we did not bother changing for now, as the feature is not widely used.
Fixes #846
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gr …
> [PAL/Linux-SGX] Mitigate CVE-2022-21233 aka INTEL-SA-00657

- pal/src/host/linux-sgx/enclave_framework.c
It specified that some values are both read and written in an incorrect manner.
If you were unlucky (no idea what are the exact circumstances), current master might not have compiled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/909)
> [PAL/Linux-SGX] Fix inline asm in `copy_u64s()`

- CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template
- libos/src/fs/libos_fs_encrypted.c
Without this normalization, Gramine would fail on syntax like this:
fs.mounts = [ { path = "/a/", uri = "file:a/", type = "encrypted" } ]
This was because LibOS concatenated the URI and the filename by adding `/`, resulting in non-normalized URI `file:a//name`. However, the Protected Files common logic requires URIs to be normalized, otherwise filename comparison (done to prevent file-swap attacks) fails.
Fixes #904.
`ra-tls-secret-prov` example fixed. The rest of CI passes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/908)
> [LibOS] Normalize paths in URIs of `encrypted` FS mounts

- libos/src/sys/libos_dup.c
Add missing rlimit check on newfd to dup3().
Also see here: https://elixir.bootlin.com/linux/latest/source/fs/file.c#L1217
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/887)
> [LibOS] Add missing rlimit check on newfd to dup3()

- libos/include/libos_fs_pseudo.h
- libos/src/fs/sys/fs.c
- libos/src/fs/sys/node_info.c
Gramine currently doesn't emulate `/sys/devices/system/node/nodeX/meminfo` files. This will lead to some workload failures due to these missing NUMA node meminfo files.
This patch adds basic support for the above usage by simply "mimicking" a typical environment where each NUMA node returns:
- NodeMemTotal = PalMemTotal / numa_nodes_cnt
- NodeMemFree = PalMemAvailable / numa_nodes_cnt
Resolves https://github.com/gramineproject/gramine/issues/364.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/847)
> [LibOS] Support `/sys/devices/system/node/nodeX/meminfo` files

- Documentation/manifest-syntax.rst
- libos/include/libos_internal.h
- libos/src/libos_init.c
- libos/src/sys/libos_uname.c
- libos/test/regression/hostname.c
- libos/test/regression/hostname_extra_runtime_conf.manifest.template
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/include/host/linux-common/etc_host_info.h
- pal/include/pal/pal.h
- pal/regression/ipv4_parser.c
- pal/regression/ipv6_parser.c
- pal/regression/meson.build
- pal/src/host/linux-common/etc_host_info.c
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux/pal_main.c
- pal/src/pal_main.c
This is a continuation of the issue https://github.com/gramineproject/gramine/issues/689.
From what I can see, most applications use the uname(2) syscall to obtain a current hostname, for example, gethostame.
The /etc/hostname is read during startup, and the sethostname(2) is called. For example, this is done on Ubuntu 20.04 with /etc/init/hostname.conf script.
Because of that we decided not to create a `/etc/hostname` file but just to set the Gramine hostname to the host's hostname.
The Gramine hostname has to be a valid domain. This is a difference from Linux, as Linux accepts any hostname value. That said, Linux doesn't assume that the root user tries to exploit it through hostname, and Gramine should.
This change doesn't address the support of the sethostname(2). The hostname can …
> [LibOS,PAL] Extend extra runtime configuration to include hostname

- Documentation/sgx-intro.rst
KSS stands for Key Separation and Sharing,
a feature added to the SGX hardware and
not yet implemented in Gramine
Signed-off-by: Lavi, Nir <nir.lavi@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/873)
> [docs] Add KSS description to SGX introduction

- libos/src/sys/libos_epoll.c
- libos/test/regression/epoll_test.c
`do_epoll_wait` gathers PAL handles from all epoll items + one PAL handle to prematurely wake up the waiter. The code missed a case where there are no epoll items (so the array should contain only the wakeup handle), which this commit fixes.
Fixes #920
Added a test case
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/928)
> [LibOS] Always allocate a slot for a wakeup handle in `do_epoll_wait`

- meson.build
We have to release 1.3.1 because of one documentation bug (https://github.com/gramineproject/gramine/pull/935) and missing dependencies in some of the packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/939)
> Bump Gramine version to 1.3.1 

- packaging/docker/Dockerfile
Since v1.3 Ubuntu 20.04 has dedicated Gramine package.
Try building docker image
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/947)
> [packaging/docker] Update dockerfile to match post v1.3 repo name

- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-mbedtls/README.md
- CI-Examples/ra-tls-mbedtls/src/server.c
Previously, the server in the `ra-tls-mbedtls` example corrupted the SGX quote (for testing purposes) when it was started with *any* arguments. With this commit, the server recognizes only `--malicious-quote` arg and complains on other arguments. This change prevents users from accidentally corrupting the SGX quote when they mistype something like `gramine-sgx server dcap`.
For the context, see https://github.com/gramineproject/gramine/issues/941.
CI is enough (it tests `make check_epid_fail`). I also tested manually on an EPID machine and on a Azure DCAP machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/943)
> [CI-Examples] Use `--malicious-quote` arg for ra-tls-mbedtls server

- libos/src/libos_rtld.c
- libos/test/regression/scripts/foo.sh
- libos/test/regression/shebang_test_script.sh
Previously, the "load shebang" logic didn't strip trailing spaces, which resulted in additional empty arguments to the interpreter (e.g., `#!/bin/bash ` was interpreted as "start `/bin/bash` with the first argument ` `" -- and Bash failed because it expected the first argument to be the program to run).
Kudos to @svenkata9 for finding this bug. It was found on one Docker image that had such a problematic entrypoint Bash script (with trailing spaces in the shebang line), when trying to graminize this image via GSC.
CI is enough. Modified the `test_212_shebang_test_script` example (the Bash script) to contain trailing spaces.
Without this PR, the modified example fails like this:
```
test_libos.py:244: in test_212_shebang_test_script
stdout, _ = self.run_binary(['shebang_test_script']) …
```
> [LibOS] Strip trailing spaces in the shebang line

- CI-Examples/nginx/README.md
- CI-Examples/nginx/nginx.manifest.template
This PR removes unneeded `/etc/` files from `sgx.allowed_files`.
Also the PR adds `loader.uid` to skip Nginx dropping privileges.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/960)
> [CI-Examples] Harden Nginx example

- CI-Examples/redis/Makefile
- CI-Examples/redis/README.md
- CI-Examples/redis/redis-server.manifest.template
After Gramine v1.3, we have nice features and can finally get rid of insecure manifest options.
This PR removes the following insecure manifest options:
- `loader.insecure__use_cmdline_argv` in favor of `loader.argv`,
- `sgx.allowed_files`, they are not needed at all.
CI is enough. Also tested manually, including on a cloud machine with a public IP and connecting remotely (this was for testing `--protected-mode no`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/954)
> [CI-Examples] Harden Redis example

- libos/test/regression/exec_same.c
This bug was fixed over two years ago by "[Pal/Linux-SGX] Fix race in accessing trusted files hashes list".
Try running the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/965)
> [LibOS/regression] Remove a note about a bug in `exec_same`

- CI-Examples/ra-tls-secret-prov/helper-files/hosts
- CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_minimal/client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template
This PR removes the following insecure manifest options:
- `loader.insecure__use_cmdline_argv` since it is not needed,
- `sgx.allowed_files`, they are not needed at all.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/963)
> [CI-Examples] Harden `ra-tls-secret-prov` example

- CI-Examples/memcached/Makefile
- CI-Examples/memcached/README.md
- CI-Examples/memcached/memcached.manifest.template
This PR removes the following insecure manifest options:
- `loader.insecure__use_cmdline_argv` as we use `loader.uid` now and thus don't need `-u nobody` argument,
- `sgx.allowed_files`, they are not needed at all.
CI and manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/957)
> [CI-Examples] Harden Memcached example

- CI-Examples/busybox/Makefile
- CI-Examples/busybox/README.md
- CI-Examples/busybox/busybox.manifest.template
- CI-Examples/busybox/helper-files/hosts
This PR removes the `sgx.allowed_files` insecure manifest option, since the files there are not needed at all. Also, this commit removes many other superfluous manifest options.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/958)
> [CI-Examples] Harden Busybox example

- CI-Examples/sqlite/.gitignore
- CI-Examples/sqlite/Makefile
- CI-Examples/sqlite/README.md
- CI-Examples/sqlite/manifest.template
This PR removes the following insecure manifest options:
- `loader.insecure__use_cmdline_argv` in favor of `loader.argv`,
- `sgx.allowed_files` in favor of an "encrypted" FS mount.
The database files are now stored under the `db/` directory which is mounted as "encrypted" in Gramine. For the SGX case, the encryption key is MRENCLAVE-based; for non-SGX case, the key is a hardcoded dummy.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/964)
> [CI-Examples] Harden SQLite example

- common/include/linux_socket.h
- libos/src/sys/libos_socket.c
Some applications use `MSG_MORE` flag and fail when they are not supported, such as Pytorch. Source code can be seen in
https://github.com/pytorch/pytorch/blob/614d6f19e3d30cac0d77059e738d1f25d75eb408/torch/csrc/distributed/c10d/Utils.hpp#L559
Ignoring `MSG_MORE` flag in `sendto` syscall is correct semantically for TCP socket and fixes Pytorch workloads that use above `namespace tcputil`.  I don't encounter performance issue.
Fixes #823.
straightforward change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/966)
> [LibOS] Allow and ignore `MSG_MORE` flag for TCP socket in `sendto`

- Documentation/manifest-syntax.rst
- libos/src/fs/etc/fs.c
- pal/include/pal/pal.h
- pal/src/host/linux-common/etc_host_info.c
- pal/src/host/linux-sgx/pal_main.c
This PR build upon the recent feature of domain name extra runtime configuration (aka emulating `/etc/resolv.conf`). In previous PR we emulated only two options: `inet6` and `rotate`.
@dimakuv in review to https://github.com/gramineproject/gramine/pull/889 proposed propagating fallowing options:
* `options edns0`
* `ndots:n`
* `use-vc`
This PR tries to address this request.
* [resolv.conf](https://man7.org/linux/man-pages/man5/resolv.conf.5.html)
* [Resolv GLIBC parser](https://elixir.bootlin.com/glibc/latest/source/resolv/res_init.c#L645)
* [Resolv GLIBC header limits](https://elixir.bootlin.com/glibc/latest/source/resolv/resolv.h#L69)
https://github.com/gramineproject/gramine/issues/689
Check the value of `resolv.conf` with multiple different hosts configuration.
- - -
This change …
> [LibOS,PAL] Extend DNS runtime configuration

- Documentation/Doxyfile-pal
- Documentation/pal/host-abi.rst
- common/include/iovec.h
- common/include/linux_socket.h
- libos/src/net/ip.c
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/regression/send_handle.c
- pal/src/host/linux-sgx/pal_linux_types.h
- pal/src/host/linux-sgx/pal_sockets.c
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_sockets.c
- pal/src/host/linux/pal_streams.c
- pal/src/host/skeleton/pal_sockets.c
- pal/src/pal_sockets.c
This struct was essentially `struct iovec` from Linux and it's usage required some otherwise unneeded `malloc()` + `free()`, which became a performance bottleneck in some cases.
This commit also removes erroneous include of `sys/socket.h`, which also got in the way of these changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/946)
> [LibOS,PAL] Remove `struct pal_iovec`

- libos/src/sys/libos_exec.c
- libos/test/regression/exec_null.c
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Add support for execv with argv = NULL.
Run added LibOS regression test case.
Resolves: https://github.com/gramineproject/gramine/issues/794
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/979)
> [LibOS] Add support for execv with argv = NULL

- libos/src/bookkeep/libos_thread.c
- libos/src/sys/libos_exit.c
- libos/src/sys/libos_futex.c
See commit messages.
Fixes #969
Try the following patch with and without this PR:
```diff
diff --git a/libos/src/sys/libos_futex.c b/libos/src/sys/libos_futex.c
index 114ef2e5..712b5ff8 100644
--- a/libos/src/sys/libos_futex.c
+++ b/libos/src/sys/libos_futex.c
@@ -898,9 +898,9 @@ static bool handle_futex_death(uint32_t* uaddr) {
* Returns 0 on success, negative value on error.
*/
static int fetch_robust_entry(struct robust_list** entry, struct robust_list** head) {
-    if (!is_user_memory_readable(head, sizeof(*head))) {
-        return -EFAULT;
-    }
+    //if (!is_user_memory_readable(head, sizeof(*head))) {
+    //    return -EFAULT;
+    //}
*entry = *head;
return 0;
@@ -926,9 +926,9 @@ void release_robust_list(struct robust_list_head* head) {
return;
}
-    if …
```
> [LibOS] Robust futexes fixes

- CI-Examples/python/python.manifest.template
- python/graminelibos/gen_jinja_env.py
Because of differences between distributions, specifically filesystem layout and content of `sys.path`, it's hard to write a manifest that would run Python apps correctly on different distributions. This is an attempt to fix this.
This PR supersedes ~#977 and~ #978.
Closes #978.
`CI-Examples/python` is modified — run in CI or manually
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/999)
> gramine-manifest: API to list python paths

- pal/src/host/linux-sgx/meson.build
- tools/sgx/common/meson.build
- tools/sgx/ra-tls/meson.build
Gramine RA-TLS and Secret Provisioning libraries actually only need `sgx_arch.h` and `sgx_attest.h` from `PAL/Linux-SGX` (for some SGX-hardware-specific structs). However, `sgx_inc` which contains unnecessary includes e.g., `common_inc` is currently used for them.
This patch removes `sgx_inc` from RA-TLS and Secret Provisioning libs' include dependencies and includes only the needed from `PAL/Linux-SGX`.
Resolves https://github.com/gramineproject/gramine/issues/876.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1008)
> [tools/sgx] Remove unneeded include deps for RA-TLS and secret-prov libs

- libos/src/libos_parser.c
These removed flags are used only in compat syscalls, which Gramine does not implement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1015)
> [LibOS] Remove unneeded fcntl flags from `libos_parser.c`

- .ci/lib/config-docker.jenkinsfile
- .ci/lib/stage-build-sgx.jenkinsfile
- Documentation/devel/building.rst
- Documentation/sgx-intro.rst
- meson.build
- meson_options.txt
- pal/src/host/linux-sgx/generated_offsets.c
- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/host_platform.c
- pal/src/host/linux-sgx/host_sgx_driver.h.in
- pal/src/host/linux-sgx/meson.build
AFAIK all of these (DCAP <= 1.6, super-old OOT version, gsgx) are not being used by anyone since long time ago.
CI should be enough, but if you have some unusual config then you may want to try it yourself.
Please verify that I removed everything, there may be more leftovers I missed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/997)
> [Pal/Linux-SGX] Drop support for old SGX drivers

- common/include/linux_socket.h
- libos/src/net/ip.c
- libos/test/regression/getsockopt.c
- libos/test/regression/test_libos.py
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_sockets.c
- pal/src/host/linux/pal_host.h
- pal/src/host/linux/pal_sockets.c
Gramine currently doesn't support set (via `setsockopt()`) or get (via `getsockopt()`) `TCP_KEEPIDLE`, `TCP_KEEPINTVL` and `TCP_KEEPCNT` socket options. This may lead to some applications failures when they try to set these socket options but find out they are unsupported.
This patch implements support for the above TCP socket options.
Resolves https://github.com/gramineproject/gramine/issues/902.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1007)
> [LibOS,PAL] Support TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT socket opts

- common/include/api.h
- common/include/path_utils.h
- common/include/string_utils.h
- common/src/meson.build
- common/src/path_utils.c
- common/src/string/atoi.c
- common/src/string/util.c
- common/src/string_utils.c
- libos/src/fs/libos_fs.c
- libos/src/fs/libos_fs_encrypted.c
- pal/regression/normalize_path.c
- pal/src/host/linux-sgx/enclave_framework.c
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux/pal_files.c
Currently, all `common/` source files are supplied via a single `common_dep`. However in some cases, we may only want to reuse the part of the utility functions in `common/` without importing the other part of Gramine-supplied mini-libc (which might lead to colliding issues).
This patch separates `common/` into several dependencies for more flexible usage.
The original requirement was from https://github.com/gramineproject/gramine/pull/937. For details, pls kindly refer to that PR thread.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1002)
> [common] Split `common_dep` into several dependencies

- libos/include/libos_fs_pseudo.h
- libos/include/libos_vma.h
- libos/src/bookkeep/libos_vma.c
- libos/src/fs/proc/fs.c
- libos/src/fs/proc/thread.c
The `/proc/[self-pid]/statm` and `/proc/[self-pid]/stat` files are required by the `psutil` module of Python. 
In most cases, workloads that use this module don't really care about the values in them. The mean of each value are listed in `man proc`.
This PR emulate `stat` and `statm` only in `/proc/[self-pid]`. And only a few values are filled. Dummy values in correct format are enough. 
Resolves #967
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1024)
> [LibOS] Add `/proc/[pid]/stat` and `/proc/[pid]/statm` pseudo-file

- CI-Examples/python/python.manifest.template
Signed-off-by: TejaswineeL <tejaswinee.ramdas.langhe@intel.com>
-test_numpy.py executable imports a package called Numpy
-While executing test_numpy.py with SGX, it demands an extra space to load the package to enclave.
-Increase the enclave size to 1G and internal pal memory size to 128M (for manifest). This resolves the insufficient space issue.
-OMP_num_threads limits the number of Numpy threads creation.
-During runtime, SGX requests for python local installation path and in turn the Numpy package location. 
-Add the relevant path in the SGX trusted files.
-run test-numpy.py file from the python examples with "gramine-sgx ./python scripts/test-numpy.py"
-the .py file should successfully execute by importing numpy package with SGX
- - - …
> Update the manifest defaults for importing numpy package

- subprojects/packagefiles/mbedtls/meson.build
The mbedtls_gramine package contains three static libraries: libmbedcrypto_gramine, libmbedtls_gramine, libmbedx509_gramine. The latter two libs depend on the first one, so the linking order is important. Previously it was incorrectly reported as `-lmbedcrypto_gramine -lmbedtls_gramine -lmbedx509_gramine`. This commit adds `-Wl,--start-group ... -Wl,--end-group` options to effectively ignore the ordering of these three libs.
Fixes #1046.
I guess try on RHEL 8.6 server with some specific GCC version...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1048)
> [mbedtls] Fix link order in `pkg-config --libs mbedtls_gramine`

- CI-Examples/nginx/Makefile
Nginx version 1.16.1 is not compatible with openssl version available for Ubuntu 22.04. Nginx make kept failing with deprecated errors.
So, in order to enable Nginx for Ubuntu 22.04 also, we need to upgrade nginx version.
Signed-off-by: Anjali Rai <anjali.rai@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1047)
> [CI-Examples] Update nginx version to 1.22.0

- tools/sgx/common/meson.build
- tools/sgx/common/pf_util.c
- tools/sgx/pf_crypt/pf_crypt.c
- tools/sgx/pf_tamper/pf_tamper.c
Protected Files common logic requires file paths to be normalized, otherwise filename comparison (done to prevent file-swap attacks) fails. E.g., `gramine-sgx-pf-crypt encrypt ... -o ./encrypted-file` would previously save the path verbatim (`./encrypted-file`) which would confuse Gramine that expects a normalized path.
Fixes #923.
Play with `gramine-sgx-pf-crypt` tool like this:
```
gramine-sgx-pf-crypt encrypt -w key.key -i input.file -o ./somedir/.././encrypted.file
gramine-sgx-pf-crypt decrypt -w key.key -i ./gramine/./../encrypted.file -o ./somedir/../decrypted.file -V
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/937)
> [tools/pf_crypt] Normalize paths during PF encrypt/decrypt

- CI-Examples/python/Makefile
- CI-Examples/python/README.md
- CI-Examples/python/run-tests.sh
- CI-Examples/python/scripts/sgx-quote.py
- CI-Examples/python/scripts/sgx-report.py
- libos/src/fs/dev/attestation.c
Previously, SGX local attestation files like `user_report_data` and `report` were exposed only if `sgx.remote_attestation` type was "epid" or "dcap". This is incorrect -- local attestation can be done completely independent of the remote-attestation scheme.
This PR always exposes all `/dev/attestation/` pseudo-files now, except for `quote` which is only exposed when `sgx.remote_attestation` is set.
See https://github.com/gramineproject/gramine/discussions/1055
A Python example for SGX reports is added and tested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1057)
> [LibOS,CI-Examples] Always expose SGX local attestation files

- libos/src/sys/libos_mmap.c
- libos/test/regression/mprotect_prot_growsdown.c
If `mprotect` is called with `PROT_GROWSDOWN` flag, it should apply the change to the whole mapping. Old code correctly adjusted beginning of the changed region in such case, but used original length.
We had a test for this, but it was faulty... Fixed now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1060)
> [LibOS] Fix length calculation in `mprotect` with `PROT_GROWSDOWN`

- .ci/lib/stage-build-nosgx.jenkinsfile
- .ci/lib/stage-build-sgx.jenkinsfile
- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- CI-Examples/ra-tls-secret-prov/Makefile
- Documentation/devel/building.rst
- meson.build
- subprojects/.gitignore
- subprojects/curl-7.84.0.wrap
- subprojects/packagefiles/curl-7.84.0/compile.sh
- subprojects/packagefiles/curl-7.84.0/meson.build
- subprojects/packagefiles/mbedtls/compile-curl.sh
- subprojects/packagefiles/mbedtls/meson.build
- tools/sgx/common/meson.build
Previously, we built `libsgx_util` as a shared library which is linked into RA-TLS, Secret Provisioning libraries and some other tools.
This patch
- builds `libsgx_util` into a static library
- builds and minimizes `curl` into a static library (leveraging `mbedtls` as the TLS backend)
- links all dependencies of `tools/sgx` statically to avoid pulling in a lot of dependencies.
See https://github.com/gramineproject/gramine/pull/740 and https://github.com/gramineproject/gramine/pull/730 for some previous discussions.
**BEFORE**
```
kailun@kailun-NUC:~/workspace/intel/upstream/gramine/build/tools/sgx/ias-request$ ldd gramine-sgx-ias-request
linux-vdso.so.1 (0x00007ffd21e84000)
libsgx_util.so => /home/kailun/workspace/intel/upstream/gramine/build/tools/sgx/ias-request/./../common/libsgx_util.s …
```
> [tools/sgx,curl,Docs] Link all dependencies of `tools/sgx` statically

- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- Documentation/devel/building.rst
- Documentation/requirements.txt
- libos/test/regression/attestation.manifest.template
- libos/test/regression/attestation_deprecated_syntax.manifest.template
- libos/test/regression/device_passthrough.manifest.template
- libos/test/regression/file_check_policy_allow_all_but_log.manifest.template
- libos/test/regression/file_check_policy_strict.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- libos/test/regression/toml_parsing.manifest.template
- python/gramine-gen-depend
- python/gramine-manifest
- python/gramine-sgx-sign
- python/graminelibos/manifest.py
- python/graminelibos/util_tests.py
`toml` Python library (for parsing and dumping TOML files) is buggy and doesn't support the full spec of TOML 1.0.0. This PR replaces it with more robust `tomli` (for parsing) and `tomli-w` (for dumping).
Useful links:
- https://github.com/uiri/toml/issues/404
- https://github.com/hukkin/tomli
- https://github.com/hukkin/tomli-w
- https://pypi.org/project/tomli/
- https://pypi.org/project/tomli-w/
- https://packages.ubuntu.com/jammy/python3-tomli
- https://packages.ubuntu.com/jammy/python3-tomli-w
Closes #990. Fixes #968.
See also https://github.com/gramineproject/gsc/pull/101.
CI. One LibOS test was modified a bit to test more TOML cases.
- - - …
> [python] Move from `toml` library to `tomli` + `tomli-w`

- common/include/linux_socket.h
- libos/src/net/ip.c
- libos/test/regression/getsockopt.c
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_sockets.c
- pal/src/host/linux/pal_host.h
- pal/src/host/linux/pal_sockets.c
Previously, Gramine didn't support setting (via `setsockopt()`) or getting (via `getsockopt()`) `TCP_USER_TIMEOUT` socket option. This could lead to some applications failures (in particular, libpq) when they tried to get/set this socket option but found out it's unsupported.
This is requested by application devs that have to use `libpq` library. The offending code is here: https://github.com/postgres/postgres/blob/3d0c95bc8920f51f7d7685c622c9a75f59cf322f/src/backend/libpq/pqcomm.c#L1872-L1915
This PR is based on a prevoius similar PR: https://github.com/gramineproject/gramine/commit/bd977417363224906aba1d28ce14329ae37163c6
How Linux does it (very simply):
- https://elixir.bootlin.com/linux/latest/source/tools/include/uapi/linux/tcp.h#L108
- …
> [LibOS,PAL] Support TCP_USER_TIMEOUT socket opt

- Documentation/devel/building.rst
- meson.build
- pal/src/host/linux-sgx/generated_offsets.c
- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/host_sgx_driver.h.in
- python/graminelibos/sgx_get_token.py
Continuation of https://github.com/gramineproject/gramine/pull/997, where we planned to move resolving of DCAP/upstream driver paths to the runtime, so that we can have a single build supporting both the upstreamed driver and the legacy DCAP one.
Same as with https://github.com/gramineproject/gramine/pull/997, please run on different drivers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1027)
> [PAL/Linux-SGX] Rework SGX driver path resolving

- common/include/linux_socket.h
- libos/include/libos_handle.h
- libos/src/net/ip.c
- libos/src/sys/libos_socket.c
- libos/test/regression/tcp_ipv6_v6only.c
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_sockets.c
- pal/src/host/linux/pal_host.h
- pal/src/host/linux/pal_sockets.c
This PR adds support for the SO_REUSEPORT option in Gramine.
This PR is related to issues #238,  #361 and #763.
A regression test has been added to the `tcp_ipv6_v6only.c` file. Please let me know if other tests are needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1031)
> Implement SO_REUSEPORT support

- libos/src/sys/libos_exec.c
It's legal according to `PalVirtualMemoryFree` semantics, but is pointless
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1076)
> [LibOS] Do not try to free unmapped memory on execve

- libos/include/libos_fs.h
- libos/include/libos_fs_mem.h
- libos/include/libos_internal.h
- libos/include/libos_table.h
- libos/src/bookkeep/libos_signal.c
- libos/src/fs/libos_fs_mem.c
- libos/src/fs/libos_fs_pseudo.c
- libos/src/fs/libos_fs_util.c
- libos/src/sys/libos_poll.c
- libos/test/ltp/ltp.cfg
- libos/test/regression/poll.c
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_object.c
- pal/src/host/linux/pal_object.c
- pal/src/pal_object.c
Fixed some bugs, hopefully the code easier to manage too now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1067)
> [LibOS] Clean up `select` and `poll` implementations

- CI-Examples/ra-tls-mbedtls/Makefile
- debian/gramine.install
- subprojects/packagefiles/mbedtls/meson.build
Previously, Gramine didn't install the header files for the `mbedtls_gramine` package. This required e.g. the `ra-tls-mbedtls` example to download mbedTLS and use its headers. This PR copies the header files such that they can be accessed via pkg-config, and `ra-tls-mbedtls` example uses it now.
This PR is part of solving #1071.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1106)
> [mbedtls] Use `pkg-config --cflags mbedtls_gramine`

- CI-Examples/bash/Makefile
- CI-Examples/blender/Makefile
- CI-Examples/busybox/Makefile
- CI-Examples/helloworld/Makefile
- CI-Examples/lighttpd/Makefile
- CI-Examples/memcached/Makefile
- CI-Examples/nginx/Makefile
- CI-Examples/python/Makefile
- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-secret-prov/Makefile
- CI-Examples/redis/Makefile
- CI-Examples/rust/Makefile
- CI-Examples/sqlite/Makefile
- Documentation/manpages/gramine-sgx-get-token.rst
- Documentation/manpages/gramine.rst
- tools/gramine.in
- tools/meson.build
There's no EINITTOKEN on upstream driver (nor DCAP), and most people use that driver (it is/will be the only packaged flavour). It's bad UX to require them to do `gramine-sgx-get-token` for nothing (like, 384 * `\0`).
This PR is the first of series of two. It changes UX (`gramine-sgx-get-token` gets called automatically), but doesn't change behaviour of loader (the `.token` file is still required).
Run `gramine-sgx` without doing `gramine-sgx-get-token` first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1093)
> Do `gramine-sgx-get-token` automatically

- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
Liberally submit Jenkins-Debug-* pipelines in CI, none should time out on blender.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1117)
> [CI] Expand timeout for blender example in CI

- libos/src/sys/libos_poll.c
- pal/src/host/linux-sgx/pal_object.c
- pal/src/host/linux/pal_object.c
Current implementation of poll syscall uses multiple malloc and free. When the number of threads calling poll is high, the lock contention limits the application performance. This PR tries to use stack space when the space being allocated is small, and reduces such lock contention.
Run the MySQL example on one server and use Sysbench to test it from another. When the number of threads in Sysbench is set to 128, the result TPS is >50% better than the original code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1051)
> [LibOS,PAL] Reduce lock contention caused by malloc() in poll

- CONTRIBUTING.rst
As discussed in the Gramine core meeting, we'd like to:
- split the list of maintainers into active and inactive,
- amend the rules slightly so that only active maintainers vote,
- add @woju as the active maintainer.
We need to agree and vote on these changes. The comments/reviews in this PR will serve as the voting procedure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1095)
> [Docs] CONTRIBUTING.rst: Update the list of maintainers

- README.rst
They stopped to operate recently and we had to move to our own hosting.
For more info see the announcement at https://fosshost.org/.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1130)
> [Docs] Remove fosshost.org mention from README.rst

- .ci/lib/stage-test-sgx.jenkinsfile
- CI-Examples/python/run-tests.sh
Workloads take 2x-5x times to execute with EDMM than non-EDMM's, and thus require larger timeouts, hence increasing the wait time for server.
Signed-off-by: Anjali Rai <anjali.rai@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1113)
> [CI-Examples] Increase server wait time to 300

- .ci/linux-sgx-edmm.jenkinsfile
- libos/test/regression/avx.c
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/src/host/linux-sgx/host_framework.c
- python/graminelibos/regression.py
Commits https://github.com/gramineproject/gramine/commit/e73da5e2a0b77c5ea88585bb52a75b9d4e65c55b and https://github.com/gramineproject/gramine/commit/95d49502db1dd816fca0266fefb12c185269e7d3 removed/deprecated the call to `gramine-sgx-get-token` Python script on non-OOT platforms (i.e., on machines with SGX FLC).
However, that Python script doesn't only fetch the token from AESM but also sets optional SGX features if available on current machine, see `sgx_get_token.py:get_optional_sgx_features()`. With the two commits above, Gramine stopped setting these optional SGX features, **making some apps slow** and **some apps faililing explicitly** on e.g. AVX instructions (because their use was not enabled in XFRM attrs).
This commit fixes this bug, by reproducing …
> [PAL/Linux-SGX] Set optional SGX features if available on machine

- scripts/gitignore-check-files
Starting from Git v2.32.0, `git ls-files -i` must be used with either `-o` or `-c` (this was a bug in Git, fixed in commit "ls-files: error out on -i unless -o or -c are specified").
See https://github.com/git/git/commit/b338e9f668737e08201c990450b8c3d744f63162 for details.
This was detected on my PR https://github.com/gramineproject/gramine/pull/1032 that uses Ubuntu 22.04 Docker, which has Git v2.34.
https://github.com/gramineproject/gramine/pull/1032 fails without this trick.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1137)
> [CI] Fix `git ls-files` command

- .ci/debian11.dockerfile
- .ci/lib/stage-build-sgx.jenkinsfile
- .ci/lib/stage-clean-check.jenkinsfile
- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
As discussed in some other PRs and offline, `leeroy` seems to be totally useless, and we don't need `/opt/intel` directory -- instead we can just use a relative dir.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1131)
> [CI] Remove `leeroy` user and `/opt/intel` dir

- debian/gramine.install
1) CI must pass (esp. no errors from `dh_missing` in `pkg-deb-debian11` pipeline)
2) Get packages from CI and try to install — there should be no error like this:
```
Selecting previously unselected package gramine-ratls-dcap.
Preparing to unpack .../25-gramine-ratls-dcap_1.3.1~post_amd64.deb ...
Unpacking gramine-ratls-dcap (1.3.1~post) ...
dpkg: error processing archive /tmp/apt-dpkg-install-Qg3vBm/25-gramine-ratls-dcap_1.3.1~post_amd64.deb (--unpack):
trying to overwrite '/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/libra_tls_verify_dcap.so', which is also in package gramine 1.3.1~post
Selecting previously unselected package gramine-ratls-epid.
Preparing to unpack .../26-gramine-ratls-epid_1.3.1~post_amd64.deb ...
Unpacking gramine-ratls-epid (1.3.1~post) ...
dpkg: error processing …
```
> Fix conflicting files in .deb packages

- .ci/linux-direct-sanitizers.jenkinsfile
- .ci/linux-direct-ubuntu18.04-gcc-debug.jenkinsfile
- .ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
- .ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile
- .ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- .ci/linux-sgx-edmm.jenkinsfile
- .ci/linux-sgx-sanitizers.jenkinsfile
- .ci/linux-sgx-ubuntu18.04-gcc-release-apps.jenkinsfile
- .ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- .ci/linux-sgx-ubuntu20.04-gcc-release-apps.jenkinsfile
- .ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- common/include/arch/x86_64/cpu.h
- libos/src/arch/x86_64/libos_cpuid.c
- libos/test/regression/cpuid.c
- libos/test/regression/test_libos.py
- pal/src/arch/x86_64/pal_cpuid.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/enclave_ocalls.h
- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/pal_misc.c
- pal/src/host/linux/arch/x86_64/pal_arch_misc.c
- pal/src/host/linux/pal_linux.h
- pal/src/host/linux/pal_main.c
- subprojects/packagefiles/mbedtls/compile-curl.sh
- subprojects/packagefiles/mbedtls/compile.sh
- subprojects/packagefiles/mbedtls/enforce-aes-ni.patch
*This PR fixes a security issue*
These CPU features are required for correct and secure use of Gramine:
- XSAVE is used internally by Gramine,
- AES-NI and RDRAND are required, otherwise some crypto libraries (e.g. mbedtls) silently switch to side-channel-prone software implementations of crypto algorithms.
This PR ensures that we always have them enabled and report as such to the application running under Linux-SGX PAL. Additionally, it patches the mbedtls version we ship to refuse to ever use non-AES-NI (i.e. vulnerable) AES implementation.
Kudos to Corentin Lauverjat from Mithril Security for reporting the bug!
p.s. We don't have to fix `/proc/cpuinfo`, as it already gets the flags from CPUID. See: https://github.com/gramineproject/gramine/blob/1aab0f79729f0c8a4852150a985be527991a06bc/l …
> [PAL/Linux-SGX] Enforce AES-NI, XSAVE and RDRAND

- Documentation/manifest-syntax.rst
- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_main.c
Fixes #1148
Some references:
- https://lore.kernel.org/lkml/6f8653a000c0fd670ea19337d1c744b28127be54.1644274683.git.reinette.chatre@intel.com/ (search for "Ensure kernel supports ...")
- https://lore.kernel.org/lkml/165721846417.15455.4074908162801839460.tip-bot2@tip-bot2/T/ (search for "sgx_ioc_sgx2_ready")
- https://patchwork.kernel.org/project/intel-sgx/patch/d787827dbfca6b3210ac3e432e3ac1202727e786.1616136308.git.kai.huang@intel.com/
- https://elixir.bootlin.com/linux/latest/source/arch/x86/kernel/cpu/sgx/ioctl.c#L1257
- Intel SDM, Table 3-8, CPUID leaf `0x12`.
Manually on different machines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1149)
> [PAL/Linux-SGX] Print error message if no EDMM support

- pal/regression/memory.c
- pal/regression/test_pal.py
This increases test coverage for the EDMM SGX feature.
This is another approach instead of #1120: we just augment the already-existing PAL test `memory.c` instead of creating a new one.
~~Closes #1120.~~
CI and manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1146)
> [tests] Add "execute" subtest to `memory` test

- Documentation/cloud-deployment.rst
- Documentation/devel/building.rst
- Documentation/devel/coding-style.rst
- Documentation/devel/packaging.rst
- Documentation/quickstart.rst
I'd prefer this PR be merged after #1102, because although it's unrelated, I think the discussion if we support RHEL 9 et.al. should be concluded before we agree on the exact language about installing on RHEL and derivatives. Regardless of that section's intro text, the CLI commands will be the same.
Just before release there will be packages available in `unstable-` repositories. I'll change this text when this happens. Then you should go though all the new install instructions, but for our repos prefix the names with `unstable-` (like, instead of `https://packages.gramineproject.io jammy`, write `https://packages.gramineproject.io unstable-jammy`) and see if they work. Obviously the packages from stable repos won't be available until after the release.
- - - …
> [Docs] Edit build and install docs for upcoming 1.4 release

- packaging/docker/Dockerfile
Replace usage of `apt` with `apt-get`. The `apt` tool doesn't have a stable CLI interface, and it's not recommended to use it in Dockerfile.
Replace deprecated `apt-key` with `signed-by`.
As we are here - drop the `packaging` directory, as other packaging scripts (like `debian`) don't use it.
```
docker build .
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1181)
> [docker] Drop deprecated/unstable directives

- Documentation/manifest-syntax.rst
- libos/src/sys/libos_clone.c
- libos/test/regression/fork_disallowed.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Some apps (in particular Python) tend to spawn helper subprocesses. There is no simple way to disable such functionality in the apps themselves, so we introduce a new manifest option to force apps to use only the main process and fall back to no-subprocesses logic.
~~**This is a draft for quick testing! After we'll test that it helps sometimes, we can have discussions on the terribleness of this approach.**~~ Based on customer feedback, this looks like useful feature, so I mark this PR as ready-for-review.
This PR literally disables `fork/vfork/clone` syscalls used to spawn subprocesses.
Tested some Python workloads; they stopped spawning child enclaves and still behave correctly.
Here is an example of Flask:
- Install Flask: `pip3 install Flask` (installs in HOME dir of user)
- Improve …
> [LibOS] Add `sys.disallow_subprocesses` manifest option

- .ci/pkg-rpm-almalinux9.jenkinsfile
A new version of glibc uses `clone3` to create a thread, to resolve a hostname. almalinux9 uses a new version of this library. CI agents need to support `clone3 syscall` to test Gramine on this distribution.
The `clone3` syscall was introduced in the Linux kernel 5.3. Besides the kernel also userland utilities have to support it, like docker to create valid seccomp rules.
To indicate full support of this syscall new label `clone3` has been introduced.
CI should be sufficient.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1199)
> [CI] Run almalinux9 on hosts that support `clone3`

- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-mbedtls/src/client.c
- CI-Examples/ra-tls-mbedtls/src/server.c
- CI-Examples/ra-tls-secret-prov/Makefile
- debian/gramine.install
- gramine.spec
- pal/src/host/linux-sgx/meson.build
- tools/sgx/ra-tls/meson.build
- tools/sgx/ra-tls/ra_tls.h
- tools/sgx/ra-tls/ra_tls.map
- tools/sgx/ra-tls/ra_tls_attest.c
- tools/sgx/ra-tls/ra_tls_common.h
- tools/sgx/ra-tls/ra_tls_verify_common.c
- tools/sgx/ra-tls/ra_tls_verify_dcap.c
- tools/sgx/ra-tls/ra_tls_verify_epid.c
- tools/sgx/ra-tls/secret_prov.h
- tools/sgx/ra-tls/secret_prov.map
- tools/sgx/ra-tls/secret_prov_attest.c
- tools/sgx/ra-tls/secret_prov_common.h
- tools/sgx/ra-tls/secret_prov_verify.c
This PR splits RA-TLS and SecretProv libs in a more fine-grained manner, suitable for writing external plugins (e.g. with Microsoft Azure Attestation flows). This PR also installs corresponding header files and pkg-config files. Finally, this PR fixes a bug with too-many exported symbols from these libs.
For more context on this, see https://github.com/gramineproject/gramine/issues/1071.
Fixes #1182 (by making the `abort` symbol local)
The examples `ra-tls-mbedtls` and `ra-tls-secret-prov` (run in CI) are updated to reflect these changes.
To aid the review process, let me show some logs how things look with this PR.
- Installed includes:
```
~/gramineproject/gramine/built/include$ tree
.
└── gramine
├── mbedtls
│   ├── aes.h
│   ├── ...
├── psa
│   ├── crypto_builtin_composites.h
│   ├── …
```
> [tools/sgx] Install RA-TLS and SecretProv libs properly

- common/include/linux_socket.h
- libos/include/libos_socket.h
- libos/src/fs/socket/fs.c
- libos/src/net/ip.c
- libos/src/net/unix.c
- libos/src/sys/libos_socket.c
- libos/test/ltp/ltp.cfg
- libos/test/regression/meson.build
- libos/test/regression/tcp_ancillary.c
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Previously, Gramine returned `-ENOSYS` on `recvmsg()`/`sendmsg()` and similar syscalls if it detected the use of `struct msghdr` ancillary data (`msg_control` field). This PR is the first step in adding proper ancillary data support.
Currently no ancillary data type is truly supported:
- on `sendmsg()`:
- unknown/unsupported types force an error,
- SCM_RIGHTS/SCM_CREDENTIALS are ignored in TCP/UDP sockets;
- on `recvmsg()`: `msg_controllen` is set to zero to indicate there is no ancillary data added to the received network packet.
I added a LibOS regression test + I disabled one misbehaving LTP test.
One can try this example: https://github.com/gramineproject/examples/pull/57. Without this PR, it doesn't work properly (see test 2 in the README there).
- - - …
> [LibOS] Add dummy ancillary data support for sockets

- libos/src/sys/libos_getcwd.c
- libos/src/sys/libos_mmap.c
- libos/src/sys/libos_open.c
- libos/src/sys/libos_sched.c
- libos/src/sys/libos_wait.c
- libos/src/sys/libos_wrappers.c
This PR fixes a bunch of unrelated checks which were missing from various syscalls. These cases were found by Jaewon Hur using an adapted version of syzkaller, thanks!
Just for the record: none of these bugs is security related, because both sides of the emulated syscall interface are in the same security domain.
See each commit for the specific case where it failed. No tests added to CI, as all of the cases were adversarial and shouldn't be possible in normal apps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1211)
> Fix a bunch of syscall arguments checking

- .ci/ubuntu20.04.dockerfile
- debian/control
- gramine.spec
- meson.build
- subprojects/packagefiles/cJSON/meson.build
- tools/sgx/common/ias.c
- tools/sgx/ra-tls/ra_tls_common.h
- tools/sgx/ra-tls/ra_tls_verify_common.c
This PR is a result of me porting MAA from in-core-Gramine (#652) to being a plugin in [contrib repo](https://github.com/gramineproject/contrib).
The previous PR (#1114) created the basis for writing such plugins. However, I missed a couple bugs that prevent me from enabling MAA as a plugin. This PR fixes all bugs that I found:
- [tools/sgx] Expose `find_oid_in_cert_extensions()` in RA-TLS common API. Previously, function `find_oid()` was hidden in RA-TLS. However, some plugins (e.g. Microsoft Azure Attestation) would benefit from this function. So let's expose it and give a more specific name.
- ~~[meson] Install curl's headers and static lib as part of Gramine. Gramine uses a specially built minimized static version of curl. This version should be available for plugins of Gramine (in …
> [tools/sgx,meson,packaging] Bug fixes for RA-TLS plugins

- CI-Examples/ra-tls-mbedtls/src/client.c
- tools/sgx/common/ias.c
- tools/sgx/common/ias.h
- tools/sgx/ra-tls/ra_tls.h
- tools/sgx/ra-tls/ra_tls.map
- tools/sgx/ra-tls/ra_tls_verify_common.c
- tools/sgx/ra-tls/ra_tls_verify_dcap.c
- tools/sgx/ra-tls/ra_tls_verify_epid.c
- tools/sgx/ra-tls/secret_prov_verify.c
- tools/sgx/verify-ias-report/verify_ias_report.c
Previously, RA-TLS hid the details of errors in a dull and uninformative way. This was due to that `ra_tls_verify_callback()` is an mbedtls-adhering callback function, and we cannot simply return a non-mbedtls error code as a ret value.
This patch introduces `ra_tls_verify_callback_args` and a new RA-TLS API `ra_tls_verify_callback_extended_der()` to unhide the detailed error information (e.g. the original SGX-attestation-verification error code) from RA-TLS.
Resolves https://github.com/gramineproject/gramine/issues/1209.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1215)
> [tools/sgx,CI-Examples] Expose RA-TLS verification error details via callback args

- libos/src/fs/libos_dcache.c
It was removed in 29f127542a4d81a8b461f05a4b36344d89bed3fa.
Build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1240)
> [LibOS] Drop leftovers of old macro

- Documentation/manifest-syntax.rst
- Documentation/performance.rst
- pal/src/host/linux-sgx/enclave_api.h
- pal/src/host/linux-sgx/enclave_framework.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/pal_events.c
- pal/src/host/linux-sgx/pal_host.h
A malicious OS could map MMIO memory into the untrusted memory space of an enclave application (which can be used for e.g. parameter passing to/from ECALLs and OCALLs, or any external buffers that an enclave might use to communicate with its application). Then when the enclave writes to this memory, it could unintentionally propagate the stale (secret) data in its core fill buffers into the uncore, where it could later be extracted by malicious software.
Naturally aligned 8-byte writes are not affected by this vulnerability, so as SW mitigation, this commit makes all untrusted memory writes 8-byte wide and naturally aligned.
There is a side effect introduced to the Exitless (aka RPC-threads aka Switchless) feature by the fix of CVE-2022-21233 aka INTEL-SA-00657, which marks the feature as …
> [PAL/Linux-SGX] Mitigate CVE-2022-21166 aka INTEL-SA-00615

- libos/src/fs/libos_fs_pseudo.c
- libos/test/regression/meson.build
- libos/test/regression/open_file.c
- libos/test/regression/shadow_pseudo_fs.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
`inode` in `data` field keep a specific file system data. In the case of pseudo fs it is a `pseudo_node`. However, when a lookup is done, the `dentry` might not be fully initialized. During mount, we are doing a lookup using [do_path_lookupat](https://github.com/gramineproject/gramine/blob/634d0392c3acec724dad5a6af8e6305f166eca57/libos/src/fs/libos_namei.c#L266):
```c
struct lookup lookup = {
.flags = flags,
.name = name,
.has_slash = has_slash,
.dent = dent,
.link_depth = link_depth,
};
/* Main part of the algorithm. Repeatedly call `lookup_enter_dentry`, then `lookup_advance`,
* until we have finished the path. */
ret = lookup_enter_dentry(&lookup);
if (ret < 0)
goto err;
while (*lookup.name != '\0') {
ret = lookup_advance(&lookup);
if (ret < 0)
goto err;
ret = …
```
> [LibOS] Fix NULL pointer dereference in pseudo fs

- libos/src/fs/libos_fs_pseudo.c
- libos/test/regression/proc_cpuinfo.c
- libos/test/regression/test_libos.py
Pseudo-files under `/dev`, `/proc` and `/sys` should not be removable.
This was noticed by @mkow in #1249.
Added a quick sub-test in one of the LibOS regression tests. Also you can try manually via e.g. Busybox example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1266)
> [LibOS] Don't allow removal of pseudo-files

- libos/src/sys/libos_exit.c
This change is to cover a corner case of a non-main thread performing `execve()`. Linux does the following: the main (leader) thread is terminated, and the non-main thread assumes its identity: https://elixir.bootlin.com/linux/v6.0/source/fs/exec.c#L1078
Before this PR, Gramine simply terminated the main thread. This led to the process being marked as a zombie (even though the non-main thread runs correctly and responds to signals). This in turn confused tools like `docker kill`, which couldn't find the Gramine process anymore.
This PR fixes this corner case. Gramine can't do as Linux because there is no way to ask the host OS to "rewire" the identity of one thread to the other thread. Thus we introduce a workaround of keeping alive (but in a "parked" state) the main thread -- it sleeps …
> [LibOS] Keep main thread alive if it's not the last one

- libos/test/regression/devfs.c
- libos/test/regression/test_libos.py
This was fixed after the pseudo filesystem refactoring so that we can re-enable the test now.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1282)
> [tests] Re-enable test for writing to `/dev/stdout`

- pal/src/host/linux-sgx/host_profile.c
After enabling profile by `sgx.profile.enable = "main"` , we'll see the following error log
```
(libos_debug.c:121:append_r_debug) [P1:T1:helloworld] debug: adding file:[vdso_libos] at 0xf816d95000
(host_profile.c:327:sgx_profile_report_elf) error: sgx_profile_report_elf([vdso_libos]): realpath failed
```
It's also reported in https://github.com/gramineproject/gramine/issues/853#issuecomment-1225268770.
Dummy vdso filenames in LibOS and Pal do not match.
https://github.com/gramineproject/gramine/blob/73c8e93d6cfe17f1b9c95945f58b90e7485fc24c/libos/src/libos_rtld.c#L998
This PR corrects dummy vdso filename and fixes the error log. 
Run a profile enabled workload and check the log.
- - - …
> [Pal/Linux-SGX] Fix an error log when profile enabled

- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/pal_misc.c
Previously, Gramine did not verify the read-from-Linux-host timestamp against the last RDTSC time. So it is possible periodically that the previous timestamp (calculated via RDTSC) is greater than the current timestamp (read from Linux host via OCALLs), which can lead to the intermittent failure of LTP test `gettimeofday02` on some configurations with indication that "time is going backwards". This could be even security-relevant since the app running inside the enclave may behave unexpectedly if time teleports back.
This commit adds a sanity adjustment which guarantees no rewinding time is applied when the OCALL-obtained timestamp is "back in time" than the last recorded RDTSC timestamp.
Fixes https://github.com/gramineproject/gramine/issues/82.
CI + LTP tests on specific configs …
> [PAL/Linux-SGX] Verify OCALL-obtained time against last RDTSC time

- libos/src/sys/libos_epoll.c
- libos/src/sys/libos_poll.c
- libos/test/regression/epoll_test.c
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_object.c
- pal/src/host/linux/pal_host.h
- pal/src/host/linux/pal_object.c
Previously, `(E)POLLRDHUP` was not handled and `(E)POLLHUP` was always reported together with `(E)POLLERR` due to the limitation of PAL API, which did not distinguish these conditions. This may cause some workloads to ignore the fact that the socket was closed by the peer and hence keep it in the `CLOSE-WAIT` state.
This commit:
* splits (e)poll error events from hup events.
* adds support for `(E)POLLRDHUP` but treats/reports it as `(E)POLLHUP`, i.e., not distinguishing these two states.
Fixes https://github.com/gramineproject/gramine/issues/1034.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1073)
> [LibOS,PAL] Treat (e)poll error and hup events separately

- common/src/protected_files/protected_files.c
- libos/test/regression/fcntl_lock.c
- libos/test/regression/fcntl_lock_child_only.c
- libos/test/regression/fcntl_lock_child_only.manifest.template
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
There was a bug in the corner case of POSIX locking: when the child process acquires a lock on an encrypted file that was not processed yet by the master process. In this case, the child sends an IPC request to the master process (since all POSIX locks' operations are centrally processed in the master process). The master process must lookup the file first, and only if the lookup is successful, grant the POSIX-lock request to the child.
The bug was: because encrypted files were *not* updated on the hard disk upon creation (the file was created but its metadata wasn't flushed), this confused the master process, and POSIX lock operations failed.
This PR fixes this bug by immediately flushing the metadata of each newly created encrypted file.
A new test is added. CI is enough.
- An exerpt …
> [common] Fix POSIX locking on encrypted file in child process

- LICENSE.txt
As in the title. This PR just replaces the license with the original, downloaded from https://www.gnu.org/licenses/lgpl-3.0.txt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1307)
> Fix broken indentation in LICENSE.txt

- libos/include/libos_utils.h
- libos/src/ipc/libos_ipc.c
- libos/src/libos_init.c
- pal/include/host/linux-common/linux_utils.h
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/src/host/linux-common/gramine_unix_socket_addr.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/pal_pipes.c
- pal/src/host/linux-sgx/pal_process.c
- pal/src/host/linux/pal_main.c
- pal/src/host/linux/pal_pipes.c
- pal/src/host/linux/pal_process.c
- pal/src/pal_main.c
This commit moves the current restriction of pipes + UDSes (that they can connect
to processes only within the same Gramine instances) from PAL layer to LibOS layer.
As a side effect, this commit renames `instance_id` to a more appropriate
`namespace_id` ("Gramine instance" was a term we used to describe a set of
Gramine processes that can communicate with each other, but the better term
for this is "namespace").
Signed-off-by: Ying Liu <ying2.liu@intel.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1170)
> Move the current restriction of pipes + UDSes from PAL layer to Libos layer

- .ci/lib/stage-build-sgx-vm.jenkinsfile
- .ci/lib/stage-clean-vm.jenkinsfile
- .ci/lib/stage-test-vm.jenkinsfile
- .ci/linux-sgx-vm-gcc-release.jenkinsfile
- .ci/ubuntu22.04.dockerfile
- libos/test/regression/device_ioctl.c
- libos/test/regression/device_ioctl.manifest.template
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- python/graminelibos/regression.py
- python/graminelibos/util_tests.py
New Jenkins pipeline runs a Docker container that creates a minimal VM based on https://github.com/gramineproject/device-testing-tools repo and runs a subset of Gramine tests, in particular, the device IOCTL tests. The pipeline uses Ubuntu 22.04 with modern Linux kernel (to have an upstream SGX driver and support for SGX in KVM) and QEMU/KVM to run the VM.
A LibOS regression test `device_ioctl` is added to test the CI; currently it is minimal but will be expanded when [Flexible IOCTLs](https://github.com/gramineproject/gramine/pull/671) functionality is added to Gramine.
The corresonding PR in `device-testing-tools` repo is ~~https://github.com/gramineproject/device-testing-tools/pull/6~~ ~~https://github.com/gramineproject/device-testing-tools/pull/7~~ …
> [CI] Add a VM-based Jenkins pipeline

- libos/test/fs/test_fs.py
While here, let's skip the tests instead of expecting failure for Linux/SGX.
This is small optimization for our CI.
Fixes https://github.com/gramineproject/gramine/issues/663.
Run CI with sgx and with direct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1306)
> [tests] Document why mmap tests are disabled with Linux/SGX

- LICENSE.addendum.txt
As in the title, it seems that info about `libcurl` and `libgomp` are missing in the current `LICENSE.addendum.txt`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1308)
> Update LICENSE.addendum.txt with libcurl and libgomp

- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux/pal_main.c
We can't do that because the array which contains error strings might not be relocated yet. The error strings reside in .rodata segment. If we use `pal_strerror` and relocations are in use (default build), the function will return the offset instead of the real address. This will cause Gramine to segfault.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1317)
> [PAL/Linux] Do not call `pal_strerror` before/during/failed PAL relocation

- libos/include/libos_process.h
- libos/src/bookkeep/libos_process.c
Previously Gramine had a static buffer of one page (4KB) in size to hold cmdline, which turns out to be not enough for Apache Kafka workloads (which is actually a `/bin/java` command line with many JAR files listed in the command line).
This commit changes to use dynamic allocation for it and propagates on fork/clone.
Fixes https://github.com/gramineproject/gramine/discussions/1303.
manual testing + CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1320)
> [LibOS] Use dynamic allocation for `libos_process.cmdline`

- Documentation/pal/host-abi.rst
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/regression/File.c
- pal/regression/Symbols.c
- pal/regression/test_pal.py
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_streams.c
- pal/src/host/skeleton/pal_streams.c
- pal/src/pal_streams.c
- pal/src/pal_symbols
The whole codebase of Gramine actually uses `PalVirtualMemoryFree()` instead, so this API was completely unused and untested.
No functional changes. CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1329)
> [PAL] Remove unused `PalStreamUnmap()`

- Documentation/manifest-syntax.rst
The syntax `loader.pal_internal_mem_size = "[SIZE]"` was deprecated in Gramine v1.4.
Now that the next version of Gramine will be v1.5, we can safely remove it.
doc change only
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1330)
> [Docs] Remove deprecated syntax for Gramine internal metadata size

- Documentation/manifest-syntax.rst
- pal/src/host/linux-sgx/common_manifest_sgx_parser.c
The syntax `sgx.remote_attestation = [true|false]` was deprecated in Gramine v1.3.
Now that the next version of Gramine will be v1.5, we can safely remove it.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1333)
> [PAL/Linux-SGX,Docs] Remove deprecated bool syntax for `sgx.remote_attestation`

- Documentation/manifest-syntax.rst
- libos/test/regression/multi_pthread_exitless.manifest.template
- pal/src/host/linux-sgx/host_main.c
- python/graminelibos/manifest.py
- python/graminelibos/sgx_sign.py
The syntax `sgx.thread_num = [NUM]` was deprecated in Gramine v1.4.
Now that the next version of Gramine will be v1.5, we can safely remove it.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1331)
> [PAL/Linux-SGX,Docs] Remove deprecated syntax for number of threads

- pal/src/host/linux/pal_memory.c
Linux can return `-ENOMEM` if a request to `munmap()` will exceed the process's maximum number of mappings (this is possible in case of partial memory unmap, when Linux would have to create two mappings out of one). Gramine's LibOS is not ready for such failures, and also it is specific to the Linux PAL, so this commit simply makes this failure more visible and provides a hint for the user what can be done on the host.
Fixes #1327 (though not a real fix, more like a verbose failure).
Manually test like described in https://github.com/gramineproject/gramine/issues/1327. This can be hit only on specific and memory-hungry workloads.
- - - …
> [PAL/Linux] Log a message on `munmap()` returning `-ENOMEM`

- Documentation/manifest-syntax.rst
- pal/src/pal_main.c
The syntax `fs.experimental__enable_sysfs_topology = [true|false]` was deprecated in Gramine v1.2.
Now that the next version of Gramine will be v1.5, we can safely remove it.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1332)
> [PAL,Docs] Remove deprecated syntax for experimental sysfs topo support

- .readthedocs.yaml
The recent version of urllib3 (v2.0) only supports OpenSSL 1.1.1+. However, the ReadTheDocs engine that we use for generating our web documentation by default uses older OpenSSL. The workaround is to pin a specific OS distro and Python version.
For the context:
- https://github.com/urllib3/urllib3/issues/2168
- https://github.com/readthedocs/readthedocs.org/issues/10290
- https://github.com/readthedocs/readthedocs-docker-images/issues/194
Check RTD logs. (I will do it manually.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1335)
> [Docs] Work around the bug of urllib3 and OpenSSL incompatibility

- libos/include/arch/x86_64/gramine_entry_api.h
- libos/include/libos_handle.h
- libos/include/libos_rwlock.h
- libos/src/bookkeep/libos_handle.c
- libos/src/fs/proc/thread.c
- libos/src/libos_call.c
- libos/src/libos_rwlock.c
- libos/src/meson.build
- libos/src/sys/libos_fcntl.c
- libos/src/sys/libos_ioctl.c
- libos/src/sys/libos_poll.c
- libos/test/regression/meson.build
- libos/test/regression/rwlock.c
- libos/test/regression/rwlock.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Map of LibOS handles is mainly read, so using rwlocks should give some performance advantage.
CI.
I couldn't come up with a good and simple test for the locks themselves. Also we have no way of running "unit tests" in LibOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1109)
> [LibOS] Use rwlock in libos handle map

- pal/src/pal_main.c
The syntax `loader.debug_type = "[none|inline|file]"` was deprecated in favor of `loader.log_level` and `loader.log_file` long before Gramine introduced a deprecation policy. Now that the next version of Gramine will be v1.5, we can safely remove it.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1342)
> [PAL] Remove deprecated syntax for debug type

- Documentation/_static/css/gramine.css
Extracted from #1241.
I created a RTD job to see the rendering: https://gramine.readthedocs.io/en/dimakuv-docs-add-sidebar-gramine-css/. Notice the scrollbar. Compare with our classic: https://gramine.readthedocs.io/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1346)
> [Docs] Add scrollbar to the side navigation menu

- pal/include/pal_internal.h
Found this Graphene-era unused stuff while working on https://github.com/gramineproject/gramine/issues/1352
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1353)
> [PAL] Remove unused `__attribute_*` macros

- Documentation/devel/building.rst
- Documentation/devel/coding-style.rst
- Documentation/devel/features.md
- Documentation/devel/onboarding.rst
- Documentation/glossary.rst
- Documentation/manifest-syntax.rst
- Documentation/pal/host-abi.rst
- Documentation/quickstart.rst
- Documentation/sgx-intro.rst
Extracted from https://github.com/gramineproject/gramine/pull/1241.
Compare:
- https://gramine.readthedocs.io/en/dimakuv-docs-wording-typos/ (this PR)
- https://gramine.readthedocs.io/en/latest/ (current docs)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1348)
> [Docs] Fix typos and improve wording

- libos/test/fs/common.h
The ACCESSPERMS macro seems to be glibc specific, for example, it is not defined in the musl libc on Alpine Linux.
This macro is used by the `chmod_stat` test (`libos/test/fs/chmod_stat.c`).
* https://codebrowser.dev/glibc/glibc/io/sys/stat.h.html#_M/ACCESSPERMS
* https://git.musl-libc.org/cgit/musl/tree/include
CI and build on Alpine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1370)
> [tests] Define ACCESSPERMS, if not present

- libos/include/arch/x86_64/gramine_entry_api.h
`gramine_call` is a custom interface to test Gramine internal functions. It uses Gramine syscall emulation and hence does not save/restore SEE registers (see "libos/src/arch/x86_64/syscallas.S" for more details). This turned out to be problematic, since test code calling `gramine_call` might assume SSE registers are not clobbered, since `gramine_call` is in reality just an inline asm block. This commit fixed that by explicitly adding all SSE registers to the clobber list.
Fixes #1352
Closes #1354
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1355)
> [LibOS] Add SSE registers to clobber list in gramine_call

- .ci/lib/stage-build-sgx-vm.jenkinsfile
- Documentation/manifest-syntax.rst
- libos/src/sys/libos_ioctl.c
- libos/test/regression/device_ioctl.c
- libos/test/regression/device_ioctl.manifest.template
- libos/test/regression/device_ioctl_fail.manifest.template
- libos/test/regression/device_ioctl_parse_fail.c
- libos/test/regression/device_ioctl_parse_fail.manifest.template
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/enclave_ocalls.h
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux-sgx/pal_ocall_types.h
- pal/src/host/linux/pal_devices.c
- pal/src/host/skeleton/pal_devices.c
- pal/src/pal_misc.c
- pal/src/pal_symbols
The newly added `ioctl()` syscall emulation on device-backed file descriptors is pass-through. It is insecure by itself since the emulation only passes the arguments to and from the untrusted memory. It is the responsibility of the app developer to correctly use ioctls, with security implications in mind.
On the Linux-SGX PAL, a set of IOCTL requests must be explicitly allowed in the manifest via the new option `sgx.allowed_ioctls.[id].request`. Also, the allowed IOCTLs' arguments (typically pointers to complex nested objects) must be explicitly described in the manifest via the new options `sgx.ioctl_structs.[id]` and a corresponding reference `sgx.allowed_ioctls.[id].struct`; see docs for explanation of the IOCTL struct format.
Companion PR: …
> [LibOS,PAL] Add flexible device-specific IOCTL support

- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c
An implicit conversion from const-qualified pointer types to non-const-qualified ones in C can generate a compilation warning. This happened for `str_ptrace_request()` when `DEBUG_GDB_PTRACE` was enabled, where "return discards `const` qualifier from pointer target type".
Manual testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1379)
> [PAL/Linux-SGX] sgx_gdb: return const string for `str_ptrace_request()`

- pal/src/host/linux-common/debug_map.c
- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c
Previously, Gramine's GDB plugin used `ptrace(PTRACE_PEEKDATA, pid)` to detect all TIDs of enclave threads. This way of invocation (with a PID of a process instead of a stopped-tracee thread TID) led to sporadic errors of ptrace syscall with `-ESRCH`. Ptrace can return this error code when the specified tracee (the main thread) is not currently stopped. Because this invocation could happen from child threads, this error happened when debugging multi-threaded workloads.
The fix is to always use `ptrace(PTRACE_PEEKDATA, tid)` where TID is the currently ptrace-stopped tracee thread.
Also, this PR has a small commit to print the absolute address (RIP value) in debug messages. This turned out helpful in my debugging.
Fixes #1375.
CI is enough. Also manually check the scenarios in …
> [Pal/Linux-SGX] sgx_gdb: Fix `ptrace(PTRACE_PEEKDATA)` invocation

- libos/include/libos_process.h
- libos/src/bookkeep/libos_process.c
- libos/src/bookkeep/libos_thread.c
- libos/src/fs/proc/thread.c
- libos/src/sys/libos_clone.c
- libos/src/sys/libos_getpid.c
- libos/src/sys/libos_ioctl.c
- libos/src/sys/libos_sigaction.c
- libos/test/ltp/ltp.cfg
- libos/test/ltp/ltp_sgx.cfg
- libos/test/regression/meson.build
- libos/test/regression/sid.c
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Previously, session-management syscalls e.g., `setsid()`, `getsid()`, were not supported in Gramine. However, they are required for many workloads, particularly the ones that use JVM.
This commit adds basic support for session-management syscalls and enables the related tests. As a side effect of the introduction of `setsid()`, `pgid` and `sid` in struct `libos_process` are now both not suitable for atomic access so we introduced a new global lock and used it everywhere where we access `pgid` and `sid`.
Newly enabled LTP tests + unit tests
How session-management syscalls work:
* https://man7.org/linux/man-pages/man2/setsid.2.html
* https://man7.org/linux/man-pages/man2/getsid.2.html
* https://www.andy-pearce.com/blog/posts/2013/Aug/process-groups-and-sessions/
* …
> [LibOS] Add support for `setsid()`/`getsid()`

- libos/src/libos_init.c
- libos/src/libos_rtld.c
This memory leak was found by the Coverity tool. Also, we fix a couple nits around `g_library_paths`.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1389)
> [LibOS] Fix memory leak of `interp_path` string

- .ci/lib/stage-clean-check.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- .ci/ubuntu20.04.dockerfile
- .ci/ubuntu22.04.dockerfile
- CI-Examples/ra-tls-nginx/Makefile
- CI-Examples/ra-tls-nginx/README.md
- CI-Examples/ra-tls-nginx/html/index.html
- CI-Examples/ra-tls-nginx/nginx.conf
- CI-Examples/ra-tls-nginx/nginx.manifest.template
- CI-Examples/ra-tls-nginx/run.sh
- Documentation/conf.py
- Documentation/manpages/gramine-ratls.rst
- Documentation/manpages/index.rst
- debian/gramine.manpages
- tools/sgx/ra-tls/gramine-ratls.c
- tools/sgx/ra-tls/meson.build
This PR adds `gramine-ratls` tool, which is (will be) useful when packaging HTTP(S) apps which do attestation using RA-TLS.
Run this tool inside enclave, possibly start HTTPS server using generated keypair.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1382)
> [tools/sgx] Add gramine-ratls wrapper

- libos/test/regression/test_libos.py
Previously encrypted files (aka protected files) were only available for SGX PAL. Since then, encrypted files were moved to LibOS layer and can be used also in non-SGX setup. But we forgot to enable some tests.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1392)
> [tests] Enable encrypted-files tests in non-SGX setup

- Documentation/manifest-syntax.rst
- libos/src/fs/socket/fs.c
- libos/src/sys/libos_ioctl.c
- libos/test/ltp/ltp.cfg
- libos/test/ltp/ltp_sgx.cfg
- libos/test/ltp/manifest.template
- libos/test/regression/meson.build
- libos/test/regression/socket_ioctl.c
- libos/test/regression/socket_ioctl.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux/pal_devices.c
Add host ABI `PalSocketIoControl` to handle socket-specific `ioctl` operations. Currently only `SIOCGIFCONF` and `SIOCGIFHWADDR` commands are supported to enable workloads that request IP address of all network interfaces, for example, Pyspark.
In Linux-SGX Pal, `ocall_ioctl` is added and aligns with device-specific IOCTL support in #671.
new regression test `socket_ioctl` and ltp test `sockioctl01`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1233)
> [LibOS,Pal] Add support of `ioctl(SIOCGIFCONF/SIOCGIFHWADDR)`

- libos/include/libos_fs.h
- libos/include/libos_fs_lock.h
- libos/include/libos_ipc.h
- libos/src/bookkeep/libos_handle.c
- libos/src/fs/libos_dcache.c
- libos/src/fs/libos_fs_lock.c
- libos/src/ipc/libos_ipc_fs_lock.c
- libos/src/ipc/libos_ipc_worker.c
- libos/src/sys/libos_exit.c
- libos/src/sys/libos_fcntl.c
This is a preparatory commit to introduce flock (BSD locks) support. Previously, Gramine supported only POSIX locks, which was reflected in struct and function names (the `posix_` prefix and the `pl` abbreviation). With BSD locks, the same structs and functions will be used for both lock types, so this commit renames `posix` to `file` and `pl` to `file_lock`. Additionally, misleadingly named `struct fs_lock` is renamed to `struct dent_file_locks` (means: association of a dentry with its file locks).
Created in response to the comments in #1212.
CI is enough. Pure renaming.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1406)
> [LibOS] Rename POSIX lock related structs and functions

- libos/include/libos_table.h
- libos/include/linux_abi/sysinfo.h
- libos/include/linux_abi/types.h
- libos/src/sys/libos_getrlimit.c
This is a part of making our LibOS independent of the host headers (we want this b/c the host may not even be Linux).
Previous work from this series: #1275, #1301.
For now only this one struct, because Alpine need it.
Try building on weird hosts (like Alpine).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1426)
> [LibOS] Import `struct sysinfo` to Gramine

- Documentation/manifest-syntax.rst
- libos/include/libos_fs_lock.h
- libos/include/libos_handle.h
- libos/include/libos_ipc.h
- libos/src/bookkeep/libos_handle.c
- libos/src/fs/libos_fs_lock.c
- libos/src/ipc/libos_ipc_fs_lock.c
- libos/src/ipc/libos_ipc_pid.c
- libos/src/sys/libos_fcntl.c
- libos/test/ltp/ltp.cfg
- libos/test/ltp/manifest.template
- libos/test/regression/fcntl_lock.c
- libos/test/regression/flock_lock.c
- libos/test/regression/manifest.template
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
The `flock` implementation introduces flock (aka BSD) locks, in addition to already-existing fcntl (aka POSIX) locks. The flock heavily reuses the current logic of `libos_file_lock` and `dent_file_locks`.
Since flock locks are tied to the handle, we introduce a new field `struct libos_file_lock::handle_id` that serves to distinguish flock  locks from fcntl locks. Similarly to fcntl locks, interruptable flock locks are not supported.
This is a reincarnation of #1212. It was easier to make it a new PR, then to continue working on the old PR.
Closes #1212.
New tests are added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1416)
> [LibOS] Add `flock` syscall

- subprojects/packagefiles/glibc-2.37/fix-bug-30068.patch
- subprojects/packagefiles/glibc-2.37/meson.build
Glibc v2.37 introduced a bug in `vfprintf()` family of functions, where mishandling of grouping when formatting integers leads to a buffer overflow. This is considered a critical vulnerability, so Gramine must apply a fix. The fix is taken from glibc commit c980549cc6a.
See:
- https://nvd.nist.gov/vuln/detail/CVE-2023-25139
- https://sourceware.org/bugzilla/show_bug.cgi?id=30068
- https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=c980549cc6a1c03c23cc2fe3e7b0fe626a0364b0
- https://github.com/bminor/glibc/commit/c980549cc6a
I tested manually on the reproducer from https://sourceware.org/bugzilla/show_bug.cgi?id=30068. Here's a diff:
```diff
diff --git a/CI-Examples/helloworld/helloworld.c b/CI-Examples/helloworld/helloworld.c
index 2efc7765..e7940174 100644
--- …
```
> [Glibc] Apply a fix of CVE-2023-25139 (glibc bug 30068)

- .ci/alpine3.17.dockerfile
- .ci/pkg-apk-alpine3.17.jenkinsfile
- packaging/alpine/.gitignore
- packaging/alpine/APKBUILD
Taken over #1421, with fixes and CI.
CI (esp. `pkg-apk-alpine3.17`)
Quick and dirty, but always works. Leaves root-owned files in you repo (you can clean with `sudo git clean -dxf` afterwards). Proper testing would require proper alpine packaging setup (read more here: https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package), which is not in scope here.
```
docker run -it --rm alpine:latest --volume $PWD:/gramine
cd /gramine/packaging/alpine
apk add alpine-sdk jq meson nasm
abuild-keygen -an
abuild -F -r snapshot checksum all
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1439)
> [packaging] Alpine

- Documentation/manpages/gramine-ratls.rst
It was noted that current documentation on `gramine-ratls` is too dense. I added a bit more explanations:
- It's important to state that a normal usage would be as a "pre-main" executable.
- It's important to state that `gramine-ratls` will typically be the entrypoint in the manifest.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1450)
> [Docs] Provide more explanations on the use of `gramine-ratls`

- common/include/log.h
Previously we had a function that emulated `__FILE_NAME__` macro (which was introduced only recently in GCC12 and Clang9) by truncating the file name in a loop. It led to unnecessary calls to this func even when logs were disabled, ultimately resulting in perf overhead. We observed around 5% overhead because of this on file-I/O intensive benchmarks (because there we print a lot of log_debug info).
This PR simply falls back to a more clunky `__FILE__` macro when `__FILE_NAME__` is not defined.
Fixes #1456.
See how I test in https://github.com/gramineproject/gramine/issues/1456. With this PR, manual inspection. You may also want to run some simple FS benchmark (like calling `read()` syscall in a loop) and observe perf overhead, e.g. via `perf record`.
- - - …
> [common] Do not expand `__FILE_NAME__` to our func call

- pal/include/pal_internal.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux/pal_main.c
- pal/src/pal_main.c
This is useful so that the host-specific PAL can perform some post-initialization actions. In particular, the
`print_warnings_on_insecure_configs()` func in SGX PAL is moved to the post-initialization phase because this info should be logged into the `loader.log_file` (if it was specified in the manifest) instead of on the terminal.
Manually. E.g., add `loader.log_file = "gramine.log"` to the Helloworld example and observe the behavior under `gramine-sgx`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1467)
> [PAL] Add `post_callback` function arg to `pal_main()`

- CI-Examples/ra-tls-nginx/run.sh
- libos/src/bookkeep/libos_signal.c
Previously, `get_all_pending_signals()` helper function did not check for the SIGTERM signal (which has a special handling via `g_host_injected_signal`). Syscalls like `rt_sigsuspend()` and `rt_sigtimedwait()` use this helper function. Because of that erroneous behavior, apps like Nginx would wait for signals on one of these syscalls but would *not* react to SIGTERM (i.e., won't react to `kill <app>`).
This PR fixes this bug, which in turns fixes nginx and ra-tls-nginx examples.
Without this PR, ra-tls-nginx example (with `kill $pid`, i.e. without SIGKILL) would not kill Nginx at all. Running this example twice on the same machine would fail with `bind() to 0.0.0.0:8000 failed (98: Address already in use)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> [LibOS] Add SIGTERM signal to list of pending signals

- common/src/string/atoi.c
- pal/regression/strtoll_test.c
Previously, parsing "0" using `strtol(.., /*base=*/0)` returned incorrect endptr (i.e. the function failed to parse the number).
Looks like this corner case was introduced as part of this fix: https://github.com/gramineproject/gramine/commit/4003cb63a60d13061b17720514d244c6cfb7db0a
Added a test case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1481)
> [common] Fix corner case of `strtol("0", .., 0)`

- libos/src/fs/sys/cpu_info.c
- libos/src/fs/sys/fs.c
- libos/test/regression/test_libos.py
Adds `/sys/devices/system/cpu/{offline,present}` files.
Also improve the `sysfs` LibOS regression test to verify that these new CPU-related files exist, plus that the old CPU- and NUMA-node-related files exist.
Without this, `lscpu` tool works incorrectly under Gramine.
Extracted from #1454.
- Use this diff on Ubuntu (need to have `lscpu` installed):
```diff
~/gramineproject/gramine/CI-Examples/helloworld$ git diff
diff --git a/CI-Examples/helloworld/helloworld.manifest.template b/CI-Examples/helloworld/helloworld.manifest.template
@@ -1,14 +1,16 @@
loader.entrypoint = "file:{{ gramine.libos }}"
-libos.entrypoint = "/helloworld"
+libos.entrypoint = "/lscpu"
loader.log_level = "{{ log_level }}"
-loader.env.LD_LIBRARY_PATH = "/lib"
+loader.env.LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu/" …
```
> [LibOS] Add `/sys/devices/system/cpu/{offline,present}` files

- common/include/arch/x86_64/cpu.h
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux-sgx/pal_misc.c
Some hypervisors (like QEMU/KVM) do not expose CPUID leaves 0x15 and 0x16 (Core Crystal Clock/Process Frequency). Instead, hypervisor-specific CPUID leaf 0x40000010 shows TSC frequency.
Note that QEMU/VKM must start the VM with CPU flags `+invtsc,+vmware-cpuid-freq` to expose required CPUID leaves.
Fixes #1009.
See also https://lwn.net/Articles/301888/.
Need a VM. See https://github.com/gramineproject/gramine/issues/1009.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1012)
> [PAL/Linux-SGX] Add Invariant TSC query fallback for hypervisors

- libos/src/fs/sys/fs.c
- libos/test/regression/test_libos.py
Extracted from https://github.com/gramineproject/gramine/pull/1454.
Manually:
- Original:
```
~/gramineproject/gramine/CI-Examples/busybox$ cat /sys/devices/system/cpu/kernel_max
8191
```
- Without this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /sys/devices/system/cpu/kernel_max
cat: can't open '/sys/devices/system/cpu/kernel_max': No such file or directory
```
- With this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /sys/devices/system/cpu/kernel_max
8191
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1478)
> [LibOS] Add `/sys/devices/system/cpu/kernel_max` file

- libos/src/arch/x86_64/fs_proc/info.c
Some libraries fail if they cannot find the "siblings" line (in particular, `libmkl-gnu-thread` aka "Intel MKL OpenMP threading library for GNU Fortran/C compilers"). This may ultimately lead to the application being run on only a subset of available CPUs, hampering performance.
Extracted from https://github.com/gramineproject/gramine/pull/1454.
Manually using Busybox:
- On original platform:
```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
physical id     : 0
siblings        : 12
...
```
- `gramine-direct busybox cat /proc/cpuinfo`, Without this PR:
```
~/gramineproject/gramine/CI-Examples/busybox$ gramine-direct busybox cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
physical id     : 0
...   // NO …
```
> [LibOS] Add "siblings" line to `/proc/cpuinfo`

- subprojects/packagefiles/glibc-2.37/compile.sh
This was reported by @jyizheng. Thanks to him!
See discussions in https://github.com/gramineproject/gramine/discussions/1487 for details.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1490)
> [glibc] Fix wrong warning option in compile script

- pal/include/elf/elf.h
- pal/src/pal_rtld.c
RELR (relative relocs) is a new type of relocations recently added to compilers/linkers, e.g. glibc 2.36 and musl 1.2.4. These relocs are not enabled by default; however, if the system enables them during Gramine build, Gramine would segfault. This is because Gramine has its own self-relocation code that relocates the SGX PAL and the LibOS binaries. Before this commit, the code ignored RELR relocs, which led to some symbols being not relocated and ultimately to segfaults.
This commit makes Gramine aware of RELR relocs, though we simply loudly fail when we detect such type. Currently, Gramine build environment must disable such relocs.
Fixes #1446.
For the context, see #1446.
Good references:
- https://maskray.me/blog/2021-10-31-relative-relocations-and-relr
- …
> [PAL] Fail if Gramine binaries are built with RELR relocs

- Documentation/devel/building.rst
Installation steps for DCAP dependencies were specific to Ubuntu 18.04 which is not supported now, hence updated the steps for Ubuntu 20.04 and 22.04.
Check the build section in Gramine documentation: https://gramine.readthedocs.io/en/latest/devel/building.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1500)
> [Docs] Update installation steps for DCAP dependencies

- pal/src/pal_rtld.c
Some compilers/linkers generate the `DT_BIND_NOW` entry instead of adding a flag `DF_BIND_NOW` to the `DT_FLAGS` entry. Since our linker anyway always performs all relocations immediately (not lazily), this entry is a no-op.
It looks like some compilers use `DT_BIND_NOW`, though this particular dynentry was superseded by a flag `DF_BIND_NOW`. At the same time, this dynentry simply means "use immediate binding instead of lazy binding" (lazy binding is the default for linkers). And our Gramine-internal linker always uses immediate binding. So we can simply ignore `DT_BIND_NOW` dynentry, as it just hints at what Gramine is doing anyway.
References:
- http://www.qnx.com/developers/docs/qnxcar2/index.jsp?topic=%2Fcom.qnx.doc.neutrino.prog%2Ftopic%2Fdevel_Lazy_binding.html
- …
> [PAL] Recognize `DT_BIND_NOW` dynamic entry

- .ci/linux-sgx-vm-gcc-release.jenkinsfile
- .ci/ubuntu22.04.dockerfile
- libos/test/regression/device_ioctl_parse_fail.c
The Jenkins worker node for this pipeline was updated from Debian 11 to Debian12, which broke the pipeline. This commit contains assorted fixes required to make it work again.
The corresponding PR is https://github.com/gramineproject/device-testing-tools/pull/10 (must be merged first).
Check the status of `linux-sgx-vm-gcc-release` job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1512)
> [CI] Fix linux-sgx-vm-gcc-release pipeline after update to Debian 12

- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/sgx_arch.h
At ECREATE time, `isvprodid` and `isvsvn` (and many other fields) are set to zero in the SECS page. These fields will be copied from SIGSTRUCT at EINIT time. So it's only misleading to print these fields' values at ECREATE time.
As a side effort, this commit cleans up `sgx_arch.h` header.
See Intel SDM documentation for reference. Or check these carefully:
- https://www.felixcloutier.com/x86/ecreate
- https://www.felixcloutier.com/x86/einit
N/A. This was detected by a customer who was confused why the fields showed `0` values in Gramine with debug prints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1396)
> [PAL/Linux-SGX] Remove misleading print of `isvprodid` and `isvsvn`

- libos/test/regression/meson.build
- meson.build
- tools/meson.build
Instead, always use non-ambigious `get_option('prefix')`.
Extracted from #619. That PR had no movement for ~1 year already, so I decided to create a small PR with just this change.
It was also a request from a review of #619 (see top-level comments from Woju and Borys).
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1415)
> [Meson] Remove ambigious `prefix` variable

- Documentation/conf.py
- python/graminelibos/sgx_sign.py
For unencrypted keys, CI is OK. If you want to test encrypted keys, generate one manually (`gramine-sgx-gen-private-key` can't do that) and test also manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1197)
> Rewrite SGX signing in cryptography.io

- libos/src/fs/chroot/encrypted.c
Instead, a negative error code should be returned in case of failure.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1522)
> [LibOS] Fix wrong return of `chroot_encrypted_write()` on failure

- libos/src/libos_parser.c
In case of invalid MAP_TYPE flags in mmap requests (e.g., no or wrong mapping type specified), previously Gramine simply ran into assertion fails when parsing them in debug mode.
Instead, Gramine should parse the flags and fail with the same error on syscall handling as Linux does (on incorrect flags).
Fixes https://github.com/gramineproject/gramine/issues/1516.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1524)
> [LibOS] Remove assertion in `parse_mmap_flags()`

- libos/include/libos_fs.h
- libos/src/fs/chroot/fs.c
- libos/src/fs/libos_fs_util.c
`generic_truncate` can be used for other file system types (shared memory filesystem in #827).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1529)
> [LibOS] Move `chroot` specific `truncate` to generic FS operations

- libos/src/fs/libos_fs_util.c
Update time attributes in `struct stat` on file status query. This is required to support Gunicorn workload in gramine. This workload calls `fstat` on `tmpfs` files and uses the `st_ctime` field of `struct stat`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1539)
> [LibOS] Update time attributes in `struct stat` on file status query

- debian/control
- gramine.spec
- packaging/alpine/APKBUILD
- python/graminelibos/sgx_sign.py
See the commit message.
Run any scenario up to `gramine-sgx-sign` (which should not fail) on all supported distros. Executing the enclave is not necessary.
Fixes: #1532
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1540)
> [python] Fix CLI option synonym handling for old click

- libos/src/arch/x86_64/libos_arch_prctl.c
The check was missing. Reported by Scott Constable.
N/A. Trivial.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1543)
> [LibOS] Fail if address in `arch_prctl()` is inaccessible

- libos/include/libos_thread.h
- libos/src/sys/libos_access.c
- libos/src/sys/libos_alarm.c
- libos/src/sys/libos_clone.c
- libos/src/sys/libos_getcwd.c
- libos/src/sys/libos_getpid.c
- libos/src/sys/libos_mmap.c
- libos/src/sys/libos_socket.c
- libos/src/sys/libos_time.c
Inspired by #1543, I went through all the syscalls implementations and verified if they actually check user pointers.
Additionally fixes a bug in gettimeofday() implementation which left timezone struct uninitialized.
CI, mostly LTP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1544)
> [LibOS] Fix a few user-pointer checking bugs in syscalls

- libos/src/fs/sys/fs.c
- libos/src/fs/sys/node_info.c
- pal/include/arch/x86_64/pal_topology.h
- pal/src/host/linux-common/topo_info.c
- pal/src/host/linux-sgx/pal_main.c
Previously, Gramine iterated through all NUMA nodes within the range obtained from the host's `/sys/devices/system/node/possible` file to get `cpulist` and `distance`. It also used the count of possible nodes to parse the `distance` between nodes. However, there is no `/sys/devices/system/node/nodeX` directory when a node is not online. Also, `/sys/devices/system/node/nodeX/distance` lists distances between online nodes only (jumping over offline nodes). This can lead to failures when Gramine tries to read values of `cpulist` and `distance` pseudo-files from the directory. Plus a correct parsing of `distance` should consider only online nodes.
**This is version 2 of #1454.** @mkow asked to keep an original definition of the `distances` array for NUMA nodes inside Gramine, and this PR …
> [LibOS,PAL] Fix wrong handling of sysfs NUMA nodes when nodes are offline

- python/graminelibos/sgx_sign.py
The only enclave attributes required for the SGX enclave measurement are the enclave size and the number of enclave threads. Other attributes such as ISV_PROD_ID, ISV_SVN, XFRM are not included in the measurement.
This commit is extracted from https://github.com/gramineproject/gramine/pull/881.
E.g., manually build the Helloworld example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1550)
> [python] Remove unneeded attrs in `get_mrenclave_and_manifest()`

- Documentation/manifest-syntax.rst
- Documentation/performance.rst
- pal/src/host/linux-sgx/sgx_arch.h
- python/graminelibos/manifest.py
- python/graminelibos/sgx_sign.py
This PR introduces `sgx.cpu_features.[...] = "[unspecified|required|disabled]"` instead of `sgx.require_[...] = true|false`.
Mapping of deprecated and new manifest options:
- `sgx.cpu_features.[...] = "unspecified"` -> `sgx.require_[...] = false`
- `sgx.cpu_features.[...] = "required"` -> `sgx.require_[...] = true`
`sgx.cpu_features.[...] = "disabled"` is new and it disables the corresponding CPU feature inside the SGX enclave even if this CPU feature is available on the system: this may improve enclave performance because this CPU feature will *not* be saved and restored during enclave entry/exit.
As a side effect, this PR removes unneeded attrs in `get_mrenclave_and_manifest()`. The only enclave attributes required for the SGX enclave measurement are the enclave size and the number of …
> [PAL/Linux-SGX] Introduce `sgx.cpu_features.[...]` manifest options

- pal/regression/Exception.c
- pal/regression/manifest.template
- pal/regression/test_pal.py
- pal/src/host/linux-sgx/pal_exception.c
Previously, Linux-SGX PAL did not check `sgx.require_exinfo` and propogated the address anyway to LibOS/app. However, LibOS can't/shouldn't handle faulting addresses at all if `sgx.require_exinfo = false`, as in this case, no matter what enclave address LibOS/app tried to access, SGX would always report address 0.
This commit adds a check on whether `sgx.require_exinfo` is enabled when a memory fault occurred/to be handled and we loudly fail if it's not.
For more context, see discussions here: https://github.com/gramineproject/gramine/issues/1099#issuecomment-1663842018.
CI + manual testing w/ a purpose-built memfault app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/g …
> [PAL/Linux-SGX] Disallow memfault handling if `sgx.require_exinfo = false`

- libos/src/libos_rtld.c
Otherwise, this could lead to a "double `put_handle()`" problem when the shebang script depth exceeded the limit.
Fixes https://github.com/gramineproject/gramine/issues/1526.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1558)
> [LibOS] Set file handle to NULL after each shebang search iteration

- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
The `chmod()` callback is supposed to perform PAL-level (host-level) file permission change. The description of this callback explicitly states that "on success, the caller should update `dent->inode->perm`". Thus, the assignment inside the callback is redundant.
See the description of the callback: https://github.com/gramineproject/gramine/blob/8f65e6ad7444410d576a63fd0e5f443ced82830c/libos/include/libos_fs.h#L376-L387
N/A. No functional change, just removed duplicate code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1542)
> [LibOS] Remove duplicated `dent->inode->perm` assignment in `chmod()`

- libos/include/libos_fs.h
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/tmpfs/fs.c
- libos/src/sys/libos_file.c
- libos/test/regression/rename_unlink.c
Fix `ENOENT` error when `fchmod` is called on unlinked file
`rename_unlink` regression test is extended to validate this implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1538)
> [LibOS] Fix `ENOENT` error in `fchmod` on unlinked file

- python/graminelibos/sgx_sign.py
see commit message
Get an encrypted PEM RSA-3072 key, then attempt to sign an enclave with:
```sh
gramine-sgx-sign --passphrase ...
```
Before this PR, there is probably this error:
```
File "/usr/lib/python3/dist-packages/cryptography/utils.py", line 36, in _check_byteslike
memoryview(value)
TypeError: memoryview: a bytes-like object is required, not 'str'
TypeError: password must be bytes-like
```
After this PR, signing should complete without error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1581)
> [python] Fix encoding of the passphrase

- CI-Examples/memcached/Makefile
- CI-Examples/memcached/README.md
- CI-Examples/memcached/memcached.manifest.template
Previous version of Memcached (v1.5.21) failed on Ubuntu 22.04 and GCC 11.4.0 with a build error:
‘sigignore’ is deprecated: Use the signal function instead
This was fixed in v1.6.7. So let's update Memcached to the latest available version (v1.6.21 as of Oct 2023). This latest version uses eventfd, so we also update the manifest template.
The exact error:
```
gcc -DHAVE_CONFIG_H -I.  -DNDEBUG   -g -O2 -pthread -pthread -Wall -Werror -pedantic \
-Wmissing-prototypes -Wmissing-declarations -Wredundant-decls \
-MT memcached-memcached.o -MD -MP -MF .deps/memcached-memcached.Tpo -c -o memcached-memcached.o
memcached.c: In function ‘main’:
memcached.c:9531:9: error: ‘sigignore’ is deprecated: Use the signal function instead [-Werror=deprecated-declarations]
```
The exact GCC version:
```
$ gcc …
```
> [CI-Examples] Update version of Memcached

- Documentation/manifest-syntax.rst
- common/include/api.h
- common/src/string/util.c
- libos/test/regression/device_ioctl.manifest.template
- libos/test/regression/device_ioctl_fail.manifest.template
- libos/test/regression/device_ioctl_parse_fail.manifest.template
- libos/test/regression/device_passthrough.manifest.template
- pal/src/host/linux-sgx/enclave_framework.c
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_devices.c
- pal/src/host/linux/pal_host.h
- pal/src/host/linux/pal_streams.c
- pal/src/host/skeleton/pal_devices.c
Previously, device files (like `dev:/dev/zero`) where enabled in Gramine via the FS-mounts syntax in manifest:
fs.mounts = [ {path = "/dev/zero", uri = "dev:/dev/zero"} ]
However, devices are pass-through; Gramine doesn't add any protections to the app-to-device communication. Therefore, a careless usage of `write(device_fd)` may lead to data leaks and `read(device_fd)` may lead to injection attacks.
To make it more pronounced that Gramine doesn't provide any security guarantees to the device communication, this commit forces to specify devices as `sgx.allowed_files`. This is similar to how Gramine forces to specify device IOCTLs as `sys.allowed_ioctls`. **This is a breaking change!**
At the PAL level, this requires normalizing the device pathname and finding it in the list of allowed …
> [PAL] Enforce that device files are in the list of `sgx.allowed_files`

- Documentation/manifest-syntax.rst
Non-programming users do not know this quirk that `argv[0]` is typically a program name, and that actual commandline arguments start with the second item (`argv[1]`).
Documentation check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1608)
> [Docs] Explain that `loader.argv` must contain `argv[0]`

- libos/include/libos_utils.h
- libos/src/libos_malloc.c
- pal/include/pal_internal.h
- pal/src/pal_streams.c
- pal/src/slab.c
Previously, Gramine had two generic functions doing the same thing. Remove one of them.
I added the `alloc_and_copy()` function in commit https://github.com/gramineproject/gramine/commit/872a14ecb48f79b6c64838adc26bfd18197b4d8e. I didn't notice that we already have `malloc_copy()`. Now let's remove the latter (as the former is cleaner).
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1606)
> [PAL,LibOS] Replace `malloc_copy()` with `alloc_and_copy()`

- python/graminelibos/sgx_sign.py
This fixes mistake in #1581. Relevant to gramineproject/gsc#173.
- `gramine-sgx-sign` (no `--passphrase`)
- `gramine-sgx-sign --passphrase abc` (non-empty `--passphrase`)
- `gramine-sgx-sign --passphrase ''` (empty, but set `--passphrase`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1611)
> [python] Fix encoding of the passphrase yet again

- common/include/asan.h
- libos/src/libos_parser.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux/pal_files.c
- pal/src/host/linux/pal_main.c
- pal/src/host/linux/pal_memory.c
This is a safer version of `MAP_FIXED` which fails instead of overwriting already allocated memory.
Please review carefully, especially please check whether I missed something which could also be changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1374)
> Drop 18.04, part 2: Use `MAP_FIXED_NOREPLACE` where possible

- common/include/api.h
- pal/include/pal/pal.h
- pal/src/pal_streams.c
Previously PAL code had a function `parse_stream_uri()` that returned the type, URI and corresponding handle operations based on the typed URI input. This function had confusing signature and semantics. This commit renames it to `split_uri_and_find_ops()` and makes it explicit that the input URI is a type-prefixed URI.
Fixes #1586. **NOTE**: I didn't make the `find_path_in_uri()` a generic func because it would become too complex. So I kept the `find_path_in_uri()` function as local to that file, and instead simply refactored the `parse_stream_uri()` code.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1607)
> [PAL] Refactor splitting of typed URI into type, URI and ops

- libos/test/regression/debug.gdb
~GDB tests expected `_start()` function in the backtrace. However, it depends on the GDB version and on the setting `backtrace past-main off|on`. For simplicity, this commit disables past-main traces. As a side effect, this also fixes Musl traces because Musl tends to have `??` traces when past-main is on.~
UPDATE: GDB tests expect `_start()` function in the backtrace. However, it depends on the GDB version and on the setting `backtrace past-main off|on` (which seems to differ in different GDB versions). So this commit explicitly enables past-main traces.
I found this inconsistent behavior on Alpine 3.18.0. I couldn't find any discussions on the internet about it, so I just fixed as theoretically should be correct.
Check my experiment that proves that `past-main` behavior seems to be …
> [LibOS] regression: fix GDB tests

- common/src/protected_files/protected_files.c
- libos/src/sys/libos_poll.c
- pal/src/host/linux/pal_streams.c
- python/graminelibos/gen_jinja_env.py
PR fixes Coverity issues described below:
CID 3400413: Operands don't affect result (CONSTANT_EXPRESSION_RESULT)
result_independent_of_operands nfds > 2147483647 is always false regardless of the values of its operands. This occurs as the logical second operand of "||". Code:https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/libos/src/sys/libos_poll.c#L430
CID 3400412: Operands don't affect result (CONSTANT_EXPRESSION_RESULT)
result_independent_of_operands nfds > 2147483647 is always false regardless of the values of its operands. This occurs as the logical second operand of "||". Code: https://github.com/gramineproject/gramine/blob/c114403801d9faed97148cdf0394477965b35ffa/libos/src/sys/libos_poll.c#L379
CID 328009: Logically dead code
The indicated …
> Fix Coverity issues

- subprojects/packagefiles/glibc-2.38/fix-CVE-2023-4527.patch
- subprojects/packagefiles/glibc-2.38/fix-CVE-2023-4806.patch
- subprojects/packagefiles/glibc-2.38/fix-CVE-2023-4911.patch
- subprojects/packagefiles/glibc-2.38/fix-CVE-2023-5156.patch
- subprojects/packagefiles/glibc-2.38/meson.build
Glibc 2.38 release does not contain the fixes of some CVEs, specifically CVE-2023-4527, CVE-2023-4806, CVE-2023-4911 and CVE-2023-5156. Thus Gramine need to apply the fixes, which are taken from the corresponding glibc commits.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1628)
> [glibc] Apply fixes of CVEs

- libos/src/sys/libos_file.c
- libos/test/regression/rename_unlink.c
Gramine implementation of rename system call is failing if the old and new  path are same. 
Seen this issue while graminizing the harshulthakur/voice:latestforgsc  docker image.
1. create a regular file, eg: touch /home/intel/test.txt
2. Graminize and run the below sample python code 
```python
import os
file = input('Enter a file name: ')
path = os.replace(file, file)
print("File %s is renamed successfully" % file)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1627)
> [LibOS] Fix handling of oldpath == newpath in rename syscall

- libos/test/fs/test_enc.py
- tools/sgx/common/util.h
So I'm writing a tool that relies of `ra_tls_verify_*` libraries and it turns out that I need to write some output to stdout. The verifier library garbles the output.
Write an attestor, run it, check that status info from `libra_tls_*` is not being printed to stdout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1624)
> [tools] common/util.h: Make INFO and DBG print to stderr

- Documentation/manpages/gramine.rst
- scripts/meson-render-script.py
- scripts/meson.build
- tools/gramine.in
- tools/meson.build
- tools/vcs_tag.in
Alternative to #1270. Changed:
- adds generic script for rendering templates, which can also chmod the resulting file
- version output is `Gramine X.Y (COMMIT)`
- added manpage entry for `--version` 
```sh
gramine-direct --version
gramine-sgx --version
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1632)
> [tools] Add `gramine-direct --version` and `gramine-sgx --version`

- Documentation/manifest-syntax.rst
- libos/include/libos_fs.h
- libos/include/libos_handle.h
- libos/src/bookkeep/libos_vma.c
- libos/src/fs/libos_fs.c
- libos/src/fs/proc/thread.c
- libos/src/fs/shm/fs.c
- libos/src/meson.build
- libos/src/sys/libos_mmap.c
- libos/test/regression/meson.build
- libos/test/regression/shm.c
- libos/test/regression/shm.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux-sgx/pal_linux_defs.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux-sgx/pal_memory.c
- pal/src/host/linux/pal_devices.c
- pal/src/host/linux/pal_memory.c
- pal/src/host/skeleton/pal_devices.c
As description in [RFC](https://github.com/gramineproject/gramine/issues/757), I aim to add new manifest syntax item `sys.insecure__shared_memory = "[none|passthrough]"`. to support Libc call `shm_open` and `shm_unlink` , which are required in communication with devices.
When `passthrough` is specified, Gramine mounts `/dev/shm/` on host to `/dev/shm/`, which is folder contains shared memory file. Since `/dev/shm/` on host is tmpfs, when a file is created in the folder, shared memory is created in untrusted memory, and accessible by its child, another Gramine or native process. Files under ``/dev/shm/`` support read-write pass-through mmap. 
A new memory address range `shared_address_start/end` is introduced. The range default starts at `128TB` in Linux-SGX Pal to avoid overlapping and …
> [LibOS,PAL/Linux-SGX] Add shared untrusted memory support

- pal/src/host/linux-sgx/host_thread.c
- pal/src/host/linux-sgx/pal_tcb.h
A TODO within the code is fixed, adding proper error reporting in host-side `clone_thread`.  Additionally, a segfault in error handling is fixed.
This PR fixes a test added by #1451.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1645)
> [PAL/Linux-SGX] Thread initialization error handling fixes

- .ci/lib/stage-lint.jenkinsfile
- libos/test/ltp/test_ltp.py
- python/gramine-sgx-get-token
- python/graminelibos/sgx_get_token.py
- python/graminelibos/sgx_sign.py
* I think that the variable with the key is called `path` not `key`, this results in the following python error:
```
Traceback (most recent call last):                                                                                                                                                             
File "/usr/bin/gramine-sgx-sign", line 74, in <module>                                                                                                                                       
main() # pylint: disable=no-value-for-parameter                                                                                                                                            
File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__ …
```
> Fix pylint

- subprojects/packagefiles/glibc-2.38/fix-bug-30723.patch
- subprojects/packagefiles/glibc-2.38/meson.build
Glibc v2.38 has a performance regression in `posix_memalign()`, caused by the newly introduced bin scanning which is later removed. This perf regression was also observed on some boost workloads running with Gramine. Thus, Gramine has to apply a fix, which is taken from glibc commit 0dc7fc1cf0.
CI + manual testing w/ some internal workloads where the perf regression was seen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1637)
> [glibc] Apply a fix for `posix_memalign()` perf regression (glibc bug 30723)

- Documentation/manpages/gramine-sgx-sign.rst
- python/gramine-sgx-sign
- python/gramine-sgx-sigstruct-view
1) Sign any SGX enclave using `gramine-sgx-sign` without `--date`, see that there is no regression (CI is sufficient for this)
2) Use `gramine-sgx-sign --date today` — should be the same SIGSTRUCT as in (1)
3) Use `gramine-sgx-sign --date YYYY-MM-DD` with valid date (e.g. 2023-10-09 for date of submitting this PR) — should include this date in SIGSTRUCT (you can inspect with `gramine-sgx-sigstruct-view`)
4) Use `gramine-sgx-sign --date 1234-56-78` or `0000-00-00` or any other invalid date — should still pass and include such invalid "date" into SIGSTRUCT.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1598)
> [python] Add `gramine-sgx-sign --date` option

- libos/include/libos_fs.h
- libos/include/libos_vma.h
- libos/src/bookkeep/libos_vma.c
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/tmpfs/fs.c
- libos/test/fs/meson.build
- libos/test/fs/read_write_mmap.c
- libos/test/fs/test_enc.py
- libos/test/fs/test_fs.py
- libos/test/fs/test_tmpfs.py
- libos/test/fs/tests.toml
Previously, Gramine didn't propagate changes to a mmaped encrypted file back to the memory. This is unexpected for apps that use both mmap and read/write on the same file (e.g., etcd-io/bbolt has such implementation to write data via `write()` and read it via the mmaped memory).
This commit introduces overwriting of affected mmapped regions on encrypted file writes. To reduce performance penalty in normal cases (where apps use either `write()` or `mmap()`), this commit also creates a new field in the file handle to record the number of mmaped regions of this file. We hence simply check on this field to determine whether to perform the updates to make the overhead negligible if none mmapped.
Fixes https://github.com/gramineproject/gramine/issues/1432 and …
> [LibOS] Update mmapped regions when writing to encrypted files

- libos/include/libos_handle.h
- libos/include/libos_socket.h
- libos/src/net/ip.c
- libos/src/net/unix.c
- libos/src/sys/libos_epoll.c
- libos/src/sys/libos_poll.c
- libos/src/sys/libos_socket.c
- libos/test/regression/meson.build
- libos/test/regression/tcp_einprogress.c
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/regression/send_handle.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/enclave_ocalls.h
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/pal_sockets.c
- pal/src/host/linux/pal_sockets.c
- pal/src/host/skeleton/pal_sockets.c
- pal/src/pal_sockets.c
Previously, Gramine transformed `connect()` of non-blocking sockets into a blocking operation and thus never returned -EINPROGRESS. This led to the connect operation being very slow (waiting for a host timeout) if a remote peer is unresponsive.
This commit fixes this and adds a LibOS regression test ~~; unfortunately the test must be run manually with special network settings to properly test the EINPROGRESS behavior~~. UPDATE: @kailun-qin gave suggestions how to test without any special network settings, see the test sources and notes from the meeting https://github.com/gramineproject/gramine/discussions/1635.
Fixes #1641.
A new test was added, but please test it also manually as described in #1641.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [LibOS,PAL] Support `EINPROGRESS` on non-blocking sockets connect

- .ci/lib/stage-lint.jenkinsfile
- .ci/run-shellcheck
- .ci/ubuntu20.04.dockerfile
- .ci/ubuntu22.04.dockerfile
- libos/test/regression/test_libos.py
- scripts/run-pylint
pylint turned out to not be suitable as a CI check due to its instability between versions and a large amount of questionable findings.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1658)
> [CI] Remove pylint from checks

- Documentation/attestation.rst
There is a Microsoft Azure Attestation (MAA) plugin for RA-TLS and SecretProv libraries, kept in the `contrib` repository.
Fixes #1569.
I temporarily enabled the Attestation page: https://gramine.readthedocs.io/en/dimakuv-docs-mention-maa-plugin/attestation.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1604)
> [Docs] Mention MAA plugin for RA-TLS/SecretProv

- tests/test_sgx_sign.py
`tmp_path` fixture requires pytest version 3.9.0+. However, RHEL 8 and CentOS Stream 8 install pytest 3.4.2 by default.
This commit fixes the incompatibility issue by using `tmpdir` fixture instead.
Fixes https://github.com/gramineproject/gramine/issues/1661.
`python3 -m pytest -v --junit-xml tests.xml tests/` w/ both older and newer pytest versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1662)
> [tests] test_sgx_sign: fix incompatibility with old pytest

- pal/src/host/linux-sgx/enclave_entry.S
- pal/src/host/linux-sgx/pal_exception.c
- pal/src/host/linux-sgx/pal_linux.h
When enabled, the SGX EXINFO feature forces the CPU core to report #PF exceptions to the SGX enclave (in the EXITINFO/EXINFO SSA fields) whenever #PFs occur in the hardware, even if these #PFs are benign. By benign page faults we mean the ones that are handled completely by the host Linux kernel (more specifically, by the Linux SGX kernel driver).
Such benign #PF exceptions should be considered spurious -- they are reported to the SGX enclave (when `sgx.use_exinfo = true`), but they are completely resolved by the host Linux kernel and must be ignored by Gramine.
To add such functionality of ignoring spurious exceptions, the SGX asm code must be modified to forward both the trusted EXITINFO value and the untrusted external-event value to the `_PalExceptionHandler()` function.
For more …
> [PAL/Linux-SGX] Ignore spurious exceptions in exception-handling flow

- pal/src/host/linux-sgx/enclave_entry.S
- pal/src/host/linux-sgx/pal_exception.c
- pal/src/host/linux-sgx/pal_linux.h
The `_PalExceptionHandler()` function is a superset of the removed func.
CI is enough. No functional changes, just removing dead code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1571)
> [PAL/Linux-SGX] Remove redundant `_PalHandleExternalEvent()`

- Documentation/manpages/gramine-sgx-sign.rst
- Documentation/python/api.rst
- python/gramine-sgx-sign
- python/graminelibos/manifest.py
see commit message
1. Checkout this branch and build gramine.
2. Install this to your system.
3. `sed -i -e 's@file:helloworld@file:/app/helloworld@g' path/to/gramine/CI-Examples/helloworld`
4. Build `helloworld` example (only the manifest and binary, signing will come later).
5. Deboostrap an example chroot, e.g. using mmdebstrap, and install the same gramine into your chroot; copy an example into the chroot and measure it from outside. The following is a heavily modified mmdebstrap invocation I have lying aroun d (my version compiles a package using `debuild`, this version is hopefully simpler and builds using only meson):
```sh
mmdebstrap \
--customize-hook 'DESTDIR="$1" meson install -C path/to/the/build/dir' \
--customize-hook 'cp -r path/to/repo/of/gramine/CI-Examples/helloworld …
```
> [python] Add gramine-sgx-sign --chroot option

- python/graminelibos/manifest.py
- tests/test_chroot.py
See commit message and comment.
use `gramine-sgx-sign --chroot` with some Debian-based image, measuring at least one file that is symlink to absolute path (e.g. `/usr/bin/uwsgi`: `mmdebstrap --include uwsgi`). The fail is more obvious when the link destination is not present on base system (e.g. `apt-get purge uwsgi`).
Originally found by @bsulich2 and reported internally in Scaffolding project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1679)
> [python] Fix measuring absolute paths in chroots

- libos/src/sys/libos_file.c
The variable is indeed unused but may be helpful once we improve `sendfile()` implementation. Newer Clang (e.g. v14) complains about this unused variable, so let's silence Clang by adding the attribute.
Try with Clang v14 (on Ubuntu 22.04) and with `meson setup ... --werror`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1685)
> [LibOS] Add "unused" attribute to variable `read_from_in`

- pal/include/pal_internal.h
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux/pal_devices.c
- pal/src/host/linux/pal_files.c
- pal/src/host/skeleton/pal_devices.c
- pal/src/host/skeleton/pal_files.c
- pal/src/pal_streams.c
Previously, there was a bug of returning a supplied length. However, the PAL API explicitly states that this function returns 0 on success, and LibOS relied on this behavior.
I found it while working on my new PAL, on the `Event` regression test: https://github.com/gramineproject/gramine/blob/a3694193649f8dccc9cb6eb349d092e65b686c5c/pal/regression/File.c#L164
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1687)
> [PAL] Return `0` on success in `PalStreamSetLength()`

- pal/src/host/linux-sgx/host_profile.c
Gramine's embedded profiler already skips the internal Gramine vDSO library. However, we forgot to skip the host-Linux vDSO library, which resulted in a benign but annoying error message: the underlying ELF file couldn't be found by profiler, so it complained about non-existing path.
See https://github.com/gramineproject/gramine/pull/1285#issuecomment-1873809020 for explanations.
Just try out some workload with `sgx.profile.enable = "main"`. I tried with Blender.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1695)
> [PAL/Linux-SGX] Fix an error log on `[vdso]` when profile is enabled

- pal/src/host/linux-sgx/pal_linux_error.h
- pal/src/host/linux/pal_linux_error.h
Previously, both PALs forgot to convert `ENOTCONN` into an (already-existing) `PAL_ERROR_NOTCONNECTION` error code. This led to `ENOTCONN` host-Linux errors being transformed into `EACCES` for the application. This in turn confused some applications, most notably Python's `ssl.py` method `SSLSocket::_create()`.
Fixes #1694. See there for my analysis.
Do the same as in #1694.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1696)
> [PAL/Linux,Linux-SGX] Convert `ENOTCONN` to `PAL_ERROR_NOTCONNECTION`

- subprojects/packagefiles/curl-8.4.0/compile.sh
For minimization purposes, libcurl is built with most features disabled. One of the disabled features was proxy support. This made libcurl-based dependencies, such as RA-TLS libs, unusable in proxy-restricted environments (e.g. with a company-wide proxy). This commit re-enables proxy support, which increases the size of `libcurl.a` by ~7%.
Fixes #1719. See it for detailed analysis.
Try RA-TLS with EPID in a proxy environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1720)
> [curl] Re-enable proxy support in libcurl

- python/graminelibos/sigstruct.py
Fixes: #1731
Check the reproducer in #1731.
Cc: @andre-w-fischer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1732)
> [python] Pass bytes to cryptography.io's RSAPrivateKey.sign()

- libos/include/libos_fs.h
These macros were mixed up. However, they were used only in the syscall parser so this mix up didn't lead to any functionality issues. Noticed when analyzing Gramine logs; kudos to Jinen Gandhi and Anjali Rai.
Here are the links how it's implemented in Musl and Glibc, for cross reference:
- https://github.com/bminor/musl/blob/f314e133929b6379eccc632bef32eaebb66a7335/include/fcntl.h#L115-L118
- https://github.com/bminor/glibc/blob/bbd248ac0d75efdef8fe61ea69b1fb25fb95b6e7/posix/unistd.h#L281-L284
And this is the only place where these macros are used: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/libos/src/libos_parser.c#L734-L747
Fixes #1755 
Look at Gramine logs in the `access()` syscall.
- - - …
> [LibOS] Fix `R_OK` and `X_OK` macros for file permissions

- Documentation/devel/features.md
- libos/src/bookkeep/libos_vma.c
- libos/test/regression/madvise.c
Previously, it was not implemented though there is no blocker for this (only need to temporarily change permissions on the mapping to be writable). This fixes Node.js v20 workloads.
Fixes #1469.
Added a LibOS test.
Also, test Node.js v20:
- Without PR:
```
gramineproject/examples/nodejs$ gramine-direct ./nodejs helloworld.js
gramineproject/examples/nodejs$ gramine-sgx ./nodejs helloworld.js
```
- With PR:
```
gramineproject/examples/nodejs$ gramine-direct ./nodejs helloworld.js
Hello World
gramineproject/examples/nodejs$ gramine-sgx ./nodejs helloworld.js
Hello World
```
To install Node.js v20 on Ubuntu 20.04, you can use this hacky approach: https://joshtronic.com/2023/04/23/how-to-install-nodejs-20-on-ubuntu-2004-lts/. Note that the binary was renamed from `nodejs` to `node`, so when …
> [LibOS] Allow `madvise(MADV_DONTNEED)` on non-writable mappings

- tools/sgx/common/pf_util.c
mbedTLS explicitly says that CTR_DRBG operations are not thread-safe. Since we do not build mbedTLS with `MBEDTLS_THREADING_C`, we must introduce our own sync mechanism. For this, we use spinlocks.
The only identified mbedTLS function that needs this is `mbedtls_ctr_drbg_random()`. See also mbedTLS docs.
Kudos to Petr Evstifeev (Villain88) who reported this issue.
Closes #1742.
See also https://mbed-tls.readthedocs.io/projects/api/en/development/api/file/ctr__drbg_8h/#_CPPv423mbedtls_ctr_drbg_randomPvPh6size_t
CI is enough. Also can try the tool in #1742.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1746)
> [tools] Surround mbedTLS's CTR_DRBG operations with spinlocks

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
- libos/src/fs/libos_fs_encrypted.c
- tools/sgx/common/pf_util.c
Previously, Protected Files didn't have a way to ensure that the data is physically stored on disk (aka fsync). This is in contrast to the "file flush" operation, which only flushes user-space buffers to the OS kernel buffers. (Gramine confusingly uses the term "flush" to mean flush and fsync, depending on the context.)
This explicit fsync is important in e.g. persistent database workloads. It was detected on a RocksDB workload.
Unfortunately I don't know how to test this, without failing the system somehow...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1753)
> [common] Add explicit fsync callback to Protected Files

- libos/include/libos_signal.h
- libos/src/bookkeep/libos_signal.c
- libos/src/sys/libos_sigaction.c
- libos/test/regression/meson.build
- libos/test/regression/sigterm_multithread.c
- libos/test/regression/sigterm_multithread.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/test_sigterm.sh
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Some apps (e.g. MongoDB) create a separate thread that has a single job -- to wait for a SIGTERM signal and then perform graceful app termination. This special thread issues `sigtimedwait(SIGTERM)` and waits forever for this signal. Other threads instead block this signal (add it to their sigmask), so that they don't need to care about reacting to this signal.
Previously, our LibOS would try to handle SIGTERM on the thread that got chosen by the host Linux (the thread is arbitrarily chosen). But with high probability, on such apps this thread will be the not-special-one, and the app would effectively ignore SIGTERM.
This was detected on MongoDB. Snippet from MongoDB log on master branch (without this PR):
```sh
[P1:T2:mongod] trace: ---- …
```
> [LibOS] Wake up thread that can handle SIGTERM on host-injected SIGTERM

- Documentation/manifest-syntax.rst
- pal/src/host/linux-sgx/pal_exception.c
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_main.c
Commits ["[PAL/Linux-SGX] Disallow memfault handling with no faulting address reported"](https://github.com/gramineproject/gramine/commit/9f80c4245a8a852a2d6ac30c81840c94db447305) and ["[PAL/Linux-SGX] Cross-verify SW signals vs HW exceptions"](https://github.com/gramineproject/gramine/commit/a390e33e16ed374a40de2344562a937f289be2e1) hardened Gramine's exception handling in the SGX PAL. In particular, memory faults (#PF and #GP) became allowed only when the SGX EXINFO feature is available on the CPU and is enabled in the manifest (via `sgx.use_exinfo`). Otherwise Gramine immediately terminated the SGX enclave.
However, some applications (Java runtimes in particular) rely on exception handling of memory faults, even if the related MADDR (faulting address) and ERRCD (error code) have dummy …
> [Pal/Linux-SGX] Add `sgx.insecure__allow_memfaults_without_exinfo` manifest option

- common/include/slabmgr.h
- libos/src/fs/libos_fs_mem.c
Allocating the file nodes (`file_node_t`) of Gramine's encrypted files can be one source of overhead for certain workloads (e.g., RocksDB compaction). To address this performance bottleneck, this commit introduces a new slab size (8288B, considering the alignment) tailored for the size of the file node (8235B) and therefore a new free list for 8256B blocks managed by the slab allocator.
Note that while this change can improve performance for certain memory allocation patterns, it introduces internal fragmentation and may also increase memory overhead and external fragmentation if the application rarely makes allocations of the file node size.
In addition, this commit fixes an issue where in-memory files are not zeroed out when resized.
Fixes …
> [common] Add encrypted-file-node-size slab into slab allocator

- libos/src/sys/libos_alarm.c
Previously in the itimer event callback, we checked the timeout of the timer based on the value entered when the event was installed. Since we have a single global timer anyway, this check makes no sense.
See https://github.com/gramineproject/gramine/pull/1741#pullrequestreview-1859415462 for details.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1749)
> [LibOS] Remove unnecessary check in itimer event callback

- libos/include/libos_socket.h
- libos/src/fs/socket/fs.c
- libos/src/sys/libos_socket.c
On Linux, `read(socket-fd, buf, /*count=*/0)` has a special case of returning zero, after all checks. Same applies for `readv()`. However, this does *not* apply to `recvfrom()`, `recvmsg()`, `recvmmsg()`.
Linux code simply says "Match SYS5 behavior" in this corner case: https://github.com/torvalds/linux/blob/99bd3cb0d12e85/net/socket.c#L1136-L1136
Apparently some applications/libraries rely on this behavior. Without this corner case, these apps would hang (if the socket is blocking) or unexpectedly return -EAGAIN (if the socket is non-blocking). Note that the underlying PalSocketRecv() uses `recvmsg()` syscall, at least on Linux-based PALs, so a simple fall-through to PAL would change the semantics of `read()`/`readv()` issued by the app.
Found on a closed-source app.
Not sure if this …
> [LibOS] Return `0` on zero-sized `read()` syscalls on sockets

- Documentation/manifest-syntax.rst
The tmpfs limitation of not supporting mmap was fixed long ago, but we forgot to update the documentation.
See the implementation:
- https://github.com/gramineproject/gramine/blob/a50192cfe261854ef7dfa28f777f167d500cd3ba/libos/src/fs/tmpfs/fs.c#L319
- https://github.com/gramineproject/gramine/blob/a50192cfe261854ef7dfa28f777f167d500cd3ba/libos/src/fs/libos_fs_util.c#L135
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1782)
> [Docs] Remove limitation of tmpfs not supporting mmap

- common/include/arch/x86_64/cpu.h
- libos/test/regression/fork_and_access_file.c
- libos/test/regression/fork_and_access_file.gdb
- libos/test/regression/fork_and_access_file.manifest.template
- libos/test/regression/fork_and_access_file_testfile
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_streams.c
Previously, Trusted Files feature had the following bug: after fork, the metadata of currently-opened-in-parent-process TFs (SHA256 hashes for each chunk of the file) was not available in the child SGX enclave. This effectively degenerated all currently-opened TFs into Allowed Files, and thus the child enclave lost integrity guarantees in these TFs. An attacker could substitute the TF contents on the storage with arbitrary code/data, and the child enclave would not notice this.
This bug was exposed only in the child process (child SGX enclave) and only in these scenarios:
- fork without execve: the child continues reading from one of the file descriptors pointing to a trusted file opened before `fork()`;
- fork with execve: the child reads from an inherited file descriptor pointing to a …
> [PAL/Linux-SGX] Fix Trusted Files degenerating to Allowed Files on fork

- debian/changelog
- gramine.spec
- meson.build
- packaging/alpine/APKBUILD
Release PR for 1.6.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1808)
> Release 1.6.2

- CI-Examples/common_tools/benchmark-http.sh
- CI-Examples/rust/README.md
Previously, we were printing the throughput in bytes, but wrk2 gives "Req/Sec" and the throughput in bytes doesn't really make sense.
Additionally, this commit adds a note in the README of our rust example stating the need of `wrk2` when using the benchmark script.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1821)
> [CI-Examples] Fix wrong throughput unit in benchmark-http.sh

- libos/test/regression/sigaltstack.c
- libos/test/regression/test_libos.py
As in title. I don't know/remember why the test was disabled, but everything works on current Gramine master. So looks like we just forgot to re-enable this test when refactoring signaling code.
Extracted from https://github.com/gramineproject/gramine/pull/1812 (completely unrelated, just noticed while working on that PR).
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1819)
> [LibOS] test/regression: reenable `sigaltstack` test

- libos/include/libos_handle.h
- libos/src/bookkeep/libos_handle.c
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/libos_fs_pseudo.c
- libos/src/fs/libos_fs_util.c
- libos/src/fs/shm/fs.c
- libos/src/fs/tmpfs/fs.c
- libos/src/sys/libos_file.c
- libos/src/sys/libos_open.c
- libos/src/sys/libos_poll.c
- libos/src/sys/libos_wrappers.c
- libos/test/regression/eventfd_read_then_write.c
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Handles can be file-like (allow seeking and thus have a file position) and stream-like (do not allow seeking and thus file position field `pos` is unused). Previously, LibOS emulations of `read()`, `write()`, `sendfile()`, etc. did not distinguish between file-like and stream-like handles and always acquired `hdl->pos_lock`.
This led to a bug on stream-like handles, in particular, on eventfd handles: `read()` and `write()` operations are blocking for eventfds, thus a blocking `read()` would acquire the `hdl->pos_lock` indefinitely and e.g. hang another thread that performs `write()` on same eventfd.
This commit fixes this bug by skipping this lock on stream-like handles. This has an additional performance benefit: stream-like handles like pipes, sockets and eventfds don't spend cycles in …
> [LibOS] Do not perform `lock(&hdl->pos_lock)` on non-seeking handles

- meson.build
- subprojects/curl-8.5.0.wrap
- subprojects/curl-8.7.1.wrap
- subprojects/packagefiles/curl-8.7.1/compile.sh
- subprojects/packagefiles/curl-8.7.1/meson.build
This upgrade includes fixes for several CVEs affecting libcurl, specifically:
* CVE-2024-0853 (fixed in v8.6.0);
* CVE-2024-2004, CVE-2024-2398, CVE-2024-2379, CVE-2024-2466 (fixed in v8.7.0/v8.7.1).
This commit also updates the (disabled) libcurl feature list in Gramine based on the updated minimal binary size configuration recommendations from curl.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1833)
> [curl] Upgrade libcurl to version 8.7.1

- common/include/api.h
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/pal_main.c
Previously, if enclave size was very large (e.g. 2TB) its collision with some hardcoded memory regions in untrusted memory (ASan shadow map, debug info area, untrusted shared memory) caused allocation failures, leading to cryptic errors.
This commit fixes that and checks all the ranges for collisions.
The lack of these checks was _not_ a security issue, because:
- ASan range is used only in debug builds
- debug range is used also in release, but only by the untrusted PAL
- shared memory range allocation would fail in ocall_mmap_untrusted() before leaving the enclave (on pointer check)
Fixes #1787.
Modify some enclave size to e.g. 2TB. Outputs from my runs:
debug, 2TB, no fix:
```
> gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
fish: Job …
```
> [PAL] Print a nice error if enclave range collides with other regions

- libos/src/fs/chroot/encrypted.c
- libos/test/regression/sealed_file.c
Commit ["[LibOS] Allow `unlink()` on corrupted encrypted files"](https://github.com/gramineproject/gramine/commit/4dae6b0d1131dab890747cf91534a8c2fdd86357) introduced checks `if (!dent->inode->data) return -EACCES` for all encrypted-files callbacks. However, these callbacks are also used for directories of encrypted files (FS mounts in manifest file and their sub-dirs), and directories never have `inode->data` anyway. Therefore, that commit introduced a bug that encrypted-files dirs returned EACCES error on `stat()` and `chmod()`.
This PR fixes this bug by additionally checking that the inode is of "regular file" type.
Fixes https://github.com/gramineproject/contrib/issues/85.
A sub-test is added in `sealed_file` LibOS test. Also see https://github.com/gramineproject/contrib/issues/85 for …
> [LibOS] Allow `stat()` and `chmod()` on encrypted-files dirs

- libos/src/fs/chroot/fs.c
As in title. Tiny change.
Extracted from https://github.com/gramineproject/gramine/pull/1812.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1816)
> [LibOS] chroot fs: remove redundant arg in `chroot_temp_open()`

- libos/src/libos_init.c
Many subsystems rely on debug metadata (in particular, the lock for debug info) to be already initialized. This is especially true for error handling paths, which may want to remove the debug info.
Extracted from #1812.
Fixes #1813.
See #1813.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1814)
> [LibOS] Move `init_r_debug()` before `init_fs()`

- libos/src/fs/socket/fs.c
- libos/src/sys/libos_epoll.c
- libos/src/sys/libos_poll.c
Commit ["[LibOS] Add secure implementation of eventfd"](https://github.com/gramineproject/gramine/pull/1728) introduced a `post_poll()` callback which can be used to trigger additional events on specific events returned from select/poll/epoll. This commit refactors the LibOS code such that sockets-specific handling of EINPROGRESS is moved from select/poll/epoll code into this `post_poll()` callback.
CI must pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1844)
> [LibOS] Add `post_poll()` callback to network sockets

- .ci/ubuntu20.04.dockerfile
- .ci/ubuntu22.04.dockerfile
- CI-Examples/helloworld/Makefile
- Documentation/conf.py
- Documentation/manpages/gramine-manifest-check.rst
- Documentation/manpages/gramine-manifest.rst
- Documentation/requirements.txt
- debian/control
- gramine.spec
- libos/test/regression/fork_disallowed.manifest.template
- packaging/alpine/APKBUILD
- pal/regression/tests.toml
- python/gramine-manifest
- python/gramine-manifest-check
- python/graminelibos/manifest.py
- python/graminelibos/manifest_check.py
- python/graminelibos/meson.build
- python/graminelibos/util_tests.py
- python/meson.build
Linter for gramine manifest. Parser in the actual application is permissive, silently ignores unknown keys in manifest. This optional tool will warn about unknown options (probably mistyped real things!).
Fixes: #1336
Go get any manifest (and/or manifest.sgx) and feed it to this tool. If there's no output and 0 exit code, then manifest should be OK. If the manifest is not OK, exit code should be != 0 and some explanation should be written to stdout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1726)
> `gramine-manifest-check` tool

- python/gramine-manifest
See the analogous problem and discussion for `gramine-manifest-check`: https://reviewable.io/reviews/gramineproject/gramine/1726#-Nw79aKICx9Ai1ujL3Hk.
Corrupt a manifest template and try to build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1862)
> [python] Print nicer errors in `gramine-manifest`

- tests/test_sgx_sign.py
Incorrect signature length calculation could cause an `InvalidSignature` exception if the signature happened to start with a 0x00 byte, resulting in random CI failures.
Fixes #1689.
Run `while true; python3 -m pytest -v -k 'test_sign_from_pem_path' tests/; or break; end` in Gramine root and wait. Without this PR it fails after ~64 loop iterations with:
```
tests/test_sgx_sign.py:64: in test_sign_from_pem_path
verify_signature(data, exponent, modulus, signature, key_file)
tests/test_sgx_sign.py:50: in verify_signature
public_key.verify(signature_bytes, data, padding.PKCS1v15(), hashes.SHA256())
/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/rsa.py:550: in verify
_rsa_sig_verify(
/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/rsa.py:3 …
```
> [tests] Fix signature length calculation in sgx_sign tests

- CI-Examples/bash/manifest.template
- CI-Examples/blender/blender.manifest.template
- CI-Examples/busybox/busybox.manifest.template
- CI-Examples/helloworld/helloworld.manifest.template
- CI-Examples/lighttpd/lighttpd.manifest.template
- CI-Examples/memcached/memcached.manifest.template
- CI-Examples/nginx/nginx.manifest.template
- CI-Examples/python/python.manifest.template
- CI-Examples/ra-tls-mbedtls/client.manifest.template
- CI-Examples/ra-tls-mbedtls/server.manifest.template
- CI-Examples/ra-tls-nginx/nginx.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov/client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_minimal/client.manifest.template
- CI-Examples/ra-tls-secret-prov/secret_prov_pf/client.manifest.template
- CI-Examples/redis/redis-server.manifest.template
- CI-Examples/rust/rust-hyper-http-server.manifest.template
- CI-Examples/sqlite/manifest.template
- Documentation/manifest-syntax.rst
- Documentation/manpages/gramine-manifest.rst
- Documentation/manpages/gramine-ratls.rst
- Documentation/tutorials/pytorch/index.rst
- python/graminelibos/manifest.py
For end users, the `loader.entrypoint` manifest option is always the LibOS binary. Similarly, `sgx.trusted_files` must always contain the LibOS binary.
To preserve special cases like PAL tests (where `loader.entrypoint` points to the PAL test binary), we allow special `loader.entrypoint`. In this case, the LibOS binary is not appended to `sgx.trusted_files`.
I was asked too many times by casual users what the hell this is. I don't see any point in not allowing this info to go implicit.
So, it's a small user-friendliness improvement.
If folks agree that it's a good change, then I'll do the same for:
Changes CI-Examples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/grami …
> [Python,CI-Examples] Hide `loader.entrypoint` manifest option

- subprojects/packagefiles/glibc-2.39/fix-fortify-source.patch
- subprojects/packagefiles/glibc-2.39/meson.build
The new Ubuntu release, Noble, includes a version of GCC with a spec that defines `_FORTIFY_SOURCE` when optimization is enabled:
```
$ gcc -dumpspecs | grep _FORTIFY_SOURCE
%{!O0:%{O*:%{!D_FORTIFY_SOURCE=*:%{!U_FORTIFY_SOURCE:-D_FORTIFY_SOURCE=3}}}
```
However, some files in glibc need to be built without `_FORTIFY_SOURCE`, such as `vprintf.c`. The patch from Ubuntu Noble changes the method of undefining _FORTIFY_SOURCE to -U_FORTIFY_SOURCE. Previously it was limited only to the preprocessor (-Wp,-U_FORTIFY_SOURCE). The new method also undefines the definition from the spec.
The patch addresses some other non-standard redefinitions of _FORTIFY_SOURCE as well.
```
getbuildlog glibc last amd64
```
- http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/glibc_2.39-0ubuntu8.1.debian.tar.xz …
> [glibc] Fix redefinition of `_FORTIFY_SOURCE`

- libos/src/libos_init.c
- libos/src/net/unix.c
Commit ["[LibOS,PAL] Move assigning name to a pipe/UDS from PAL to LibOS"](https://github.com/gramineproject/gramine/commit/dd1d3dca50359d3a842cea7fb536896772438c12) had a small bug: the new LibOS logic lost the Gramine-instance-specific part of the name for some pipes and all UNIX Domain Sockets (UDSes).
This led to a benign but annoying bug of e.g. two `gramine-direct` Gramine instances being able to establish a common UDS. This could have been considered a feature, but two `gramine-sgx` Gramine instances would (correctly) fail to establish a common UDS, because each `gramine-sgx` instance has its own encryption key, and thus two UDSes would not be able to establish a secure TLS channel (even though they see each other because of this bug).
To make behavior of `gramine-direct` and …
> [LibOS] Make all pipe and UDS names Gramine-instance-specific

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
- common/src/protected_files/protected_files_format.h
- common/src/protected_files/protected_files_internal.h
This commit refactors PF code without changing functionality (part 1 in a series of commits). In particular, this commit removes unused functions, variables, fields, typedefs and macros.
Extracted from #1841 at the request of @mkow.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1866)
> [common] Refactor Protected Files, part 1

- pal/src/host/linux-common/topo_info.c
Currently Gramine does not work on Windows subsystem for linux (WSL) as WSL does not have a "/sys/devices/system/node/" folder, preventing the use of this common and convenient development platoform.   This PR remedies that by using reasonable default values if that folder does not exist.
This is a resurrection of earlier abandoned PR #679, updated to the latest version and also a bit cleaned up.
Usual CI should test that it doesn't break anything existing and to test on WSL, just build and run usual regression tests and some of the examples.
BTW: I've tested (successfully ;-) on WSL version 2.2.0 with kernel 5.15.150.1-microsoft-standard-WSL2  on running ubuntu 23.10. That said, i don't think specific WSL2 versions shouldn't matter much and neither should ubuntu version (beyond what is …
> [PAL] Support direct mode in Windows WSL

- libos/include/libos_fs.h
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/libos_dcache.c
- libos/src/fs/shm/fs.c
Function `chroot_dentry_uri()` is a generic function to extract the URI out of the dentry (by concatenating the URI prefix, the dentry's mount point path and the dentry relative name). Thus this function must have a generic name and must be moved to a generic dentry file.
Extracted from https://github.com/gramineproject/gramine/pull/1812.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1817)
> [LibOS] Rename `chroot_dentry_uri()` into `dentry_uri()`

- Documentation/manifest-syntax.rst
This commit is in response to customers' confusion on how to decrypt files encrypted with these keys.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1725)
> [Docs] Add notes on `_sgx_mrsigner` and `_sgx_mrenclave` encryption keys

- .ci/lib/stage-test-sgx.jenkinsfile
- Documentation/attestation.rst
- tools/sgx/ra-tls/ra_tls_verify_common.c
Omitting any of the measurement variables is now a hard error.
Try RA-TLS examples without setting some of these variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1870)
> [tools/RA-TLS] Drop deprecated `RA_TLS_*` env semantics

- common/src/protected_files/protected_files.c
This commit refactors PF code without changing functionality (part 2 in a series of commits). In particular, this commit simplifies function signatures of `ipf_read_node()` and `ipf_write_node()`.
Extracted from https://github.com/gramineproject/gramine/pull/1841 at the request of @mkow.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1867)
> [common] Refactor Protected Files, part 2

- libos/src/fs/dev/fs.c
Fixes #1267 (or at least one of the problems there, I split out the other problem to #1872).
Try `ls -la <(echo 123)` in Bash under Gramine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1873)
> [LibOS] Add `/dev/fd/` directory

- python/gramine-sgx-sign
See commit
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1880)
> [python] Add nice error message for ENOENT when measuring trusted files

- Documentation/devel/building.rst
#1726 added `python3-voluptuous` to dockfile, package control, etc. but not development instructions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1887)
> [Docs] Add `python3-voluptuous` to dependency install command

- CONTRIBUTING.rst
- Documentation/devel/howto-doc.rst
- README.rst
GitHub misrenders it, effectively leaving a triple-space which looks really ugly.
Look at the rich diff on GitHub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1892)
> [Docs] Stop using `|nbsp|` on pages rendered by GitHub

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
- common/src/protected_files/protected_files_format.h
- common/src/protected_files/protected_files_internal.h
- tools/sgx/pf_tamper/pf_tamper.c
This commit refactors PF code without changing functionality (part 4 in a series of commits). In particular, this commit re-orders variables, struct definitions, struct fields, typedefs, and macros for readability.
Extracted from https://github.com/gramineproject/gramine/pull/1841 at the request of @mkow.
Note that this PR is based on https://github.com/gramineproject/gramine/pull/1866.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1869)
> [common] Refactor Protected Files, part 4

- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/enclave_ocalls.h
- pal/src/host/linux-sgx/enclave_platform.c
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/host_platform.c
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux-sgx/pal_ocall_types.h
- pal/src/host/linux-sgx/sgx_attest.h
Gramine uses the AESM daemon to request SGX Quotes from the Quoting Enclave. AESM runs in the background and may be restarted. For some reason, after a restart AESM "forgets" the platform's attestation key and requires an additional INIT_QUOTE_REQUEST before it is able to generate SGX Quotes again. Moreover, the Quoting Enclave's Target Info may change at this point, so Gramine must update its cached QE Target Info. This behavior is applicable only to DCAP attestation and is documented in Intel SGX PSW/DCAP software. Gramine didn't implement this behavior and thus failed with "AESM service returned error 42".
This PR complies with the SGX PSW/DCAP documentation and adds the send of INIT_QUOTE_REQUEST + update of QE Target Info + retry of SGX quote retrieval.
This is a re-creation of …
> [PAL/Linux-SGX] Re-init attestation key after AESM restarted

- libos/src/fs/pipe/fs.c
- libos/test/ltp/ltp.cfg
- libos/test/regression/mkfifo.c
Previously, FIFO pseudo-files (named pipes) did not have callbacks of `stat()` (used on FIFO filenames) and `hstat()` (used on FIFO handles/FDs). This breaks some apps that want to double-check that the file they have opened or want to open is a FIFO, using the `stat()` or `fstat()` syscalls. There was no good reason to skip those callbacks, so this commit adds their dummy implementations.
Fixes #1896.
Added some sub-tests in LibOS, and activated `read03` in LTP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1897)
> [LibOS] Add `stat()` and `hstat()` callbacks to FIFOs

- common/include/nodiscard.h
- common/include/pal_error.h
- meson.build
Change the build system to use C23 or C2x (the experimental version of C23 used before the official release). We plan to convert functions to return pal_error_t instead of int. This will be implemented in separate commits, each making small, incremental changes.
This commit is done also to enforce a new policy on a new code.
The `__has_c_attribute` is used to check the availability of new attributes. It was added simultaneously with `nodiscard` in the experimental version: https://gcc.gnu.org/gcc-11/changes.html.
Documentation for __has_c_attribute can be found at: https://en.cppreference.com/w/c/language/attributes.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gra …
> Enable C23 when available and nodiscard feature

- .ci/debian11.dockerfile
- .ci/debian12.dockerfile
- .ci/lib/config-docker.jenkinsfile
- .ci/lib/stage-build-sgx.jenkinsfile
- .ci/linux-direct-sanitizers.jenkinsfile
- .ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile
- .ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- .ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile
- .ci/linux-sgx-ubuntu24.04-gcc-release.jenkinsfile
- .ci/ubuntu20.04.dockerfile
- .ci/ubuntu22.04.dockerfile
- .ci/ubuntu24.04.dockerfile
- Documentation/devel/packaging.rst
- scripts/download
`noble` was released on 25.04.2024. From Gramine 1.8 we'll support `noble` and `jammy` so it's about time to have those in CI. 
check CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1843)
> Ubuntu `jammy` and `noble` (22.04 LTS and 24.04 LTS)

- libos/src/sys/libos_file.c
- libos/test/regression/meson.build
- libos/test/regression/rename_unlink.c
- libos/test/regression/rename_unlink_fchown.c
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
This is conceptually similar to the commit ["[LibOS] Fix `ENOENT` error in `fchmod` on unlinked file"](https://github.com/gramineproject/gramine/commit/ac8fc770d1004dbcaf43a5b805a7928b7c4fb90f).
This PR was created while reviewing #1874.
Added a sub-test to the `rename_unlink` LibOS regression test.
If you want to run this sub-test on vanilla Linux, change UID and GID in `fchown()` to some reasonable IDs available on your system.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1875)
> [LibOS] Fix `ENOENT` error in `fchown` on unlinked file

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
- common/src/protected_files/protected_files_format.h
- common/src/protected_files/protected_files_internal.h
This commit refactors PF code without changing functionality (part 5 in a series of commits). In particular, this commit moves code around, rephrases some comments, removes useless comments and empty lines, as well as renames vague `data` and `block` words to more specific `node`.
This PR supersedes #1894.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1899)
> [common] Refactor Protected Files, part 5

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files_format.h
This commit refactors PF code without changing functionality (part 6 in a series of commits). In particular, this commit renames ambiguous `node_number` fields/variables to `physical_node_number` or `logical_node_number`, depending on the context.
This PR supersedes https://github.com/gramineproject/gramine/pull/1894.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1907)
> [common] Refactor Protected Files, part 6

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
- common/src/protected_files/protected_files_format.h
- common/src/protected_files/protected_files_internal.h
- tools/sgx/pf_tamper/pf_tamper.c
This commit refactors PF code without changing functionality (part 7 in a series of commits). In particular, this commit renames:
- "key_id" to a more correct "nonce"
- "encrypted_part_plain" to "metadata_decrypted" (i.e. decrypted conents of the encrypted part of the metadata node)
- "file" to a more specific "host_file_handle"
- "file_metadata" to a more correct "metadata_node"
- "root_mht" to a more specific "root_mht_node"
This PR supersedes https://github.com/gramineproject/gramine/pull/1894.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1908)
> [common] Refactor Protected Files, part 7

- libos/include/libos_fs.h
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/shm/fs.c
It is a bad smell to reuse functions intended for another subsystem. Also, a future commit will modify `chroot_unlink()` such that `shm` FS won't be able to reuse it.
Extracted from #1812.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1815)
> [LibOS] Do not reuse `chroot_unlink()` in `shm` filesystem

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files_format.h
- tools/sgx/pf_tamper/pf_tamper.c
This commit refactors PF code without changing functionality (part 9 in a series of commits, last one). In particular, this commit renames:
- ambigious "data" and "cipher" to "bytes", because "data" is already used to denote data file nodes
- "mht_key" and "mht_mac" to "root_mht_node_key" and "root_mht_node_mac"
- "size", "path", "data" to "file_size", "file_path", "file_data"
This PR supersedes https://github.com/gramineproject/gramine/pull/1894. And finally closes this series of refactorings.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1919)
> [common] Refactor Protected Files, part 9

- pal/src/host/linux-common/topo_info.c
- subprojects/packagefiles/mbedtls/include/mbedtls/config-pal.h
Two issues fixed:
- Unused for-loop variable `input_i` in `topo_info.c`
- Required ASN.1 dependencies for RSA in `mbedtls/config-pal.h`
This was detected on Ubuntu 24.04 and Clang 18. I don't know why I didn't observe this before; one of newer Ubuntu or Clang is the culprit.
Regarding the second issue, I also submitted an issue to mbedTLS team: https://github.com/Mbed-TLS/mbedtls/issues/9312
Build with Ubuntu 24.04 and Clang 18 (default on 24.04).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1923)
> [PAL,mbedtls] Fix build issues on newer Ubuntu and Clang

- Documentation/performance.rst
- pal/src/host/linux-sgx/host_exception.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/host_perf_data.c
- pal/src/host/linux-sgx/host_profile.c
Currently Gramine don't support flushing sgx profiling data if user wants to collect only for a particular duraion (e.g., only during perf benchmarking runs). This PR add feature to flush the profile data on demand using `SIGUSR1` signal. That way user can collect data only for a particular duration. This also eliminates the noise added in profile data duing start and stop of the process.
Partially fixes issue #1711
Please follow the instruction [here](https://gramine.readthedocs.io/en/latest/performance.html#sgx-profiling) to enable SGX profiling. Now execute the workload in Gramine SGX. Send `SIGUSR1` signal using command `kill -SIGUSR1 <pid>` to flush the profile data. This should create a sgx profile data file which can be opened using `perf report` command.
Example:
1. Add below …
> Flush profile data on demand using `SIGUSR1` signal

- common/include/arch/x86_64/cpu.h
- common/src/arch/x86_64/cpu.c
- common/src/arch/x86_64/meson.build
- libos/test/regression/in_out_instruction.c
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/src/host/linux-sgx/pal_exception.c
Fixes #1191 : ```in``` and ```out``` instructions cause ```SIGILL``` instead of ```SIGSEGV```. ```in``` and ```out``` instructions aren't allowed inside SGX enclaves and hence throws ```SIGILL``` but native behavior of user applications is that ```in``` / ```out``` instructions throw ```SIGSEGV```. ```lscpu``` is requires this fix and ```lscpu``` is sometimes used in tensorflow applications and that is why this was required.
https://c9x.me/x86/html/file_module_x86_id_139.html (for IN instruction)
https://c9x.me/x86/html/file_module_x86_id_222.html (for OUT instruction)
https://c9x.me/x86/html/file_module_x86_id_139.html
https://stackoverflow.com/questions/3215878/what-are-in-out-instructions-in-x86-used-for
https://stackoverflow.com/questions/46642384/how-to-run-code-that-uses-x86-in-and-o …
> [LibOS] Emulate in/out instructions as if they generate SIGSEGV

- common/src/avl_tree.c
- common/src/ubsan.c
- libos/src/fs/sys/fs.c
- libos/src/libos_syscalls.c
- libos/src/net/unix.c
- pal/src/host/linux-sgx/pal_main.c
- pal/src/pal_rtld.c
Newer Clang versions added more UBSan checks, in particular:
- `-fsanitize=pointer-overflow` check was extended to catch the cases where a non-zero offset is applied to a null pointer, or the result of applying the offset is a null pointer.
- `fsanitize=function`: Indirect call of a function through a function pointer of the wrong type.
This commit adds the scaffolding for the second (new) check plus fixes the places triggered by this check. This commit also fixes UBs found by the extended first check.
See:
- https://github.com/llvm/llvm-project/blob/1462605ab0a121fc2f652f178c7c13dc0179f10e/compiler-rt/lib/ubsan/ubsan_handlers.cpp#L925-L958
- https://github.com/llvm/llvm-project/blob/b579aacc30bc02e8430c0b59af644f52ece71160/compiler-rt/lib/ubsan/ubsan_handlers.h#L235-L238
- …
> [common] Update UBSan to be compatible with Clang 18

- common/include/asan.h
- common/src/asan.c
Newer Clang versions added more ASan callbacks, in particular `__asan_register_elf_globals()` and `__asan_unregister_elf_globals()`. Our code replicates exactly what the Clang/LLVM code does for these two callbacks.
See:
- https://github.com/llvm/llvm-project/blob/8f63d154ec996cba590a83a4542dd545c78af85c/compiler-rt/lib/asan/asan_globals.cpp#L346-L364
Why these callbacks were added exactly, I am not sure. All I understand is that in some mode, on ELF-based platforms, these callbacks are called instead of a more generic `__asan_register_globals()`. See these links, maybe someone will get a better understanding of this change:
- https://github.com/llvm/llvm-project/commit/4094d9a1276e7d31324cd0c075fc40890befc3ac
- https://github.com/llvm/llvm-project/pull/96529
- …
> [common] Update ASan to be compatible with Clang 18

- libos/test/regression/meson.build
- libos/test/regression/pipe_race.c
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux-sgx/pal_pipes.c
Pipes in Linux-SGX PAL are automatically encrypted using mbedTLS's SSL/TLS sessions (aka contexts). By design, an mbedTLS SSL/TLS context is assumed to be used within a single thread and thus does not use any locking. In Gramine, though, the pipe and its associated SSL/TLS context can be used in multiple threads. Without protecting pipe read/write operations with a lock, mbedTLS internal handling of the context would exhibit data races, leading to e.g. -EACCES in Gramine.
This bug was detected on a private workload. This bug can be considered a regression, introduced in [commit "[LibOS] Do not perform lock(&hdl->pos_lock) on non-seekable handles"](https://github.com/gramineproject/gramine/commit/ec06c32366672b3dfc19f539d16d37c6449ab4ca). That commit, among other things, removed the …
> [PAL/Linux-SGX] Add locking around read/write on encrypted pipes

- libos/include/libos_fs_pseudo.h
- libos/src/fs/sys/cache_info.c
- libos/src/fs/sys/cpu_info.c
- libos/src/fs/sys/fs.c
- libos/src/fs/sys/node_info.c
This is e.g. required by the gemm-common Rust crate, see `gemm-common/src/cache.rs`. Without this file, the crate logic incorrectly calculates shared-cpu count as zero and leads to a division-by-zero exception.
See:
- https://crates.io/crates/gemm-common
- https://github.com/sarah-ek/gemm/blob/8cdc1de4af69ce3fd2575b2c983fc1ccc974425f/gemm-common/src/cache.rs#L128
Detected while trying to run Candle: https://github.com/huggingface/candle/tree/0.6.0
Use Busybox for manual checks:
```
~/gramine-tdx/CI-Examples/busybox$ gramine-direct busybox sh
cat /sys/devices/system/cpu/cpu1/cache/index0/shared_cpu_list
1,65
cat /sys/devices/system/cpu/cpu1/cache/index3/shared_cpu_list
0-31,64-95
cat /sys/devices/system/cpu/cpu0/cache/index1/shared_cpu_list
0,64
cat …
```
> [LibOS] Add `shared_cpu_list` file to sysfs cache info

- tools/sgx/ra-tls/ra_tls_attest.c
- tools/sgx/ra-tls/ra_tls_common.h
- tools/sgx/ra-tls/ra_tls_verify_common.c
- tools/sgx/ra-tls/ra_tls_verify_dcap.c
- tools/sgx/ra-tls/ra_tls_verify_epid.c
Previously, `extract_quote_and_verify_pubkey()` returned a pointer to the SGX quote located inside the X.509 certificate. This is a confusing pattern, so this commit introduces a copy operation, to copy the SGX quote into a newly allocated object whose ownership is passed to the callers of this func.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1947)
> [tools/RA-TLS] Copy quote from X.509 cert into a separate object

- python/graminelibos/manifest.py
Commit "[PAL] Validate entrypoint ELF file separately" introduced a warning message during invocation of `gramine-manifest` if the manifest template has a deprecated `loader.entrypoint = "file:..."` syntax.
This warning message was erroneously printed to stdout, but stdout is used in `gramine-manifest` tool to output the rendered manifest file itself. This commit fixes that blooper by printing to stderr.
Fixes gramineproject/examples#103
See https://github.com/gramineproject/examples/issues/103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1953)
> [python] `gramine-manifest`: print warning to stderr

- pal/src/host/linux-sgx/pal_tcb.h
No idea why it was used and who introduced it. Git history ends in our infamous "First commit".
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1954)
> [PAL/Linux-SGX] Remove unused `dummy_debug_variable`

- pal/src/host/linux-sgx/enclave_ocalls.c
Previously, there was a data race that the exitless-OCALL logic read the result of the OCALL from the stack *after* the code reset the stack. However, this stack is shared with the AEX flows. As of now, the AEX flows use the stack only in debug mode, so this data race flew under the radar for a long time. What can happen is that right-before reading the result of the exitless OCALL, the enclave thread is interrupted, an AEX logic is executed and modifies the values on the stack, then the exitless-OCALL logic is resumed, and the enclave thread reads an AEX-modified OCALL result value.
Future commits (e.g., AEX-Notify) will introduce more AEX flows and expose this data race. So let's fix it now.
This was detected while working on #1857 and #1944. The same problem is exhibited also in …
> [PAL/Linux-SGX] Read exitless-OCALL result before resetting the stack

- libos/include/libos_vma.h
- libos/src/bookkeep/libos_vma.c
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/libos_fs_util.c
- libos/src/fs/tmpfs/fs.c
This commit refactors repetitive invocations of file-mapping related functions `prot_refresh_mmaped_from_file_handle()` and `reload_mmaped_from_file_handle()` into a new convenience function.
Fixes #1931.
~~Applies on top of #1818.~~
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1956)
> [LibOS] Introduce `refresh_mappings_on_file()` convenience func

- debian/gramine.install
- gramine.spec
- subprojects/packagefiles/libcbor-0.11.0/meson.build
Commit ["[tools/sgx] Modify RA-TLS to adhere to Interoperable RA-TLS standard"](https://github.com/gramineproject/gramine/commit/71fa288885d3fd8d8d23ca88156c69957c055c43) introduced libcbor static lib as a new dependency of RA-TLS libraries. However, the commit forgot to install this static lib. Installation is required so that RA-TLS plugins can re-use this libcbor library together with RA-TLS libs. Moreover, Meson v1.5.1 spits an error if libcbor is not installed.
Fixes #1962.
Try to build & install Gramine on a system with latest Meson (v1.5.1)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1963)
> [meson] Install libcbor static lib together with RA-TLS libs

- pal/src/host/linux-sgx/host_main.c
We're modifying this structure dynamically since we introduced support for dynamic TCS. The modification code in `add_dynamic_tcs()` has no way of knowing whether the allocation failed or succeeded, thus it has no way to decide whether writing there is legal or not.
This PR guarantees that the stucture is always allocated.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1968)
> [PAL/Linux-SGX] Error out on enclave_dbginfo allocation failure

- Documentation/manpages/gramine-manifest.rst
- python/gramine-manifest
Any built-in manifest validation failure is now a hard error.
CI + manual testing w/ non-compliant manifests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1975)
> [python] `gramine-manifest`: error out on manifest check failure

- Documentation/devel/features.md
- Documentation/manifest-syntax.rst
- libos/src/bookkeep/libos_handle.c
- libos/src/sys/libos_getrlimit.c
- libos/test/regression/meson.build
- libos/test/regression/rlimit_nofile.c
- libos/test/regression/rlimit_nofile_4k.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
- python/graminelibos/manifest_check.py
This manifest option allows to modify the original `RLIMIT_NOFILE` resource limit. There is *no* way to propagate this limit from the host; this is a deliberate design choice.
See discussion in https://github.com/gramineproject/gramine/discussions/1964.
Fixes #1576.
Added two LibOS tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1973)
> [LibOS] Introduce `sys.fds.limit` manifest option

- libos/test/ltp/ltp.cfg
Previously, `fork06` LTP test had a default timeout of 30 seconds, which translated to 60 seconds under AddressSanitizer builds (due to scaling factor of 2). However, our new Jenkins CI is based on wimpy VMs, and the default timeout of 60 is not enough for ASan-enabled CI jobs anymore.
Found while working on #1984.
CI is enough.
Without this PR, our current CI prints errors like this on `Jenkins-Direct-Sanitizers`:
```
_______________________________ test_ltp[fork06] _______________________________
[gw3] linux -- Python 3.8.10 /usr/bin/python3
test_ltp.py:196: in test_ltp
returncode, stdout, _stderr = run_command(full_cmd, timeout=timeout, can_fail=True)
../../../usr/lib/python3.8/site-packages/graminelibos/regression.py:157: in run_command
raise AssertionError('Command {} timed out after …
```
> [tests] Increase timeout of `fork06` LTP test

- libos/include/libos_process.h
- libos/src/bookkeep/libos_handle.c
- libos/src/sys/libos_getcwd.c
- libos/src/sys/libos_open.c
This fixes two cases where a dentry->inode derefernce was not lock-protected.  It also adds a missing call to `put_handle` during error handling and (in a separate commit) removes an unused function.
Usual regression tests ...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1978)
> [LibOS] Add missing locks around dentry->inode dereference 

- CONTRIBUTING.rst
- libos/include/libos_internal.h
- libos/src/fs/dev/attestation.c
- libos/src/libos_init.c
- libos/src/meson.build
- libos/src/utils/warn.c
- pal/include/pal/pal.h
- pal/src/host/linux-sgx/pal_main.c
- pal/src/host/linux/pal_main.c
Previously, `print_warnings_on_insecure_configs()` function was in Linux-SGX PAL. However, since almost all insecure manifest configurations are processed in the LibOS layer, it makes sense to move the printing of warnings about these configs from PAL to LibOS. This has an additional benefit of deduplicating this printing across all "confidential computing" PALs (currently there is only SGX, but in future Gramine may have TDX, AMD-SEV, etc.).
This is a recreation of #1984, rebased on top of current master (instead of `dimakuv/libos-allowed-and-trusted-files`).
Closes #1984.
Fixes #1981.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1986)
> [LibOS] Move `print_warnings_on_insecure_configs()` to LibOS

- pal/src/host/linux-sgx/pal_exception.c
- pal/src/host/linux/pal_exception.c
- Logging every raw syscall helps identify how often they occur. If it's too many, then that might cause performance issues, but if it's rare, we can ignore the performance angle
- Printing messages for every syscall captures information about multiple raw syscalls rather than just the first one.
- Printing the syscall address helps to find the library to which the syscall belongs without modifying Gramine code
- To build gramine, use meson and ninja commands. Then, for any workload (eg tested on pytorch), modify the manifest file to change log_level to trace, and you will see the raw syscalls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1991)
> Add log_trace for raw syscalls

- libos/include/libos_utils.h
- libos/src/libos_async.c
- libos/src/sys/libos_exit.c
The async worker thread is currently spawned on-demand and terminated after an idle timeout. This is entirely unnecessary — the cost of having a persistent async thread is near-0, and it simplifies the logic.
Fixes gramineproject/graphene#440.
Already covered by CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1992)
> [LibOS] Make async worker persistent

- pal/src/host/linux-sgx/host_framework.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_main.c
Inspired by #1997, maybe in the future it will save one round trip while debugging other people's computers. 
```
cd helloworld
make SGX=1
truncate -s 0 helloworld.sig  # or any number != 1808
gramine-sgx helloworld
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1998)
> [PAL/Linux-SGX] Add diagnostics to error message about sigstruct size

- .ci/alpine3.17.dockerfile
- pal/regression/AttestationReport.c
- pal/regression/Event.c
- pal/regression/Exception.c
- pal/regression/Exception2.c
- pal/regression/Hex.c
- pal/regression/Misc.c
- pal/regression/Process4.c
- pal/regression/Thread.c
- pal/regression/Thread2.c
- pal/regression/avl_tree_test.c
- pal/regression/ipv4_parser.c
- pal/regression/ipv6_parser.c
- pal/regression/memory.c
- pal/regression/normalize_path.c
- pal/regression/printf_test.c
- pal/regression/send_handle.c
- pal/regression/strtoll_test.c
Split from #1904
compile with ubsan on Ubuntu 24.04 and run
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2002)
> [PAL] Fix main() signature in regression tests for UBSan

- Documentation/manifest-syntax.rst
- Documentation/performance.rst
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/host_thread.c
- pal/src/host/linux-sgx/pal_tcb.h
Previously, when manifest contained `sgx.enable_stats = true`, Gramine-SGX printed not the process-wide SGX statistics, but also statistics for each thread. These thread-local SGX statistics only litter the output as (1) there are helper Gramine threads that do not correspond to any application thread, (2) there is no way to correlate the printed thread-local stats to application threads/workload execution (as stats simply print the opaque TID of the thread).
This PR removes thread-local stats and keeps only process-wide ones.
The Helloworld CI example (with `sgx.enable_stats = true`):
- With this PR:
```
gramineproject/gramine/CI-Examples/helloworld$ gramine-sgx helloworld
Gramine is starting. Parsing TOML manifest file, this may take some time...
----- SGX enclave loading time = …
```
> [PAL/Linux-SGX] Remove printing of thread-local SGX statistics

- Documentation/manifest-syntax.rst
- Documentation/performance.rst
- libos/test/regression/fork_and_access_file.manifest.template
- libos/test/regression/multi_pthread.manifest.template
- libos/test/regression/multi_pthread_exitless.manifest.template
- pal/regression/Thread2.manifest.template
- pal/regression/Thread2_exitless.manifest.template
- pal/src/host/linux-sgx/host_entry.S
- pal/src/host/linux-sgx/host_exception.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/host_thread.c
- pal/src/host/linux-sgx/pal_tcb.h
This commit adds support to dump and reset SGX-related statistics interactively, using SIGUSR1 signal. This helps to collect SGX-related statistics only for a particular period, e.g. skipping the Gramine startup and application initialization time and concentrating only on the actual application processing.
The printed-out statistics are not precise, as the "stats collecting" thread may run in parallel with other threads that update the statistics. However, this imprecise implementation is simple and enough for perf analysis.
This commit also breaks compatibility: SGX statistics can only be collected and printed when Gramine is built in debug or debugoptimized mode. However, this should not affect users as SGX stats is tailored for manual debugging and profiling sessions.
Applied on top …
> [PAL/Linux-SGX] Print SGX stats on SIGUSR1 and reset them

- pal/src/host/linux-sgx/pal_misc.c
UBSan detects an uninitialized boolean variable on a DCAP SGX machine on the remote attestation example, failing with the message:
error: ubsan: load of invalid value for bool or enum: 100
error: ubsan: ../pal/src/host/linux-sgx/pal_misc.c:724:43
This happens because `bool linkable` variable is assigned only in the EPID attestation scheme, but left unassigned in the DCAP scheme. This commit fixes this (though it's not a bug since DCAP never uses `linkable` anyway). Hence, UBSan doesn't complain anymore.
Reported by @woju 
Run LibOS regression test `attestation` on Ubuntu 24.04 + UBSan enabled + DCAP attestation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2004 …
> [PAL] Fix `attestation` LibOS regression test for UBSan

- pal/regression/memory.c
Newer Clang versions (v18 and newer) added more UBSan checks that triggered UBSan on PAL regression tests. In particular, UBSan added the check "Indirect call of a function through a function pointer of the wrong type". UBSan expects all functions which can be indirectly called to be instrumented with two magic metadata values, located right-before the function in address space.
The `memory` test however does *not* add this required metadata to a dummy generated-on-the-fly function (it simply allocates some pages and copies the asm code at the beginning of the first page). Instead of adding UBSan-required metadata, we simply disable this particular check (it's a test after all, not core Gramine functionality).
References:
- https://maskray.me/blog/2022-12-18-control-flow-integrity#fsanitiz …
> [PAL] Fix `memory` PAL regression test for UBSan

- libos/test/ltp/Makefile
Currently used version of LTP has a bug that results in the following build error, e.g. when using Clang v18 on Ubuntu 24.04:
clone301.c:136:8: error: call to undeclared function 'pidfd_send_signal'
This is because Clang promoted "implicit function declaration" check from a warning to an error starting from Clang v16. This commit adds `-Wno-implicit-function-declaration` flag to CFLAGS during LTP build.
Newer LTP releases fixed this bug, so in the future, when Gramine uses newer LTP, this commit should be reverted.
Reported by @woju.
Build LTP with Clang on Ubuntu 24.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2005)
> [tests] Add `-Wno-implicit-function-declaration` for LTP build

- .ci/lib/stage-test-sgx.jenkinsfile
- .ci/sgx_default_qcnl.conf
- .ci/ubuntu20.04.dockerfile
- .ci/ubuntu22.04.dockerfile
- .ci/ubuntu24.04.dockerfile
- CI-Examples/common_tools/benchmark-http.sh
- libos/test/regression/openmp.manifest.template
See #2026 for rationale
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2028)
> [CI] Ubuntu 24.04 and 22.04 part 3/?

- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- libos/test/ltp/ltp.cfg
See #2026 for rationale
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2029)
> [CI] Ubuntu 24.04 and 22.04 part 4/?

- .ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile
- .ci/linux-sgx-ubuntu24.04-gcc-release.jenkinsfile
- CI-Examples/ra-tls-mbedtls/Makefile
- libos/test/regression/test_libos.py
See #2026 for rationale
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2030)
> [CI] Ubuntu 24.04 and 22.04 part 5/?

- CI-Examples/nginx/Makefile
Commit aef087f "[[LibOS] Move trusted and allowed files logic to LibOS]" modified the Nginx `Makefile` after which it was observed that all the test data files (`install/html/random`) are generated after the manifest file generation and hence were not added as `sgx.trusted_files` in manifest.sgx file. 
Fixes #2016 
1. Git clone gramine repo `git clone https://github.com/gramineproject/gramine.git`.
2. Go to `CI-Examples/nginx` folder.
3. Execute `make SGX=1` command.
4. The test data files will be added as part of `sgx.trusted_files` within the manifest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2018)
> [CI-Examples] Add Nginx test data files measurements within the manifest

- pal/src/host/linux/pal_memory.c
Linux can return `-ENOMEM` if a request to `mmap()` exceeds the process's maximum number of mappings. After commit c0a2765 "[LibOS,PAL/Linux-SGX] Add EDMM lazy allocation support", this can occur during the checkpoint/restore on the Linux PAL. In such case, each committed page is sent separately and Linux creates a mapping for each one, which can result in a large number of mappings.
This commit makes this failure more visible and provides a hint to the user on what can be done on the host.
Related to https://github.com/gramineproject/examples/issues/107.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2023)
> [PAL/Linux] Log a message on `mmap()` returning `-ENOMEM`

- Documentation/installation.rst
Because keys for new distros were rotated, the download paths got extra `$(lsb_release -sc)`.
No change for RPM, because there's no `.el10` repo.
Install (for `noble`, use `unstable-` for gramine repo, and `mantic` for intel's repo).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1993)
> [Docs] Installation docs for 1.8

- libos/src/libos_init.c
- libos/test/regression/meson.build
- libos/test/regression/rlimit_stack.c
- libos/test/regression/rlimit_stack.manifest.template
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
Previously, the resource limit `RLIMIT_STACK` (maximum size of the process stack, in bytes) was overwritten in the child process, after fork. Thus, if the parent used `setrlimit(RLIMIT_STACK)`, the effect of this was lost in the child. This PR fixes this bug, and adds a LibOS test to verify the correct behavior.
Fixes #1974 
Noticed while reviewing #1973.
New LibOS test was added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1976)
> [LibOS] Fix bug of `RLIMIT_STACK` being overwritten in child

- .mailmap
- Documentation/management-team.rst
This PR should be merged at or around Friday, when Dmitrii's maintainership ends, WRT decision #2043 (proposed by Dmitrii himself).
The commit dates were doctored to 01.11.2024 00:00 UTC, please don't break that accidentally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2046)
> Retire Dmitrii Kuvaiskii from active maintainers

- CI-Examples/README.md
- CI-Examples/blender/Makefile
- CI-Examples/busybox/Makefile
- CI-Examples/helloworld/Makefile
- CI-Examples/lighttpd/Makefile
- CI-Examples/lighttpd/README.md
- CI-Examples/memcached/Makefile
- CI-Examples/nginx/Makefile
- CI-Examples/nginx/README.md
- CI-Examples/python/Makefile
- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-secret-prov/Makefile
- CI-Examples/redis/Makefile
- CI-Examples/rust/Makefile
- CI-Examples/sqlite/Makefile
Part of the 20.04 deprecation - we can finally use modern and less buggy tools!
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2050)
> [CI-Examples] Drop hacks in Makefiles for old Make versions

- common/include/list.h
[LibOS] Fix memmgr free list performance bug
Fixes the memmgr performance bug described in #2033 by changing the `CHECK_LIST_HEAD` macro in `common/include/list.h` in release mode to `(void)0`.
To fix the issue described in #2033, this PR surrounds the `CHECK_LIST_HEAD` macro defined in 
[common/include/list.h](https://github.com/gramineproject/gramine/blob/a08a455d7910dff7c202d61a19466cb049fc72fb/common/include/list.h) 
with `#ifdef DEBUG`. In release mode, the macro is now replaced with `(void)0`.
This macro is currently only used in `memmgr.h`. Thus, changing it directly was the simplest fix of the performance bug.
Fixes #2033
- - - …
> [LibOS] Fix memmgr free list performance bug

- debian/control
- gramine.spec
- packaging/alpine/APKBUILD
- python/graminelibos/sgx_sign.py
- tests/test_sgx_sign.py
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2053)
> [python] Stop using deprecated cryptography.io's `backend` argument

- Documentation/devel/features.md
- libos/include/libos_fs.h
- libos/src/fs/chroot/encrypted.c
- libos/src/fs/chroot/fs.c
- libos/src/fs/tmpfs/fs.c
- libos/src/sys/libos_file.c
- libos/src/sys/libos_open.c
- libos/test/fs/common.c
- libos/test/fs/common.h
- libos/test/fs/meson.build
- libos/test/fs/read_append.c
- libos/test/fs/test_fs.py
- libos/test/fs/test_tmpfs.py
- libos/test/fs/tests.toml
- libos/test/ltp/ltp.cfg
- libos/test/ltp/ltp_sgx.cfg
This PR adds `O_APPEND` emulation, but only within a single process.
Note that Gramine doesn't support multi-process operations on the same file anyhow, in particular, the file position is not synchronized among multiple processes. This PR doesn't change this limitation of Gramine, thus `O_APPEND` writes don't work correctly (may overwrite file contents).
Note that Linux has a bug in `pwrite()`. Gramine emulates this bug in the same way.
Fixes #1921.
See also:
- https://github.com/gramineproject/gramine/issues/584
- https://github.com/gramineproject/gramine/issues/1152
A new FS test is added. One LTP test is uncommented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gra …
> [LibOS] Add `O_APPEND` emulation for single process

- .ci/docs.jenkinsfile
- Documentation/conf.py
Fixes: #2066
```sh
READTHEDOCS=1 READTHEDOCS_VERSION=stable make -C Documentation html
firefox Documentation/_build/html/run-sample-application.html
```
and look at the `git clone` invocation in the first listing. `make html` should be successful, but no `--branch` in the listing. Now:
```sh
make -C Documentation clean
git tag v123456-do-not-push
READTHEDOCS=1 READTHEDOCS_VERSION=stable make -C Documentation html
firefox Documentation/_build/html/run-sample-application.html
```
should succeed and have `--branch v123456-do-not-push` in the listing.
Remember to
```sh
git tag -d v123456-do-not-push
```
before you push.
(Before this commit `READTHEDOCS=... make` will fail as in https://readthedocs.org/projects/gramine/builds/26350000/)
- - - …
> [Docs] Fix `--branch` magic to not collide variable with sphinx tags

- libos/test/fs/README.md
- libos/test/fs/conftest.py
- libos/test/fs/test_enc.py
- libos/test/fs/test_fs.py
- tools/sgx/pf_tamper/pf_tamper.c
Test `test_500_invalid` always failed as test files to decrypt _always_ had an illegal filename masking the actual intended tampering.   Fixing this in `libos/test/fs/test_enc.py` showed that a number of intended tampering use-cases in fact were uncatchable.  This PR fixes the file path in the test driver `test_nec.py`, removes ineffective tampering use-cases and adds some tampering with ciphertext on headers.
The PR also (in a separate commit) improves debuggability of python tests by optionally allow to skip the teardown of the test artifacts and run all tests for 500 instead of aborting on first failure.
Run usual regression tests
- - - …
> [tests] Fix tampering tests for protected files

- Documentation/tutorials/pytorch/index.rst
This Pull Request (PR) addresses documentation updates in the Gramine project, influenced by changes made in https://github.com/gramineproject/examples/pull/109
This PR should be merged after the completion and merging of https://github.com/gramineproject/examples/pull/109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2063)
>  [Docs] Update PyTorch tutorial

- .readthedocs.yaml
See announcement:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
Needs to build correctly in RTD, see https://readthedocs.org/projects/gramine/builds/
This PR needs to be merged before 6.01.2024, or we risk failing documentation builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2077)
> [Docs] Add explicit path to conf.py

- CI-Examples/ra-tls-secret-prov/README.md
Updated `README.md` in `CI-Examples/ra-tls-secret-prov` to include:
- Setup instructions and commands for `RA_TLS_MRSIGNER`, `RA_TLS_MRENCLAVE`, `RA_TLS_ISV_PROD_ID`, and `RA_TLS_ISV_SVN` environment variables.
- Added `make check_dcap` command.
For more details, refer https://github.com/gramineproject/gramine/pull/1870
If this measurement variables are not set, you may face issues such as:
```
Allowing quote status SW_HARDENING_NEEDED
getenv_critical: ERROR: A required environment variable RA_TLS_MRSIGNER is not set.
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -12288
client_connection: ra_tls_verify_callback_results:
attestation_scheme=2, err_loc=5, 
client_connection:     dcap.func_verify_quote_result=0x0, dcap.quote_verification_result=0xa007 …
```
> Update README.md in RA-TLS secret provisioning example

- .pylintrc
- CI-Examples/ra-tls-mbedtls/src/client.c
- Documentation/devel/coding-style.rst
- libos/src/sys/libos_file.c
- pal/src/host/linux-sgx/host_framework.c
- pal/src/pal_main.c
- python/gramine-sgx-sigstruct-view
See the commits.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2075)
> Fix some nitpicks and letfovers from other PRs

- pal/src/host/linux-sgx/pal_main.c
An example of a valid NUMA distance matrix on a host w/ with SNC and UPI affinity enabled is shown below (note the asymmetric distances between nodes, e.g., <0,4> - <4,0> and <1,3> - <3,1>):
```
$ cat /sys/devices/system/node/node*/distance
node   0   1   2   3   4   5
0:  10  15  17  21  28  26
1:  15  10  15  23  26  23
2:  17  15  10  26  23  21
3:  21  28  26  10  15  17
4:  23  26  23  15  10  15
5:  26  23  21  17  15  10
```
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2122)
> [PAL/Linux-SGX] Remove symmetry check for NUMA distances

- Documentation/devel/building.rst
- libos/include/libos_table.h
- libos/src/sys/libos_file.c
- libos/src/sys/libos_mmap.c
- libos/src/sys/libos_wrappers.c
- libos/test/ltp/README.rst
Fix syscall fchmodat(), mmap(), readv() error codes and apply minor documentation fixes. These are found while testing with a newer LTP version.
LTP Test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2117)
> Fix syscall error codes and apply minor documentation fixes

- Documentation/devel/features.md
Fixes https://github.com/gramineproject/gramine/discussions/2125, https://github.com/gramineproject/gramine/issues/2128 and https://github.com/gramineproject/gramine/issues/2110.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2130)
> [Docs] Update IPC, shared memory, directory renaming in features.md

- Documentation/devel/building.rst
ld cache needs update after adding the `.so` file otherwise binary is not able to locate the library it depend on.
Please check issue https://github.com/gramineproject/gsc/issues/239
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2141)
> [Docs] Update ld cache after adding library files
