- LibOS/shim/src/fs/sys/cpu_info.c
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux/db_sockets.c
- common/include/list.h
I'm working on AddressSanitizer integration (see #19) and it already detected a few bugs. I haven't checked Linux-SGX yet, only Linux.
(Short status summary for this work: I think writing custom hooks is still the way to go, not trying to adapt LLVM's library. The main challenge is getting the **stack** part to work: I will probably submit the first version without it, but it's very powerful: it detects use-after-return, use-after-scope, stack buffer overflows and such. Right now I'm struggling to properly cleanup (unpoison) the stack on thread exit).
The tests should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/18)
> Some ASAN fixes

- Pal/src/host/Linux/meson.build
- common/include/meson.build
- common/meson.build
- common/src/meson.build
- meson.build
- subprojects/.gitignore
- subprojects/packagefiles/tomlc99/meson.build
- subprojects/packagefiles/tomlc99/toml.c.patch
- subprojects/packagefiles/tomlc99/toml.h.patch
- subprojects/packagefiles/uthash/meson.build
- subprojects/packagefiles/uthash/src/meson.build
- subprojects/packagefiles/uthash/src/uthash.h.patch
- subprojects/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5.wrap
- subprojects/uthash-2.1.0.wrap
Compile gramine-direct with mesonified `common/`. `gramine-lib.a` is still built because the building code is common with Linux-SGX.
As usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/102)
> [common,Pal/Linux] Compile with Meson

- Documentation/conf.py
- Documentation/index.rst
- Documentation/python/api.rst
- Documentation/requirements.txt
- python/graminelibos/__init__.py
- python/graminelibos/manifest.py
- python/graminelibos/sgx_get_token.py
- python/graminelibos/sgx_sign.py
- python/graminelibos/sigstruct.py
Yeah, just that. Plus some minor bugfixes in python code.
To test SGX version (which is currently disabled) you can build Gramine, copy `_offsets.py` into `python/graminelibos/`, then uncomment stuff in `Documentation/python/api.rst` and add this patch:
```
diff --git a/python/graminelibos/__init__.py b/python/graminelibos/__init__.py
index 23177282..99a699cc 100644
--- a/python/graminelibos/__init__.py
+++ b/python/graminelibos/__init__.py
@@ -18,7 +18,7 @@ from .gen_jinja_env import make_env
_env = make_env()
from .manifest import Manifest, ManifestError
-if '@SGX_ENABLED@' == '1':
+if '@SGX_ENABLED@' == '1' or  _os.getenv('GRAMINE_IMPORT_FOR_SPHINX_ANYWAY') == '1':
from .sgx_get_token import get_token
from .sgx_sign import get_tbssigstruct, sign_with_local_key
from .sigstruct import …
```
> [python] Add API documentation

- LibOS/shim/include/shim_checkpoint.h
- LibOS/shim/include/shim_sync.h
- LibOS/shim/include/shim_thread.h
- LibOS/shim/src/bookkeep/shim_handle.c
- LibOS/shim/src/bookkeep/shim_signal.c
- LibOS/shim/src/fs/proc/thread.c
- LibOS/shim/src/sys/shim_dup.c
- LibOS/shim/src/sys/shim_fcntl.c
Some bugs fixed, mostly checking return values.
CI should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/127)
> [LibOS] Fix random bugs found by Klocwork

- LibOS/shim/include/shim_checkpoint.h
- LibOS/shim/src/shim_checkpoint.c
- LibOS/shim/src/shim_rtld.c
Found in Klocwork report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/130)
> [LibOS] Fix some NULL checks

- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/ipc/shim_ipc.c
- Pal/src/host/Linux/db_streams.c
Some bugs found by Klocwork -- most are just missing NULL checks, but one is a legitimate memory leak.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/131)
> [LibOS] Fix more random bugs found by Klocwork

- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- Documentation/requirements.txt
See https://github.com/sphinx-doc/sphinx/issues/9727.
Hopefully this fixes Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/189)
> [Docs] Add a workaround for Sphinx/docutils issue

- common/meson.build
- meson.build
Fixes #201.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/206)
> [Meson] Don't require `protoc` in non-SGX builds

- Documentation/cloud-deployment.rst
Minor updates to the cloud deployment instuctions based on a quick
sanity check using Ubuntu 20.04 based VMs with both DCsv2 and
DCsv3 instances.
These nodes run with the upstream SGX.
Fixes: #138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/216)
> [Docs] Update Cloud Deployment instructions

- LibOS/shim/src/gramine_hash.c.in
- LibOS/shim/src/meson.build
- LibOS/shim/src/shim_init.c
You know why we need it...
Just build Gramine and run it with log_level = "debug"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/229)
> [LibOS] Print Gramine commit hash on startup

- Documentation/manifest-syntax.rst
Many people encounter this situation, need to describe it somewhere in our docs.
Fixes #233 
Fixes https://github.com/gramineproject/gsc/issues/29
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/239)
> [Docs] Explain SGX v1 committed-RAM behavior for `sgx.enclave_size`

- Documentation/gramine-users.rst
- Documentation/index.rst
- README.rst
This section currently contains only one company (as an example of the text on Gramine usage that other companies can use as a template).
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/230)
> [README,Docs] Add "Users of Gramine" section

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.rst
- Documentation/index.rst
- README.rst
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/241)
> [Docs] Change email groups addresses to use our aliases

- Documentation/building.rst
- Documentation/quickstart.rst
- Pal/src/host/Linux-SGX/tools/README.rst
- Pal/src/host/Linux-SGX/tools/ias-request/.gitignore
- Pal/src/host/Linux-SGX/tools/is-sgx-available/.gitignore
- Pal/src/host/Linux-SGX/tools/pf_crypt/.gitignore
- Pal/src/host/Linux-SGX/tools/pf_tamper/.gitignore
- Pal/src/host/Linux-SGX/tools/quote-dump/.gitignore
- Pal/src/host/Linux-SGX/tools/verify-ias-report/.gitignore
This commit adds steps to build the DCAP version of the RA-TLS library as part of `building` documentation. Also fixes minor naming issues with SGX tools.
Fixes #202
Fixes #203 
Fixes #204 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/198)
> [Docs] Fix minor issues with documentation

- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- Documentation/cloud-deployment.rst
- Documentation/conf.py
- Documentation/devel/building.rst
- Documentation/index.rst
- Documentation/quickstart.rst
- Documentation/requirements.txt
- Makefile
- README.rst
- python/graminelibos/__init__.py
- tools/gramine.in
Also removed markdown support, we don't use it.
test the install instructions (if you haven't already)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/244)
> [Docs] Advise to install from repo

- Pal/src/db_rtld.c
Technically, this PR is currently not needed, but I am implementing a new PAL that uses an EXEC PAL binary. So I decided to upstream this, since it doesn't hurt and it is the only change I needed in the common PAL code.
Closes #250.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/264)
> [Pal] db_rtld: Allow EXEC (non-pie executable) PAL binaries

- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/db_process.c
- Pal/src/host/Linux-SGX/ecall_types.h
- Pal/src/host/Linux-SGX/enclave_ecalls.c
- Pal/src/host/Linux-SGX/pal_linux.h
- Pal/src/host/Linux-SGX/pal_security.h
- Pal/src/host/Linux-SGX/sgx_enclave.c
- Pal/src/host/Linux-SGX/sgx_enclave.h
- Pal/src/host/Linux-SGX/sgx_internal.h
- Pal/src/host/Linux-SGX/sgx_main.c
- Pal/src/host/Linux-SGX/sgx_process.c
- Pal/src/host/Linux/db_main.c
- Pal/src/host/Linux/db_process.c
- Pal/src/host/Linux/pal_host.h
- Pal/src/host/Linux/pal_linux.h
Yeah, I'm still trying to refactor PAL globals :) This is quite a tiny PR, but it was easy to split this part out from the harder changes which will come next.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/272)
> [Pal/Linux-SGX] Remove `stream_fd` from `pal_sec`

- python/graminelibos/regression.py
The previous (async) LTP runner only waited for the main process to exit. Right now we wait for all processes, which uncovered a (known) problem with signal delivery in Gramine: apparently LTP tests sometimes leave running child processes.
Because these tests are still useful for us, we do not treat such situations as a timeout, only log a warning.
I decided it'd be better to enable this workaround globally, than selectively enable it for "known-bad" tests. While there is a risk this will mask some real errors, this issue (as I understand) can happen with basically any program that relies on signal delivery, and deciding (probably experimentally) where this workaround is needed sounds like more trouble than it's worth.
Unfortunately, this implementation is slower: in case some processes …
> [tests] Work around LTP tests leaving running processes

- Pal/src/db_main.c
Trivial PR. Fixing now so we don't forget about this later. This slip was found by Klocwork.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/296)
> [Pal] Remove self-assignment of `g_pal_public_state.manifest_root`

- LibOS/shim/src/ipc/shim_ipc_worker.c
- LibOS/shim/src/sys/shim_pipe.c
- LibOS/shim/src/sys/shim_socket.c
- Pal/include/pal/pal.h
- Pal/include/pal_internal.h
- Pal/regression/Pipe.c
- Pal/regression/Process4.c
- Pal/regression/SendHandle.c
- Pal/regression/Socket.c
- Pal/regression/Tcp.c
- Pal/src/db_streams.c
- Pal/src/host/Linux-SGX/db_pipes.c
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux-SGX/enclave_ocalls.c
- Pal/src/host/Linux-SGX/enclave_ocalls.h
- Pal/src/host/Linux-SGX/ocall_types.h
- Pal/src/host/Linux-SGX/sgx_enclave.c
- Pal/src/host/Linux/db_pipes.c
- Pal/src/host/Linux/db_sockets.c
- Pal/src/host/Skeleton/db_pipes.c
- Pal/src/host/Skeleton/db_sockets.c
Described in commit messages. I think it's a good change by itself, but I will also need it in another PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/285)
> [Pal] Let DkStreamWaitForClient set handle options

- Pal/src/host/Linux-SGX/enclave_entry.S
@mkow asked for this in his belated review of #291.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/305)
> [Pal/Linux-SGX] `enclave_entry.S`: Capitalize regs' names in comments

- Pal/src/host/Linux-SGX/db_streams.c
- Pal/src/host/Linux/db_streams.c
These buffers could have been misaligned before and their size could have been too small.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/306)
> [Pal] Fix size and alignment of ancillary data buffers

- LibOS/shim/test/regression/cpuid.c
- Pal/src/host/Linux-SGX/db_misc.c
- Pal/src/host/Linux-SGX/pal_linux.h
- Pal/src/host/Linux/arch/x86_64/db_arch_misc.c
Split out from #314. See commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/317)
> Small CPUID refactoring

- LibOS/shim/include/arch/x86_64/shim_types-arch.h
- LibOS/shim/include/shim_signal.h
- LibOS/shim/include/shim_thread.h
- LibOS/shim/src/bookkeep/shim_signal.c
- LibOS/shim/src/fs/sys/fs.c
- LibOS/shim/src/shim_parser.c
- LibOS/shim/src/sys/shim_sigaction.c
- LibOS/shim/test/regression/test_libos.py
- Pal/include/arch/x86_64/pal-arch.h
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/db_misc.c
- Pal/src/host/Linux-SGX/sgx_enclave.c
- Pal/src/host/Linux-SGX/sgx_main.c
- Pal/src/host/Linux-SGX/sgx_perf_data.c
- Pal/src/host/Linux-common/topo_info.c
- Pal/src/host/Linux/arch/x86_64/db_arch_exception.c
- Pal/src/host/Linux/pal_host.h
We use both conventions in various places, let's unify this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/319)
> Change `num_*` to `*_cnt` naming for consistency

- LibOS/shim/src/fs/proc/info.c
- LibOS/shim/src/fs/sys/cache_info.c
- LibOS/shim/src/fs/sys/cpu_info.c
- LibOS/shim/src/fs/sys/node_info.c
- Pal/include/arch/x86_64/pal_topology.h
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-common/topo_info.c
As described in the title.
Please run `sysfs_common` test as part of the LibOS regression test suite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/339)
> [Pal] Unify sanitizing and copying operation of topology information

- Documentation/conf.py
(python3-breathe is not available on RHEL)
Build docs, check if rtfd didn't fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/350)
> [Docs] Skip doxygen if not available

- LibOS/shim/src/fs/sys/cache_info.c
- LibOS/shim/src/fs/sys/cpu_info.c
- LibOS/shim/src/fs/sys/node_info.c
- Pal/include/arch/x86_64/pal_topology.h
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-common/topo_info.c
Just a simple change, as it was discussed in #325's review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/351)
> [Pal] Un-tag topology structures

- README.rst
- meson.build
This commit will most likely be our v1.1 release (after checking packages).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/373)
> Bump Gramine version to 1.1

- LibOS/shim/include/shim_entry.h
- LibOS/shim/src/arch/x86_64/shim_context.c
- LibOS/shim/src/bookkeep/shim_thread.c
- LibOS/shim/src/fs/shim_fs.c
- LibOS/shim/src/shim_call.c
- LibOS/shim/src/shim_syscalls.c
- Pal/src/db_main.c
- Pal/src/host/Linux-SGX/db_exception.c
Just cleaning up my private TODOlist :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/372)
> Various trivial fixes

- CI-Examples/ra-tls-mbedtls/src/server.c
- Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c
See #289 for the context and analysis.
The function got stale because it was not covered by our CI tests. This PR modifies the CI example `ra-tls-mbedtls` to use this function.
Fixes #289.
`ra-tls-mbedtls` CI example was updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/295)
> [Pal/Linux-SGX] Fix bugs in `ra_tls_create_key_and_crt_der()` API

- LibOS/shim/include/shim_types.h
As suggested by @pwmarcz in #183. Those are unused.
No stipulation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/184)
> [LibOS] Remove more unused kernel stuff

- Documentation/manpages/gramine-sgx-ias-verify-report.rst
The title of `Documentation/manpages/gramine-sgx-ias-verify-report.rst` is incorrect and the cmdline opt doc'ed is no longer up-to-date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/393)
> [Docs] ias-verify-report: Fix title and update cmdline opt

- Pal/src/db_rtld.c
These three small bugs were found by Klocwork. Kudos to Anees Sahib and Jinen Gandhi.
N/A. Too simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/399)
> [Pal] db_rtld.c: Fix possible NULL-pointer derefs and memory leak

- Pal/src/host/Linux/db_exception.c
- Pal/src/host/Linux/db_main.c
Unfortunately workaround from e7429e13bb3e914c5f582ead4ca2e3f81d145a8f was not enough and we are left with no other option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/392)
> [Pal/Linux] Disable VDSO support on systems with 5-level paging

- LibOS/shim/src/ipc/shim_ipc_worker.c
- LibOS/shim/src/shim_async.c
- LibOS/shim/src/sys/shim_epoll.c
- LibOS/shim/src/sys/shim_poll.c
- Pal/include/pal/pal.h
- Pal/include/pal_internal.h
- Pal/src/db_object.c
- Pal/src/host/Linux-SGX/db_eventfd.c
- Pal/src/host/Linux-SGX/db_object.c
- Pal/src/host/Linux-SGX/db_pipes.c
- Pal/src/host/Linux-SGX/db_process.c
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux-SGX/enclave_ocalls.c
- Pal/src/host/Linux-SGX/enclave_ocalls.h
- Pal/src/host/Linux-SGX/ocall_types.h
- Pal/src/host/Linux-SGX/sgx_enclave.c
- Pal/src/host/Linux-common/timespec_utils.c
- Pal/src/host/Linux/db_object.c
- Pal/src/host/Skeleton/db_object.c
- common/include/api.h
Currently only used by epoll
Fixes https://github.com/gramineproject/graphene/issues/435
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/385)
> [Pal] Add updatable timeout to `DkStreamsWaitEvents`

- Pal/src/db_object.c
- Pal/src/host/Linux-SGX/db_object.c
- Pal/src/host/Linux/db_object.c
Mostly remove unnecessary `offset` arrays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/386)
> [Pal/{Linux,Linux-SGX}] Clean up `_DkStreamsWaitEvents`

- LibOS/shim/src/bookkeep/shim_vma.c
This is purely cosmetic (removing dead code, improving comments). No functional changes (and if there are, it is my bug).
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/413)
> [LibOS] Clean up checkpoint/restore of a VMA

- Pal/src/host/Linux-SGX/sgx_main.c
The problem with headers was because we imported <sys/auxv.h>, which in turns imports <elf.h>, which clashes with our own "elf.h". That was because we used the `getauxval` function from glibc. Instead, we manually parse the ELF aux vector.
I used a temporary log line to check if we retrieve the same value of `AT_HWCAP2`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/416)
> [Pal/Linux-SGX] Fix header conflict in `sgx_main.c`

- LibOS/shim/src/fs/shim_namei.c
Signed-off-by: Sonali Saha <sonali.saha@intel.com>
This commit fixes the issue of `readdir` not being able to detect directory deletion. When the directories have been deleted the state of those directories is not modified inside gramine and the state remains valid. As a fix, the list of old directory entries is compared with the recently fetched list of directory entries by `readdir`. If an old directory entry is not found in the latest list change the state of that directory entry to `DENTRY_NEGATIVE` and make it invalid.
Fixes #390.
Follow Readme.txt.
[subDir_experiments_SGX.tar.gz](https://github.com/gramineproject/gramine/files/8124870/subDir_experiments_SGX.tar.gz)
--- …
> [LibOS] Fix `readdir` not able to detect directory deletion

- Pal/src/host/Linux-SGX/db_streams.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/438)
> [Pal] Remove unused free_d2 check in serialize handle

- Documentation/gramine-users.rst
This text was approved by the respective companies.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/450)
> [Docs] Add gematik/IBM to "Users of Gramine" section

- Documentation/requirements.txt
This is a commit by @woju split off from #481. It fixes the Jenkins build.
Jenkins should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/493)
> [Docs] Pin jinja<3.1 in RTFD

- Documentation/sgx-intro.rst
Also fix the formatting of the "See also" section of "Architectural Enclaves".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/472)
> [Docs] Describe AESM in sgx-intro

- LibOS/shim/src/fs/eventfd/fs.c
- LibOS/shim/src/fs/pipe/fs.c
- LibOS/shim/src/fs/socket/fs.c
- Pal/include/pal/pal.h
- Pal/src/host/Linux-SGX/db_devices.c
- Pal/src/host/Linux-SGX/db_eventfd.c
- Pal/src/host/Linux-SGX/db_files.c
- Pal/src/host/Linux-SGX/db_main.c
- Pal/src/host/Linux-SGX/db_pipes.c
- Pal/src/host/Linux-SGX/db_process.c
- Pal/src/host/Linux-SGX/db_sockets.c
- Pal/src/host/Linux-SGX/db_streams.c
- Pal/src/host/Linux-SGX/ecall_types.h
- Pal/src/host/Linux-SGX/enclave_ecalls.c
- Pal/src/host/Linux-SGX/pal_linux.h
- Pal/src/host/Linux-SGX/sgx_enclave.c
- Pal/src/host/Linux-SGX/sgx_enclave.h
- Pal/src/host/Linux-SGX/sgx_main.c
- Pal/src/host/Linux/db_devices.c
- Pal/src/host/Linux/db_eventfd.c
- Pal/src/host/Linux/db_files.c
- Pal/src/host/Linux/db_main.c
- Pal/src/host/Linux/db_pipes.c
- Pal/src/host/Linux/db_process.c
- Pal/src/host/Linux/db_sockets.c
- Pal/src/host/Linux/db_streams.c
- Pal/src/host/Linux/pal_linux.h
This PR removes unused `poll` callbacks in sockets, eventfd and pipe LibOS handles + all code that become dead as a result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/488)
> [LibOS,Pal] Remove some dead code

- Documentation/gramine-users.rst
Adding https://enclaive.io/ text.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/494)
> [Docs] Add enclaive.io to "Users of Gramine" section

- CONTRIBUTING.rst
- Documentation/_templates/layout.html
Seems some of them slipped through the reviews.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/517)
> [Docs] Expand RTD links

- LibOS/shim/test/.gitignore
- LibOS/shim/test/abi/x86_64/.gitignore
- LibOS/shim/test/fs/.gitignore
- LibOS/shim/test/ltp/.gitignore
- LibOS/shim/test/regression/.gitignore
Deduplicate entries that are shared between different group tests.
This change should simplify adding the simple test directories in the future.
```
$ touch asd.xml abi/asd.xml abi/x86_64/asd.xml
$ git status
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/554)
> [gitignore] Deduplicate entries

- LibOS/shim/test/abi/x86_64/test_entrypoint.py
```
ninja all
ninja install
gramine-test -C LibOS/shim/test/abi/x86_64/ pytest
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/567)
> [tests] set up the test numbering

- Documentation/quickstart.rst
See https://github.com/gramineproject/gramine/issues/560 for details.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/562)
> [Docs] Better wording in Quick Start Guide

- .ci/lib/config.jenkinsfile
- .ci/lib/stage-clean-check.jenkinsfile
- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- .ci/ubuntu18.04.dockerfile
- .ci/ubuntu20.04.dockerfile
- CI-Examples/blender/Makefile
- CI-Examples/helloworld/Makefile
- CI-Examples/redis/Makefile
- CI-Examples/rust/.gitignore
- CI-Examples/rust/Cargo.toml
- CI-Examples/rust/Makefile
- CI-Examples/rust/README.md
- CI-Examples/rust/rust-hyper-http-server.manifest.template
- CI-Examples/rust/src/main.rs
- Documentation/devel/performance.rst
Rust's async runtime has triggered bugs in our epoll in the past.
This example will serve as a smoke-test in this area, as well as
point users to the manifest settings that are necessary.
1. `cd CI-Examples/rust`
2. `make start-gramine-server SGX=1`
3. In another terminal: `curl localhost:3000`
4. Make sure the CI config changes work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/495)
> [CI-Examples] Add an async Rust example

- LibOS/shim/src/sys/shim_eventfd.c
See #495 for an example of an application making use of eventfd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/525)
> [LibOS] Warn when app tries using disabled eventfd

- CI-Examples/busybox/Makefile
- CI-Examples/lighttpd/Makefile
- CI-Examples/memcached/Makefile
- CI-Examples/nginx/Makefile
- CI-Examples/python/Makefile
- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-secret-prov/Makefile
- CI-Examples/sqlite/Makefile
Following up n #495, I switch the rest of the examples to use the preferred method of having make generate two files with one command.
CI should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/588)
> [CI-Examples] Apply grouped targets make hack to all examples

- CI-Examples/python/README.md
- CI-Examples/ra-tls-mbedtls/README.md
- CI-Examples/ra-tls-secret-prov/README.md
- Documentation/sgx-intro.rst
The way one was supposed to run RA-TLS was confusing before. Explain what an SPID is, how to obtain one, and link to that documentation in the READMEs of relevant examples.
Follow the instructions and verify they're clear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/585)
> [Docs,CI-Examples] Document the SPID parameter

- Documentation/cloud-deployment.rst
- Documentation/devel/building.rst
- Documentation/quickstart.rst
Follow instructions (with `unstable` repo, not `stable`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/605)
> [Docs] Fix installation of dependencies for v1.2

- meson.build
Release time!
2 commits - first is supposed to go into the release, the next one updates the version on master for the post-1.2 development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/615)
> Bump version to 1.2

- .ci/lib/stage-clean-check.jenkinsfile
- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- CI-Examples/busybox/.gitignore
- CI-Examples/busybox/Makefile
See discussion in #602.
To prevent issues like #602, this PR adds a very simple check that Busybox builds and runs.
Busybox added to CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/603)
> [CI-Examples] Add Busybox check to Jenkins CI

- Documentation/devel/new-syscall.rst
- Documentation/pal/host-abi.rst
- LibOS/shim/src/bookkeep/shim_signal.c
- LibOS/shim/src/shim_checkpoint.c
- LibOS/shim/src/sys/shim_eventfd.c
- Pal/include/arch/x86_64/pal-arch.h
- Pal/include/pal/pal.h
- Pal/include/pal_internal.h
- Pal/regression/Exception.c
- Pal/regression/Exception2.c
- Pal/regression/Memory.c
- Pal/src/db_memory.c
- Pal/src/db_misc.c
- Pal/src/db_process.c
- Pal/src/db_streams.c
- Pal/src/db_threading.c
- Pal/src/host/Linux-SGX/db_exception.c
- Pal/src/host/Linux-SGX/db_misc.c
- Pal/src/host/Linux-SGX/db_pipes.c
- Pal/src/host/Linux-SGX/db_threading.c
- Pal/src/host/Linux-SGX/pal_host.h
- Pal/src/host/Linux/db_exception.c
- Pal/src/host/Linux/db_misc.c
- Pal/src/host/Linux/db_threading.c
- Pal/src/host/Linux/pal_host.h
- Pal/src/host/Skeleton/db_misc.c
- Pal/src/host/Skeleton/db_threading.c
Get rid of PAL_NUM and replace it with standard types.
Build with clang and gcc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/608)
> [gramine] Remove PAL_NUM type

- Documentation/index.rst
- Documentation/tutorials/cczoo/index.rst
CCZoo is an Intel-backed project that collects end-to-end confidential computing solutions. Many of these solutions build on top of Gramine.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/625)
> [Docs] Add a page with description and link to CCZoo

- .ci/lib/config-ubuntu18.04.jenkinsfile
- .ci/lib/config-ubuntu20.04.jenkinsfile
- CI-Examples/python/README.md
This support was removed long time ago, so the text got stale and incorrect.
See also https://github.com/gramineproject/examples/pull/30.
Our CI should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/637)
> [CI-Examples] Remove section about "local installation" in Python

- Documentation/libos/shim-init.rst
- Documentation/pal/host-abi.rst
- LibOS/shim/include/shim_internal.h
- LibOS/shim/include/shim_pollable_event.h
- LibOS/shim/src/fs/shim_fs_lock.c
- LibOS/shim/src/ipc/shim_ipc_worker.c
- LibOS/shim/src/shim_async.c
- LibOS/shim/src/shim_object.c
- LibOS/shim/src/shim_pollable_event.c
- LibOS/shim/src/sync/shim_sync_client.c
- LibOS/shim/src/sys/shim_clone.c
- LibOS/shim/src/sys/shim_epoll.c
- LibOS/shim/src/sys/shim_futex.c
- LibOS/shim/src/sys/shim_sigaction.c
- Pal/include/pal/pal.h
Miscellaneous fixes from my todo list. Stashed into one PR as they are rather small.
Review commit-by-commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/658)
> Misc fixes

- common/include/generated_offsets_build.h
- common/src/generated_offsets_print.c
- common/src/meson.build
- libos/include/generated-offsets.c
- pal/src/host/linux-sgx/generated-offsets.c
As the name suggests.
See https://github.com/gramineproject/gramine/discussions/667 and https://github.com/gramineproject/gramine/discussions/687 for details.
CI is enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/691)
> [common] Rename files (only `-` -> `_`)

- common/src/protected_files/protected_files_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/712)
> [common] Remove unused `cur_key` from `pf_context`

- libos/include/libos_fs.h
- libos/src/fs/socket/fs.c
- libos/src/sys/libos_ioctl.c
- libos/test/regression/common.h
- libos/test/regression/tcp_msg_peek.c
- libos/test/regression/test_libos.py
Fixes https://github.com/gramineproject/gramine/issues/673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/684)
> [LibOS] Support `FIONREAD` ioctl on sockets

- Documentation/devel/building.rst
As requested by @boryspoplawski since it is hard to find good resources on SGX SDK/PSW/DCAP installation. Especially advanced topics like installing AESM daemon without systemd.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/750)
> [Docs] Add links to SGX SDK/PSW Installation Guide in "Building"

- Documentation/devel/howto-doc.rst
- common/src/protected_files/protected_files.h
- libos/include/libos_checkpoint.h
- libos/include/libos_signal.h
- libos/test/regression/attestation.c
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/src/host/linux-sgx/enclave_ocalls.h
- pal/src/host/linux-sgx/enclave_tf.h
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/pal_linux.h
- pal/src/host/linux-sgx/pal_misc.c
- pal/src/host/linux-sgx/pal_pipes.c
- pal/src/host/linux-sgx/sgx_attest.h
- pal/src/host/linux/pal_pipes.c
- tools/sgx/common/ias.c
- tools/sgx/common/ias.h
- tools/sgx/common/quote.h
- tools/sgx/common/util.h
- tools/sgx/ra-tls/ra_tls.h
- tools/sgx/ra-tls/secret_prov.h
Final (hopefully) part of #420 and #439.
No functional changes intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/751)
> [Docs] Improve and unify Doxygen comments, part 3

- pal/include/pal/pal.h
- pal/src/host/linux-sgx/enclave_framework.c
- pal/src/host/linux-sgx/pal_devices.c
- pal/src/host/linux-sgx/pal_eventfd.c
- pal/src/host/linux-sgx/pal_object.c
- pal/src/host/linux-sgx/pal_pipes.c
- pal/src/host/linux-sgx/pal_process.c
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_devices.c
- pal/src/host/linux/pal_eventfd.c
- pal/src/host/linux/pal_pipes.c
- pal/src/host/linux/pal_process.c
- pal/src/host/linux/pal_streams.c
- pal/src/pal_events.c
- pal/src/pal_threading.c
Remove `HANDLE_HDR `macros and replace with inline code 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/745)
> [PAL] replace `HANDLE_HDR ` macros with inline code

- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/src/host/linux-sgx/pal_sockets.c
- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_pipes.c
- pal/src/host/linux/pal_sockets.c
- pal/src/host/linux/pal_streams.c
- pal/src/pal_sockets.c
Remove `PAL_GET_TYPE ` macros and replace with inline code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/755)
> [PAL] replace `PAL_GET_TYPE ` macros with inline code.

- pal/src/host/linux/pal_sockets.c
- tools/sgx/common/pf_util.c
Two memory leaks detected by Klocwork.
CI is enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/779)
> [PAL/Linux-SGX,tools] Fix misc memory leaks

- Documentation/sgx-intro.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/769)
> [Docs] Update DCAP orientation guide to 1.14

- pal/include/pal/pal.h
- pal/src/pal_object.c
- pal/src/pal_streams.c
Signed-off-by: Liang Ma <liang3.ma@intel.com>
Replace `UNKNOW_HANDLE` macros with inline code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/775)
> [PAL] Replace `UNKNOWN_HANDLE` macro with inline code

- packaging/docker/Dockerfile
- packaging/docker/restart_aesm.sh
It was used to build https://hub.docker.com/r/gramineproject/gramine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/797)
> [packaging] Add source of official Gramine docker image

- common/include/api.h
- libos/include/libos_table.h
- libos/include/libos_thread.h
- libos/src/bookkeep/libos_thread.c
- libos/src/sys/libos_sched.c
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/enclave_ocalls.h
- pal/src/host/linux-sgx/pal_threading.c
- pal/src/host/linux/pal_threading.c
- pal/src/host/skeleton/pal_threading.c
- pal/src/pal_threading.c
New version of #631
Closes #631
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/798)
> [LibOS,PAL] Emulate CPU affinity in LibOS

- pal/src/host/linux/pal_streams.c
Signed-off-by: Yao Ji <yao.ji@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/811)
> [Pal] Fix possible memory leak after calling `handle_deserialize()`

- Documentation/devel/onboarding.rst
- README.rst
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/832)
> [Docs] Mention Gitter in our README

- pal/src/host/linux-sgx/host_main.c
- pal/src/host/linux/pal_main.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/833)
> [PAL] Update "pal_loader" to "gramine-*" in warnings

- libos/src/libos_init.c
- libos/src/sys/libos_clone.c
- pal/include/pal_internal.h
Found a few survivors left after the recent renamings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/831)
> [LibOS] Remove the last usages of "shim" and "DK" names

- libos/src/sys/libos_clone.c
See the commit message.
Try running https://github.com/gramineproject/gramine/pull/839 with and without this fix with ASAN and UBSAN enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/852)
> [LibOS] Fix an UAF on PAL event in `clone_implementation_wrapper`

- tools/sgx/ra-tls/secret_prov_attest.c
This memory leak was found by Klocwork. Note that `setenv()` makes a
copy of the secret, so the originally allocated secret must be freed.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/854)
> [tools/sgx] Free secret after its use in `secret_provision_constructor()`

- libos/test/fs/common.c
- libos/test/fs/common.h
- libos/test/fs/seek_tell.c
- libos/test/fs/test_enc.py
- libos/test/fs/test_fs.py
As pointed out  in review https://reviewable.io/reviews/gramineproject/gramine/719 this test is ugly.
Rewrite it to self check whatever it can.
We can trust `stat` while determine the size of file as the `libos/test/fs/stat.c` test verifies this. 
```
gramine-test -C libos/test/fs pytest
gramine-test --sgx -C libos/test/fs pytest
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/767)
> [tests] Rewrite seek_tell test

- libos/include/libos_handle.h
- libos/src/fs/socket/fs.c
- libos/src/net/unix.c
Emulated purely in LibOS. 
You can use following program (in libos regression tests, as it uses some common code from there) to play with different races (highlighted a few places you can edit for different results). I did not add it to CI, since it just races some operations and it's hard to define what counts as the test passed.
```c
#include <err.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/time.h>
#include "common.h"
static void* func(void* arg) {
int s = (long)arg;
/* You can play with this loop size. */
for (size_t i = 0; i …
```
> [LibOS] Add support for `MSG_DONTWAIT` in UNIX domain sockets

- libos/test/regression/test_libos.py
pylint doesn't like the format string without any interpolated variables
Re run test suite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/867)
> [tests] Fix warning reported by pylint

- .github/ISSUE_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/899)
> [Github] Add gitter link to issues template

- Documentation/devel/packaging.rst
Otherwise there is a discrepancy between our ["Quick start"](https://gramine.readthedocs.io/en/latest/quickstart.html) and ["Packaging and distributing"](https://gramine.readthedocs.io/en/latest/devel/packaging.html?highlight=20.04#packaging-and-distributing) pages.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/879)
> [Docs] Add RHEL-8-like distros to list of supported distros

- libos/src/sys/libos_alarm.c
Raise SIGALRM when setitimer's real time timer expires and setitimer() serves as an alarm() replacement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/888)
> [LibOS] Raise SIGALRM when setitimer's real time timer expires

- libos/src/sys/libos_sched.c
Previously, temporary CPU mask was always allocated on heap. However, the current LibOS memory allocator exhibits bad performance in multi-threaded environments as it has a single global lock. This becomes a performace bottleneck on some heavily multi-threaded workloads like OpenVINO.
This PR introduces a fast path for the common case of platforms with less than 1024 CPUs, where temporary CPU mask is allocated on the stack and thus avoids lock contention.
Fixes #913.
See #913. I checked manually on the OpenVINO workload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/915)
> [LibOS] Allocate temporary CPU mask on stack in `sched_setaffinity`

- meson.build
As usual. Will also push the tag after final packages validation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/931)
> Bump Gramine version to 1.3

- libos/test/regression/rename_unlink.c
There is a slight difference between `write_all` and `posix_fd_rw` functions. Because the test doesn't use any signal handler, the write_all function treat EINTR as an error. However, I don't think this is a good reason to introduce a separate write function, and we can reuse existing one.
Run the test suite should be enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/940)
> [tests] Remove duplicated read/write function

- common/src/string/atoi.c
- pal/regression/meson.build
- pal/regression/pal_regression.h
- pal/regression/printf_test.c
- pal/regression/strtoll_test.c
- pal/regression/test_pal.py
- pal/regression/tests.toml
Fix value of strtol/strtoll endptr if nothing was converted
Resolves: https://github.com/gramineproject/gramine/issues/907
Run PAL regression test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/945)
> [common] Fix value of strtol/strtoll endptr if nothing was converted

- CI-Examples/python/helper-files/hosts
- CI-Examples/python/python.manifest.template
This PR removes the manifest option `sgx.allowed_files` with its unneeded `/etc/` files. Also the PR cleans up the paths.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/962)
> [CI-Examples] Harden Python example

- common/include/api.h
- common/include/linux_eventfd.h
- common/include/memmgr.h
- common/include/slabmgr.h
- libos/meson.build
- libos/src/libos_init.c
- libos/src/sys/libos_brk.c
- libos/src/sys/libos_eventfd.c
- libos/src/sys/libos_mmap.c
- libos/src/sys/libos_uname.c
- libos/src/vdso/arch/x86_64/meson.build
- pal/include/host/linux-common/pal_flags_conv.h
- pal/regression/ipv4_parser.c
- pal/regression/meson.build
- pal/src/host/linux-sgx/enclave_tf.h
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/pal_eventfd.c
- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux/pal_eventfd.c
- pal/src/host/linux/pal_linux.h
- pal/src/host/linux/pal_pipes.c
- pal/src/host/linux/pal_process.c
- pal/src/host/linux/pal_streams.c
- pal/src/meson.build
- subprojects/packagefiles/mbedtls/compile-pal.sh
See commit messages.
https://man7.org/linux/man-pages/man1/gcc.1.html
https://man7.org/linux/man-pages/man1/ld.1.html
https://gcc.gnu.org/onlinedocs/gcc/Standards.html#Standards
No functional changes, CI should be enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/970)
> Revisit compiler flag usages

- pal/src/host/linux-sgx/enclave_ecalls.c
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/host_ecalls.c
- pal/src/host/linux-sgx/host_ocalls.c
- pal/src/host/linux-sgx/pal_ecall_types.h
- pal/src/host/linux-sgx/pal_ocall_types.h
@mkow in https://github.com/gramineproject/gramine/pull/850 suggested that this `ms_` prefix is obsolote and useless.
So lets remove it.
Gramine test suite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/870)
> [PAL] Drop `ms_` prefix

- libos/src/bookkeep/libos_vma.c
Issue found by Klocwork.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/989)
> [LibOS] Add missing free to `all_vmas` checkpointing

- pal/src/host/linux-sgx/pal_streams.c
- pal/src/host/linux/pal_streams.c
Rename some variables to make the code more readable. Also checked the remaining pointers inside handle. There is no need to serialize those pointers.
Run pal regression test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/988)
> [Pal] Refactor `handle_serialize()`

- python/graminelibos/manifest.py
Not yet sure if we want it, but in case we do here it is.
Closes #977 
Add duplicate entries in trusted files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1003)
> [python] Remove duplicates when expanding trusted files

- libos/test/regression/test_libos.py
- libos/test/regression/unix.c
Extracted from https://github.com/gramineproject/gramine/pull/986, with comments from @boryspoplawski resolved.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/996)
> [LibOS] Rewrite `unix` regression test

- README.rst
Requested by Mona. See https://github.com/gramineproject/gramine/discussions/985.
See https://github.com/gramineproject/gramine/tree/dimakuv/add-discussions-to-readme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1011)
> Mention GitHub Discussions in README

- Documentation/devel/building.rst
Yes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1022)
> [Docs] Add missing packages to installation instructions

- Documentation/pal/host-abi.rst
- libos/src/bookkeep/libos_vma.c
- libos/src/fs/proc/info.c
- libos/src/fs/sys/node_info.c
- libos/src/sys/libos_getrlimit.c
- pal/include/pal/pal.h
- pal/include/pal_internal.h
- pal/regression/Symbols.c
- pal/regression/memory.c
- pal/regression/test_pal.py
- pal/src/host/linux-sgx/pal_memory.c
- pal/src/host/linux/pal_memory.c
- pal/src/host/skeleton/pal_memory.c
- pal/src/pal_misc.c
- pal/src/pal_symbols
See each commit.
Fixes #1017
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1036)
> Fix available memory accounting

- common/include/slabmgr.h
Signed-off-by: Liang, Ma <liang3.ma@intel.com>
Correct typo of SLAB_LEVELS_SUM
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1037)
> [common] a typo in SLAB_LEVELS_SUM

- libos/include/libos_types.h
- libos/src/fs/proc/fs.c
- libos/src/ipc/libos_ipc_pid.c
- libos/test/ltp/ltp.cfg
The file is read-only and returns a UINT_MAX constant.
This is required by some LTP tests, e.g. https://github.com/gramineproject/gramine/blob/5bba58a902d099f9068e0f04b3c2a37e591a1d27/libos/test/ltp/ltp.cfg#L869
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1053)
> [LibOS] Add `/proc/sys/kernel/pid_max` file

- tools/sgx/ra-tls/ra_tls.h
- tools/sgx/ra-tls/ra_tls_attest.c
- tools/sgx/ra-tls/ra_tls_verify_common.c
- tools/sgx/ra-tls/ra_tls_verify_dcap.c
- tools/sgx/ra-tls/ra_tls_verify_epid.c
No functional changes. This is in preparation for "interoperable RA-TLS" modification of RA-TLS (with IANA-registered OIDs and CBOR tags).
CI. Only renames of funcs/variables and moving code around.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1038)
> [tools/sgx] Cosmetic refactoring of RA-TLS

- pal/include/pal_internal.h
- pal/src/pal_memory.c
- pal/src/pal_rtld.c
One hack less
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1061)
> [PAL] Allow for bookkeeping internal memory

- libos/src/fs/chroot/encrypted.c
- libos/src/fs/libos_fs.c
Just more logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1068)
> [LibOS] Inform user about malformed URI

- libos/src/sys/libos_poll.c
Fixes #1110 
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1111)
> [LibOS] Check read/write/except set buffers on `select`

- pal/src/host/linux-sgx/enclave_edmm.c
- pal/src/host/linux-sgx/sgx_arch.h
Bugfix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1135)
> [PAL/Linux-SGX] Add missing EACCEPT after restricting page perms

- libos/include/libos_vma.h
- libos/src/bookkeep/libos_vma.c
As in the title. Context: some review discussion under #1054.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1126)
> [LibOS] Unify ret-via-arg name prefixes

- CI-Examples/python/run-tests.sh
Fixed a funny typo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1123)
> Fix typo in run-tests.sh

- pal/src/host/linux-sgx/host_framework.c
Fixes #1140 
Test manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1141)
> [PAL/Linux-SGX] Print message on EACCES during SGX driver open

- libos/src/fs/chroot/encrypted.c
- libos/test/fs/chmod_stat.c
- libos/test/fs/meson.build
- libos/test/fs/test_fs.py
- libos/test/fs/tests.toml
Signed-off-by: Jaewon Hur <hurjaewon@snu.ac.kr>
Fix assertion on `dent->inode`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1127)
> [LibOS] Fix assertion on `dent->inode`

- meson.build
Just a random finding in our Meson files.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1172)
> [meson] Indentation fixes for VTune dependency

- libos/include/libos_handle.h
Noticed these completely unused declarations. Removed them.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1204)
> [LibOS] Remove dead code from `libos_handle.h`

- Documentation/gramine-users.rst
Yes.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1030)
> [Docs] Add Super Protocol to "Users of Gramine" section

- .ci/check-python-platlib-almalinux8.dockerfile
- .ci/check-python-platlib-almalinux9.dockerfile
- .ci/check-python-platlib-debian11.dockerfile
- .ci/check-python-platlib-ubuntu18.04.dockerfile
- .ci/check-python-platlib-ubuntu20.04.dockerfile
- .ci/check-python-platlib-ubuntu22.04.dockerfile
- .ci/check-python-platlib.jenkinsfile
- scripts/get-python-platlib.py
Install Gramine on Ubuntu 22.04 from sources, either do not specify `--prefix` or set it to `/usr/local`.
Fixes #1201 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1203)
> Fix python installation on Ubuntu 22.04

- README.rst
This PR:
- Fixes a broken link in the README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1229)
> README.md: Fix performance tuning link

- libos/test/regression/fcntl_lock.c
Fix error message in the `fcntl_lock` test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1243)
> [tests] Fix error message in `fcntl_lock` test

- Documentation/devel/building.rst
- Documentation/sgx-intro.rst
- Documentation/tutorials/pytorch/index.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1247)
> [Docs] Update SGX SDK/PSW/DCAP links to point to the latest version

- python/graminelibos/sigstruct.py
Previously, Gramine treated each `date` info on signing (`date_year`, `date_month`, `date_day`) as decimal and packed them into hex (in little-endian) separately in `SIGSTRUCT`.
However, `SIGSTRUCT.DATE` is required to be yyyymmdd in hex: yyyy=4 digit year, mm=1-12, dd=1-31 according to Intel SDM. Further, SGX SDK and some code signing systems interpret it as "Binary-coded decimal", e.g., expecting "14 04 23 20" rather than "0e 04 e7 07" for date "2023-4-14" in its byte representation.
This commit fixes the above issue which may fail the format validation of some code signing systems.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1287)
> [python] Fix wrong format of `SIGSTRUCT.DATE`

- pal/src/host/linux-sgx/gdb_integration/sgx_gdb.c
Some operating systems (like Alpine Linux) use `sys/ptrace.h` header from musl, which define ptrace requests as macros instead of enum.
glibc version - https://codebrowser.dev/glibc/glibc/sysdeps/unix/sysv/linux/x86/sys/ptrace.h.html#__ptrace_request
musl version - https://git.musl-libc.org/cgit/musl/tree/include/sys/ptrace.h#n12
Build with glibc and musl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1311)
> [Pal/Linux-SGX] Support musl version of ptrace

- libos/test/regression/device_ioctl_fail.manifest.template
- libos/test/regression/test_libos.py
- pal/include/pal/pal.h
- pal/src/host/linux/meson.build
- pal/src/host/linux/pal_devices.c
Final part of the series of PRs.
- First PR is https://github.com/gramineproject/gramine/pull/1386
- Second PR is https://github.com/gramineproject/gramine/pull/1387
CI is enough. It was modified in this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1388)
> [Pal/Linux] Change Linux PAL to use flexible IOCTLs

- pal/src/host/linux-sgx/host_framework.c
In the last couple weeks, I had two independent debug sessions on this `-EIO` problem. It's always about the CPU feature bits mismatching in the SGX enclave's initial SECS and what exists on the platform.
Two examples:
1. People sometimes copy-paste the final `manifest.sgx` file from platform to platform and forget about `sgx.require_xxx` flags. They get this error and have no hint what this means.
2. There was/is a bug in QEMU v7.1 which was fixed in QEMU v8.0.1. If you're unlucky and have a bad QEMU version (which incorrectly propagates CPU feature bits), you get this EIO error.
- Here I was wondering if I should add even more text to the message, mentioning that some versions of QEMU are buggy, and asking users to update to the very latest QEMU. But I think this is too corner-case to …
> [PAL/Linux-SGX] Add explanation message on ECREATE's EIO error

- .ci/debian12.dockerfile
- .ci/pkg-deb-debian12.jenkinsfile
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1431)
> [CI] Build packages for bookworm (Debian 12)

- .ci/lib/stage-build-nosgx.jenkinsfile
- .ci/lib/stage-build-sgx-vm.jenkinsfile
- .ci/lib/stage-build-sgx.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
- .ci/lib/stage-test.jenkinsfile
- .ci/linux-sgx-ubuntu20.04-musl.jenkinsfile
- Documentation/devel/building.rst
- debian/gramine.install
- gramine.spec
- libos/test/abi/x86_64/manifest.template
- libos/test/abi/x86_64/stack_arg.manifest.template
- libos/test/abi/x86_64/stack_env.manifest.template
- libos/test/regression/meson.build
- meson.build
- meson_options.txt
- scripts/makedist.sh
- subprojects/packagefiles/mbedtls/meson.build
- subprojects/packagefiles/mbedtls/meson_options.txt
- tools/sgx/ra-tls/meson.build
1. CI
2. Build gramine on Debian with `-Dlibc=musl` and try to run some tests.
3. Build gramine on Alpine with `-Dlibc=musl`.
(Don't try building gramine on Alpine with `-Dlibc=glibc`).
Fixes #1399.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1427)
> [meson] Change -Dglibc and -Dmusl to -Dlibc

- Documentation/devel/features.md
Added descriptions for flock, dummy support for ancillary data in networking, poll/epoll improvements, flexible IOCTLs, session management, `/dev/attestation/keys/_sgx_*` files.
Fixes #1295.
I temporarily enabled rendering for this PR here: https://gramine.readthedocs.io/en/dimakuv-update-gramine-features-doc-june-2023/devel/features.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1429)
> [Docs] Update "Gramine features"

- Documentation/devel/building.rst
See @woju's comment in #1434.
Closes #1434.
Docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1436)
> [Docs] Create a section on prefix when installing from sources

- Documentation/run-sample-application.rst
I was asked to add these notes on Helloworld on Alpine.
I temporarily enabled the page: https://gramine.readthedocs.io/en/dimakuv-docs-add-alpine-helloworld/run-sample-application.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1438)
> [Docs] Add notes on running Helloworld on Alpine

- Documentation/installation.rst
- debian/changelog
- gramine.spec
- meson.build
- packaging/alpine/APKBUILD
This is release PR for 1.5. Will be rebased and updated accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1437)
> Release 1.5

- Documentation/attestation.rst
- Documentation/manifest-syntax.rst
- Documentation/tutorials/pytorch/index.rst
The tutorial wasn't updated since Gramine v1.2, it got stale.
Manually on a DCAP machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1418)
> [Docs] Fix PyTorch tutorial

- pal/src/host/linux-sgx/pal_main.c
Better safe than sorry.
See also description of this option: https://gramine.readthedocs.io/en/stable/manifest-syntax.html#experimental-flock-bsd-style-locks-support
Manual inspection:
```bash
~/gramineproject/gramine/libos/test/regression$ gramine-sgx uid_gid
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:
- sgx.debug = true                           (this is a debug enclave)
Gramine will continue application execution, but this configuration must not be used in production!
-------------------------------------------------------------------------------------------------------------------- …
```
> [PAL/Linux-SGX] Add warning on startup about `sys.experimental__enable_flock`

- Documentation/devel/building.rst
The building command is incorrect.
Follow command to build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1460)
> [Docs] fix a typo in building documentation

- libos/src/libos_parser.c
This would help debug/identify issues w/ `msync()`, see https://github.com/gramineproject/gramine/issues/1432 for details.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1491)
> [LibOS] Add parser for `msync()` syscall

- CHARTER.rst
- Documentation/devel/charter.rst
- Documentation/index.rst
The Technical Charter, copied from a Word document into an RST format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1097)
> [Docs] Add Technical Charter document

- Documentation/manifest-syntax.rst
- common/src/ioctls/ioctls.c
- common/src/ioctls/ioctls.h
- libos/test/regression/device_ioctl.c
- libos/test/regression/device_ioctl.manifest.template
- libos/test/regression/device_ioctl_parse_fail.c
- libos/test/regression/device_ioctl_parse_fail.manifest.template
- libos/test/regression/test_libos.py
Continuation of #671. Last functionality part required.
Fixes #1378.
Depends on:
- https://github.com/gramineproject/device-testing-tools/pull/9
- https://github.com/gramineproject/gramine/pull/1481
Tests are augmented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1482)
> [common] Add `onlyif` syntax to flexible IOCTLs

- CI-Examples/busybox/README.md
- CI-Examples/python/README.md
- CI-Examples/ra-tls-mbedtls/README.md
- CI-Examples/ra-tls-secret-prov/README.md
- CI-Examples/rust/rust-hyper-http-server.manifest.template
Reported-by: Anjali Rai <anjali.rai@intel.com>
Fixes #1533.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1534)
> [CI-Examples] Fix links to Gramine's ReadTheDocs

- libos/include/arch/x86_64/linux_abi/errors_arch.h
- libos/include/libos_checkpoint.h
- libos/include/libos_thread.h
- libos/include/linux_abi/errors.h
- libos/include/linux_abi/types.h
- libos/src/arch/x86_64/libos_arch_prctl.c
- libos/src/bookkeep/libos_pid.c
- libos/src/bookkeep/libos_thread.c
- libos/src/fs/eventfd/fs.c
- libos/src/fs/tmpfs/fs.c
- libos/src/libos_rtld.c
- libos/src/sys/libos_dup.c
- libos/src/sys/libos_exec.c
- libos/src/sys/libos_getcwd.c
- libos/src/sys/libos_mlock.c
- libos/src/sys/libos_time.c
- libos/src/sys/libos_uname.c
This is a part of making our LibOS independent from the host headers (we want this b/c the host may not even be Linux).
Previous work from this series: https://github.com/gramineproject/gramine/pull/1275, https://github.com/gramineproject/gramine/pull/1301, #1426.
Just error codes, because it's already a lot of lines.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1541)
> [LibOS] Import Linux error codes

- libos/include/arch/x86_64/linux_abi/types_arch.h
- libos/include/libos_table.h
- libos/include/linux_abi/fs.h
- libos/include/linux_abi/poll.h
- libos/include/linux_abi/sysinfo.h
- libos/include/linux_abi/types.h
- libos/src/fs/libos_fs_pseudo.c
- libos/src/libos_parser.c
- libos/src/sys/libos_poll.c
- libos/src/sys/libos_uname.c
This is a part of making our LibOS independent from the host headers (we want this b/c the host may not even be Linux).
Continuation of #1275, #1301, #1426 and #1541.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1551)
> [LibOS] Import simple Linux types

- CONTRIBUTING.rst
- libos/test/ltp/README.rst
Found and asked to be fixed by @kailun-qin in #1562.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1564)
> [Docs] Mention that LTP may not work under SGX

- CI-Examples/common_tools/benchmark-http.sh
- CI-Examples/ra-tls-mbedtls/Makefile
- CI-Examples/ra-tls-nginx/run.sh
- libos/test/regression/eventfd.c
Replace sleeps with more appropriate wait-for tools, or at least shorten the sleep interval.
CI is enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1565)
> [CI-Examples,tests] Remove/shorten `sleep` invocations

- packaging/docker/Dockerfile
Apply the good practice in our Dockerfile.
- clear the apt cache files after installation [DL3009](https://github.com/codacy/codacy-hadolint/blob/master/codacy-hadolint/docs/description/DL3009.md)
- execute update and install in the same "RUN" command. Docker caches each RUN statement. This means that the `apt update` and `apt install` can get unsynchronized, and `apt install` can report that some packages are missing.
```
docker build
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1583)
> Dockerfile optimization

- meson.build
- subprojects/curl-7.84.0.wrap
- subprojects/curl-8.4.0.wrap
- subprojects/packagefiles/curl-8.4.0/compile.sh
- subprojects/packagefiles/curl-8.4.0/meson.build
This version includes fixes for two CVEs affecting libcurl:
* CVE-2023-38545: severity HIGH,
* CVE-2023-38546: severity LOW.
**Note**: this is in preparation for the coming release (which'll happen on Oct 11) of libcurl which contains security fixes. Pls see https://github.com/curl/curl/discussions/12026 for details.
CI (unfortunately it'll fail currently due to the unavailability of the new libcurl package).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1596)
> [curl] Upgrade libcurl to version 8.4.0

- Documentation/index.rst
- Documentation/scag-installation.rst
Add documentation for a new method of "graminizing" apps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1578)
> Add documentation for Scaffolding

- packaging/docker/Dockerfile
- packaging/docker/build.sh
Allow to create images on ubuntu 20.04 and 22.04. 
I have run libos regression test suite on Ubuntu 22.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1614)
> [docker] Support multiple versions of Ubuntu

- .ci/lib/stage-clean-check.jenkinsfile
- .ci/lib/stage-test.jenkinsfile
- python/graminelibos/gen_jinja_env.py
- tests/test_ldd.py
Fix `ldd()` function in `gramine-manifest`, which probably never worked and had no tests.
See also: #1410.
Write some manifest using this function, see if it works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1411)
> [python] Fix `{{ ldd }}` and add test

- Documentation/performance.rst
This info was scattered around Gramine repositories. Let's summarize it in our documentation.
I enabled ReadTheDocs branch to look at it: https://gramine.readthedocs.io/en/dimakuv-docs-mention-libgomp-perf/performance.html#gnu-libgomp-performance-bottleneck.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1652)
> [Docs] Add section on patched `libgomp` to Perf doc

- subprojects/README.rst
This is to explain the usage of each subproject in the Gramine (and its tools) codebase.
I just found it useful to add such a file, since I needed to analyze the usages today.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1654)
> [Docs] Add README to the subprojects dir

- .github/ISSUE_TEMPLATE/config.yml
- README.rst
- SECURITY.md
The text is based on
https://github.com/electron/electron/blob/28-x-y/SECURITY.md.
The text is kept rather minimal as per discussions with @woju and @mkow.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1653)
> [Docs] Add SECURITY.md

- .ci/lib/stage-test.jenkinsfile
- tests/test_sgx_sign.py
Add new tests.
This test was requested in the PR: https://github.com/gramineproject/gramine/pull/1613
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1646)
> [tests] Introduce tests for PEM file signing functions

- Documentation/devel/features.md
Added descriptions of POSIX shared memory, POSIX semaphores, a note on `sendfile()` syscall, a note on `-EINPROGRESS` during non-blocking `connect()`, new "siblings" line in /proc/cpuinfo, three new files under /sys/devices/system/cpu/ (`kernel_max`, `offline`, `present`).
Fixes #1634.
Temporarily enabled in ReadTheDocs: https://gramine.readthedocs.io/en/dimakuv-docs-update-gramine-features-nov-2023/devel/features.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1663)
> [Docs] Update "Gramine features" with v1.6 features

- debian/changelog
- gramine.spec
- meson.build
- packaging/alpine/APKBUILD
This is release PR for 1.6.
This is 100% based on the previous PR for v1.5: https://github.com/gramineproject/gramine/pull/1437
TODOs:
Manual testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1677)
> Release 1.6

- .ci/check-rwx.py
- .ci/lib/stage-build-nosgx.jenkinsfile
- .ci/lib/stage-build-sgx-vm.jenkinsfile
- .ci/lib/stage-build-sgx.jenkinsfile
- .ci/lib/stage-test-direct.jenkinsfile
- .ci/lib/stage-test-sgx.jenkinsfile
Ensure that none of the binaries we distribute contain an RWX segment.
CI is sufficient.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1698)
> [CI] Enable RWX verification for all binaries

- pal/src/host/linux-sgx/pal_main.c
Gramine's logging configuration is done in the PAL-common logic (to avoid duplication), which is executed after the PAL-specific logic. So previously, the warnings about invalid search domain names and/or hostname (which are checked and produced during the PAL-specific logic) didn't show up in Gramine logs.
This commit saves the invalid DNS information, and prints the warnings in `post_callback()`, which is after logging is configured.
Fixes https://github.com/gramineproject/gramine/issues/1626.
Manual testing w/ invalid search domain names in `/etc/resolv.conf` or hostname.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1630)
> [PAL/Linux-SGX] Log invalid search domains/hostname in `post_callback()`

- meson.build
- subprojects/curl-8.4.0.wrap
- subprojects/curl-8.5.0.wrap
- subprojects/packagefiles/curl-8.5.0/compile.sh
- subprojects/packagefiles/curl-8.5.0/meson.build
This version includes fixes for two CVEs affecting libcurl:
* CVE-2023-46218: severity Medium,
* CVE-2023-46219: severity Medium.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1697)
> [curl] Upgrade libcurl to version 8.5.0

- Documentation/devel/building.rst
- Documentation/devel/howto-doc.rst
- Documentation/run-sample-application.rst
- Documentation/sgx-setup.rst
Rearrange some paragraphs of building instructions and add a troubleshooting subsection under 'run a sample application'.
Build and verify documentation locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1676)
> [Docs] Adjust building instructions paragraphs

- libos/src/bookkeep/libos_signal.c
Gramine allows to inject only one SIGTERM (signal number 15). To distinguish a case when SIGTERM was already injected, LibOS atomically updates a global variable to a special value meaning "SIGTERM was injected". Previously, this special value was chosen as `0xff` for no obvious reason. This leads to an artificial requirement that valid signals cannot have numbers great than or equal to 255 (`0xff`).
This commit removes this artifical requirement by replacing `0xff` with `-1`. This is possible because signals are always of type `int`.
Suggested by @mkow . See discussions in #1703 
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1766)
> [LibOS] Use `-1` for special signal value instead of `0xff`

- Documentation/attestation.rst
As described in the title.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1750)
> [Docs] Fix broken link to "Marblerun docs on Gramine integration"

- libos/test/regression/large_file.c
- tools/sgx/common/pf_util.c
Valid error numbers are all positive numbers in libc.
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1743)
> [tools,tests] Fix incorrect errno checking

- debian/changelog
- gramine.spec
- meson.build
- packaging/alpine/APKBUILD
Release PR for 1.6.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1770)
> Release 1.6.1

- libos/test/regression/test_libos.py
Just a quick fixup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1775)
> [tests] Fix a duplicated test number in LibOS tests

- README.rst
We have completed the self-certification for the basic ("passing") level in the [OpenSSF Best Practices Badge Program](https://www.bestpractices.dev/en). See https://www.bestpractices.dev/en/projects/8380 for details.
According to the previous community meeting discussions https://github.com/gramineproject/gramine/discussions/1740, we planned to achieve the silver level (and we are currently 96% done). But there still seems to be several blockers, in particular:
* The project MUST be able to repeat the process of generating information from source files and get exactly the same bit-for-bit result. Related to https://github.com/gramineproject/gramine/issues/153.
* The project MUST cryptographically sign releases of the project results intended for widespread use, and there MUST be a …
> [Docs] Add OpenSSF Best Practices Badge

- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files_format.h
- common/src/protected_files/protected_files_internal.h
Obvious cleanup.
Already covered by existing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1789)
> [common/protected_files] Remove unused fields

- libos/src/sys/libos_alarm.c
Though there is not much we could do when `install_async_event()` fails, it's better to check the return of it and print a warning message if this fails.
CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1786)
> [LibOS] Log itimer event re-registration failure in callback

- pal/src/host/linux-sgx/pal_files.c
- pal/src/host/linux-sgx/pal_host.h
- pal/src/host/linux/pal_files.c
- pal/src/host/linux/pal_linux.h
- pal/src/host/skeleton/pal_files.c
Some trivial changes which I wanted to do long time ago.
Should be useful before we start real work on refactoring Trusted Files.
Existing tests are enough. No functional changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1790)
> [PAL] Refactor `pal_files.c` code (trivial changes)

- libos/include/libos_handle.h
- libos/include/libos_internal.h
- libos/src/fs/eventfd/fs.c
- libos/src/libos_init.c
- libos/src/sys/libos_eventfd.c
- libos/test/regression/eventfd.c
- libos/test/regression/eventfd_fork.c
- libos/test/regression/eventfd_fork.manifest.template
- libos/test/regression/meson.build
- libos/test/regression/test_libos.py
- libos/test/regression/tests.toml
- libos/test/regression/tests_musl.toml
This PR refactors eventfd code, in preparation for a second, secure (not passthrough-to-host) implementation of eventfd. The corresponding `eventfd` test is split into two tests: a single-process test and a new multi-process (forking) test. This is because the new secure implementation of eventfd will only be applicable to single-process applications.
For context, see:
- https://github.com/gramineproject/gramine/discussions/1713
- https://github.com/gramineproject/gramine/discussions/1413
CI. No functional change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1727)
> [LibOS] Refactor eventfd implementation and corresponding tests

- libos/src/fs/chroot/encrypted.c
- libos/test/regression/.gitignore
- libos/test/regression/Makefile
- libos/test/regression/manifest.template
- libos/test/regression/sealed_file.c
- libos/test/regression/test_libos.py
~~Previously, LibOS unconditionally set up the inode of the dentry on first lookup, for example, querying the size of the underlying file and saving it into inode fields. This setup of dentry's inode is not needed in cases like file removal (`unlink()`), since the inode will be immediately removed after it was set up. This was particularly painful for encrypted files (as they would open and decrypt the underlying file on inode setup) and tmpfs files (as they would allocate an underlying memory region for file contents on inode setup). Moreover, encrypted files were decrypted on lookup, just to get the real file size; this failed `unlink()` on corrupted or encrypted-with-old-key files.~~
~~This PR allows to skip the setup of the inode. Currently this is only used for the `unlink()` system …
> [LibOS] Allow `unlink()` on corrupted encrypted files 

- Documentation/devel/features.md
- common/src/protected_files/README.rst
- common/src/protected_files/protected_files.c
- common/src/protected_files/protected_files.h
- libos/src/fs/chroot/encrypted.c
- libos/test/fs/seek_tell_truncate.c
- libos/test/fs/test_enc.py
- libos/test/fs/test_fs.py
Fixes #950.
Closes #972.
Tests included in PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1785)
> [common/protected_files] Add support for arbitrary truncation

- Documentation/scag-installation.rst
Like in the title.
No need.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1838)
> [Docs] Update the gramine-scaffolding GitHub repository link

- debian/changelog
- gramine.spec
- meson.build
- packaging/alpine/APKBUILD
Release checklist: #1847
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1848)
> Release 1.7

- Documentation/devel/building.rst
- Documentation/sgx-intro.rst
As in the title. Still not complete, but it's already a lot of changes, so I'd prefer to do the rest in a follow-up PR.
Render the docs and read.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1827)
> [Docs] Add more documentation about SGX

- common/src/protected_files/protected_files.c
This commit refactors PF code without changing functionality (part 3 in a series of commits). In particular, this commit simplifies function `ipf_update_all_data_and_mht_nodes()`.
Extracted from https://github.com/gramineproject/gramine/pull/1841 at the request of @mkow.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1868)
> [common] Refactor Protected Files, part 3

- gramine.spec
1. build the package
2. try `rpm -q --specfile gramine.spec --define 'dist .el9' --qf '%{nvr}'`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1886)
> [rpm] Simplify `has_supported_sphinx` definition

- Documentation/manpages/is-sgx-available.rst
- tools/sgx/is-sgx-available/is_sgx_available.cpp
Run the tool on a server with these feature and without.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1890)
> [tools/sgx] Detect EDECCSSA and AEX-Notify in `is-sgx-available`

- Documentation/installation.rst
- Removed outdated information about the supported image distros
- Updated Docker run command to include provisioning device
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1905)
> [Docs] Update Gramine Docker image usage

- CI-Examples/busybox/README.md
For details see #1909.
This doesn't fix the problem, just mentions it to users in the README.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1910)
> [CI-Examples] busybox: Add note on build failure on Ubuntu 24.04

- .ci/lib/stage-build-sgx.jenkinsfile
- .ci/linux-sgx-edmm.jenkinsfile
- .ci/linux-sgx-sanitizers.jenkinsfile
- .ci/linux-sgx-ubuntu20.04-gcc-release-apps.jenkinsfile
- .ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- .ci/linux-sgx-ubuntu20.04-musl.jenkinsfile
- .ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile
- .ci/linux-sgx-ubuntu24.04-gcc-release.jenkinsfile
See commit
CI only, no way to test manually
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1920)
> [CI] Change default SGX driver to upstream

- .ci/alpine3.17.dockerfile
- .ci/pkg-apk-alpine3.17.jenkinsfile
Attempt to fix the alpine pipeline.
CI/CD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1942)
> Attempt to fix alpine

- CI-Examples/rust/README.md
Fixes #1950.
N/A.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1952)
> [CI-Examples] Rust: add note on need for latest Rust compiler

- common/include/pal_error.h
- pal/src/host/linux/pal_main.c
Fixes that were promised during #1900.
Ci/CD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1960)
> Fix exit_group status code and include

- libos/src/libos_init.c
Small change as in the title.
CI/CD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1966)
> [LibOS] Refactor pal_to_unix_errno function to only accept known values

- tools/sgx/ra-tls/ra_tls_attest.c
I was a bit annoyed by this function when reviewing #1039, so I refactored the code slightly.
CI, no functionality changes intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1967)
> [tools/RA-TLS] Add more readable rw_file() wrappers

- Documentation/devel/onboarding.rst
- pal/src/host/linux-sgx/enclave_ocalls.c
- pal/src/host/linux-sgx/host_exception.c
- pal/src/host/linux-sgx/host_internal.h
- pal/src/host/linux-sgx/host_profile.c
- pal/src/host/linux-sgx/pal_rtld.c
Seems we forgot that.
Just read the comments and verify.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/1970)
> [PAL/Linux-SGX,Docs] Update comments after the recent file renamings

- python/graminelibos/regression.py
See commit message
```sh
cd libos/tests/regression
python3 -m pytest 
```
Reported by @anjalirai-intel 
Fixes: #2038
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2041)
> [python] Fix GDB version detection to account for

- debian/changelog
- debian/control
- gramine.spec
- meson.build
- packaging/alpine/APKBUILD
Release PR for v1.8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2022)
> Release 1.8

- packaging/docker/Dockerfile
- packaging/docker/build.sh
Add support for Ubuntu Noble.
Build image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2045)
> [docker] Add support for Ubuntu Noble

- Documentation/devel/building.rst
More cleanup of docs which I've stumbled upon.
```sh
make -C Documentation html && firefox Documentation/_build/html/devel/building.html
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2055)
> [Docs] Remove more Focal leftovers from building.rst

- Documentation/manifest-syntax.rst
- libos/test/regression/mock_syscalls.manifest.template
- libos/test/regression/toml_parsing.manifest.template
- pal/src/pal_main.c
- python/graminelibos/manifest.py
Please verify that I didn't miss any place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2054)
> Drop deprecated syntax of loader.entrypoint

- python/graminelibos.dist-info/meson.build
- subprojects/packagefiles/mbedtls/meson.build
- tools/pf_crypt/meson.build
- tools/pf_tamper/meson.build
- tools/sgx/common/meson.build
- tools/sgx/is-sgx-available/meson.build
- tools/sgx/quote-view/meson.build
- tools/sgx/ra-tls/meson.build
Split off #2088, because `.el10` is expected "mid-2025", but we can fix stuff earlier. See commit messages for individual fixes.
Please see #2088 CI pipelines, esp. `pkg-rpm-almalinux10`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gramine/2090)
> Random fixes before AlmaLinux (RHEL) 10
